(() => {
  'use strict';
  window.CDRWorkspaceFactory = function(ctx){
    const {$,state,download,dtFmt,applyFilters,incidentDateTime,refreshSelectors,renderAll,renderFileList,safeName,showStatus,stableKey,audit,rebuildIndexes}=ctx;

  function filterSnapshot(){const ids=['q','dateFrom','dateTo','timeFrom','timeTo','bparty','durMin','durMax','callType','cellId','tower','city','subcity','roaming','imei','imsi','provider','operator','cdrNo','sourceFile','nightFrom','nightTo','episodeGapMins','movementDateFrom','movementDateTo','smsIntelCdr','smsIntelFrom','smsIntelTo','smsIntelNightFrom','smsIntelNightTo','smsIntelCallMins','smsIntelIdMins','smsIntelContextMins','smsIntelBurstMins','smsIntelBurstMinCount','smsIntelBurstMode','smsIntelIncidentMins','smsIntelSearch','smsIntelFilterCategory','smsIntelFilterRecognition','locationMatchMode','locationMatchMins','locationEpisodeGapMins','locationMatchFrom','locationMatchTo'];const o={};ids.forEach(id=>o[id]=$(id)?.value??'');['callsOnly','smsOnly','nightOnly','weekendOnly','excludeServiceSenders','smsIntelFirstOnly','smsIntelIncidentOnly','smsIntelUnusualOnly'].forEach(id=>o[id]=!!$(id)?.checked);return o;}
  function applyFilterSnapshot(o={}){for(const [id,v] of Object.entries(o)){const el=$(id);if(!el)continue;if(el.type==='checkbox')el.checked=!!v;else el.value=v;}}
  function workspacePayload(){const noteByKey={},flagKeys=[];for(const r of state.records){const k=stableKey(r);if(state.flags.has(r.id))flagKeys.push(k);if(state.notes[r.id])noteByKey[k]=state.notes[r.id];}return {version:4,savedAt:new Date().toISOString(),appVersion:state.appVersion||'',case:{title:$('caseTitle').value,caseNo:$('caseNo').value,station:$('station').value,analyst:$('analyst').value,incidentDate:$('incidentDate').value,incidentTime:$('incidentTime').value,incidentWindowHours:6},settings:{analysisMode:state.analysisMode,sourceTimezone:state.sourceTimezone,mapPrivacyMode:!!state.mapPrivacyMode},filters:filterSnapshot(),generalNote:$('generalNote').value,caseContactTags:state.contactTags,caseContactNames:state.contactNames,locationMatchSelected:[...state.locationMatchSelected],chronology:state.chronology,auditTrail:state.auditTrail,exactIncidentRange:state.exactIncidentRange?{start:state.exactIncidentRange.start.toISOString(),end:state.exactIncidentRange.end.toISOString()}:null,flagKeys,noteByKey,files:state.files.map(f=>({name:f.name,sheet:f.sheet,rows:f.rows,inferredCdr:f.inferredCdr,sha256:f.sha256||'',size:f.size||0,lastModified:f.lastModified||'',importedAt:f.importedAt||'',sourceTimezone:f.sourceTimezone||'',headers:f.headers||[],map:f.map||{}}))};}
  function saveWorkspace(){audit('Workspace exported',$('caseNo').value||$('caseTitle').value||'');download(`${safeName($('caseNo').value||$('caseTitle').value)}_cdr_workspace.json`,JSON.stringify(workspacePayload(),null,2),'application/json');}
  function restorePendingWorkspace(){const w=state.pendingWorkspace;if(!w)return;const byKey=new Map(state.records.map(r=>[stableKey(r),r]));state.flags.clear();state.notes={};for(const k of w.flagKeys||[]){const r=byKey.get(k);if(r)state.flags.add(r.id);}for(const [k,note] of Object.entries(w.noteByKey||{})){const r=byKey.get(k);if(r)state.notes[r.id]=note;}}
  function loadWorkspaceObject(w){if(!w||typeof w!=='object')throw new Error('Invalid workspace JSON');state.pendingWorkspace=w;const c=w.case||{};$('caseTitle').value=c.title||'';$('caseNo').value=c.caseNo||'';$('station').value=c.station||'';$('analyst').value=c.analyst||'';$('incidentDate').value=c.incidentDate||'';$('incidentTime').value=c.incidentTime||'';$('generalNote').value=w.generalNote||'';state.contactTags=w.caseContactTags||w.contactTags||{};state.contactNames=w.caseContactNames||w.contactNames||{};state.locationMatchSelected=new Set(Array.isArray(w.locationMatchSelected)?w.locationMatchSelected:[]);state.chronology=Array.isArray(w.chronology)?w.chronology:[];state.auditTrail=Array.isArray(w.auditTrail)?w.auditTrail:[];const settings=w.settings||{};state.analysisMode=settings.analysisMode==='unique'?'unique':'raw';state.sourceTimezone=settings.sourceTimezone||'Asia/Kolkata';state.mapPrivacyMode=!!settings.mapPrivacyMode;if($('analysisMode'))$('analysisMode').value=state.analysisMode;if($('sourceTimezone'))$('sourceTimezone').value=state.sourceTimezone;if($('mapPrivacyMode'))$('mapPrivacyMode').checked=state.mapPrivacyMode;state.exactIncidentRange=w.exactIncidentRange?{start:new Date(w.exactIncidentRange.start),end:new Date(w.exactIncidentRange.end)}:null;if($('exactIncidentStatus')&&state.exactIncidentRange)$('exactIncidentStatus').textContent=`Exact filter active: ${dtFmt(state.exactIncidentRange.start)} → ${dtFmt(state.exactIncidentRange.end)}`;applyFilterSnapshot(w.filters||{});restorePendingWorkspace();rebuildIndexes();audit('Workspace loaded',w.savedAt||'');applyFilters();showStatus(`Workspace restored${state.records.length?' and matched to loaded CDR rows':' — now load the referenced CDR file(s)'}.`,'ok');}
  function clearLoaded(){for(const c of Object.values(state.charts)){try{c.destroy()}catch{}}state.charts={};state.records=[];state.filtered=[];state.files=[];state.flags.clear();state.notes={};state.chronology=state.chronology.filter(x=>x.source==='Manual');state.exactIncidentRange=null;state.fileSeq=0;rebuildIndexes([]);audit('Loaded CDR data cleared','Raw rows removed from current session');refreshSelectors();renderFileList();renderAll();showStatus('Loaded CDR data cleared. Case metadata and notes fields were left in place.','ok');}
  function applyIncidentWindow(){const inc=incidentDateTime();if(!inc){showStatus('Save the case with an incident date and time first.','error');return;}const hours=6,h=hours*3600000;const a=new Date(inc-h),b=new Date(inc+h);state.exactIncidentRange={start:a,end:b};$('dateFrom').value='';$('dateTo').value='';$('timeFrom').value='';$('timeTo').value='';if($('exactIncidentStatus'))$('exactIncidentStatus').textContent=`Exact filter active: ${dtFmt(a)} → ${dtFmt(b)}`;applyFilters();showStatus(`Applied exact ±${hours} hour incident window (${dtFmt(a)} to ${dtFmt(b)}).`,'ok');}

    return {filterSnapshot,applyFilterSnapshot,workspacePayload,saveWorkspace,restorePendingWorkspace,loadWorkspaceObject,clearLoaded,applyIncidentWindow};
  };
})();
