/* Transcribed and concisely labelled from user-provided 24-page annexure. Historic legal references retained; verify current law. */
window.InvestigationAnnexure = {
  "source": "Check lists- Annexure.pdf, 24 pages",
  "referenceNote": "Reference checklist from supplied annexure, with concise wording. Historic Cr.P.C. / IPC / Indian Evidence Act citations are retained. Verify current BNS / BNSS / BSA sections and procedural requirements. Entries are not legal-compliance certification.",
  "categories": [
    {
      "id": "hurt",
      "title": "Bodily Offences / Hurt / Rioting",
      "pages": "1–2",
      "sourceCount": 29,
      "items": [
        "First Information Report",
        "Complaint Copy – Original",
        "Case Diary with page numbers",
        "Photograph / Videograph of SOC",
        "Observation Mahazar",
        "Rough Sketch",
        "Seizure Mahazar at SOC",
        "Dog / FP / Scientific Expert visit (if necessary)",
        "Statements of Witnesses",
        "Wound Certificate(s)",
        "Form 91 – send properties",
        "CDR Tower Dump – 65-B IEA Certificate",
        "Overt Act table – accused, weapon, injured, injury site and type (if 2+ accused / injured)",
        "Arrest of Accused",
        "Arrest Intimation",
        "Confession Statement",
        "S.27 IEA Seizure Mahazar / weapon / materials",
        "Photograph / Finger Print of Accused",
        "Remand Report",
        "Section Addition / Deletion Report",
        "Doctor's opinion on weapon and injuries",
        "Motor Vehicle details / documents / ownership",
        "Accused / Victim Vehicles sent for MV Inspection",
        "MVI Report / Damage / Value",
        "Firearms / Explosives / Acid / Inflammable Oil used",
        "Ballistics / Explosives / Oil Analysis Reports",
        "Serology Reports",
        "Final Medical Opinion on injuries",
        "Anticipatory Bail / Surrender / Police Custody details"
      ]
    },
    {
      "id": "murder",
      "title": "Murder / Murder for Gain",
      "pages": "3–5",
      "sourceCount": 48,
      "items": [
        "First Information Report",
        "Complaint / Death Intimation",
        "Dying Declaration by JM / Doctor / other available person",
        "SOC Photograph / Videograph",
        "Observation Mahazar",
        "Rough Sketch",
        "Dog / FP / Scientific Expert visit",
        "Seizure Mahazar at SOC",
        "Inquest Report",
        "PM Requisition / History of Case",
        "Viscera / Hyoid / Femur bone for DNA to FSL",
        "Skull for Superimposition test (if arises)",
        "Special Report of PM Police Constable with properties",
        "AR Entry in Hospital",
        "Wound Certificate Requisition",
        "Form 91 – properties to Court",
        "CDR / Tower Location and 65-B IEA Certificate",
        "CCTV footage and 65-B IEA Certificate",
        "Overt Act table – accused, weapon, injured, injuries",
        "Arrest of Accused",
        "Arrest Intimation",
        "Confession Statement",
        "S.27 IEA Recovery Mahazar – weapon / materials",
        "Accused Photograph / Finger Print",
        "Remand Report",
        "Affidavit for custody (if required)",
        "Search intimation / warrant requisition",
        "House Search / Seizure / Form 91",
        "Section Alteration / Addition Report",
        "Anticipatory Bail / Surrender / Police Custody",
        "Identification of deceased belongings by kin / witnesses",
        "PM Doctor opinion on weapon, injuries and cause of death",
        "Vehicle details / ownership (own / hired / stolen)",
        "MV Inspection and MVI Report",
        "Postmortem Certificate",
        "TNFSL Viscera / DNA / Serology Reports",
        "Final Medical / PM Doctor Opinion",
        "Second Opinion Requisition to Joint Director Medical Services (if arises)",
        "Questionnaires on Second Opinion",
        "Replies to Questionnaires and Second Opinion",
        "Test Identification Parade (if any)",
        "Witness Statements u/s 161(3) Cr.P.C.",
        "Statements u/s 164 Cr.P.C. (if any)",
        "Accused turned Approver (if any)",
        "Accused Addition / Deletion Report (if arises)",
        "Final Report / Charge Sheet",
        "Memo of Evidence",
        "List of Documents / Witnesses"
      ]
    },
    {
      "id": "robbery",
      "title": "Robbery / Dacoity",
      "pages": "6–8",
      "sourceCount": 59,
      "items": [
        "First Information Report",
        "Complaint / Hospital / Death Intimation",
        "Case Diary with page numbers",
        "Dying Declaration",
        "SOC Photograph / Videograph",
        "Observation Mahazar",
        "Rough Sketch",
        "Dog / FP / Scientific Expert visit",
        "SOC Seizure Mahazar – weapon / stains / cigarette butt etc.",
        "Inquest Report (396 IPC case)",
        "Witness Statements",
        "Medical Officer Requisition / History",
        "PM / Wound Certificate(s)",
        "Special Report of PM Police Constable with properties",
        "Form 91 for properties after PM",
        "Viscera / Hyoid / Femur bone for DNA / FSL",
        "Skull Superimposition Test (if arises)",
        "Criminals Checked / Crime Cards",
        "Advisory Memo complied with",
        "Crime Records entries (Part-I etc.)",
        "Recently released jail prisoners checked",
        "Other District DCRB / SCRB visited",
        "Photo Album of accused / suspects shown to witnesses",
        "CDR Tower Dump and 65-B IEA Certificate",
        "Overt Act table for accused, injured, deceased and weapons",
        "Arrest of Accused",
        "Arrest Intimation",
        "Confession Statement",
        "S.27 IEA Recovery Mahazar – weapon / materials",
        "Accused Photograph / Finger Print",
        "Remand Report",
        "Section Alteration / Addition Report",
        "Identification of complainant / victim belongings after recovery",
        "PM Doctor opinion on weapon and injuries",
        "Vehicle details / documents / ownership",
        "MV Inspection of vehicles",
        "MVI Report / Damage / Value",
        "Firearms / Explosives / Acid involved",
        "Ballistics / Explosives Analysis",
        "Viscera / DNA / Serology Reports",
        "Final Medical / PM Opinion",
        "Requisition for PM Fair Copy (if necessary)",
        "Postmortem Fair Copy",
        "Second Opinion Requisition to Joint Director Medical Services",
        "Second Opinion Questionnaires to Medical Officer",
        "Doctor's Replies and Second Opinion",
        "Anticipatory Bail / Surrender / Police Custody",
        "Test Identification Parade",
        "Statements u/s 164 Cr.P.C. (if necessary)",
        "Accused Approver (if any)",
        "Case Diaries with dated supporting records",
        "IO / Law Officer Draft Opinion",
        "Final Report / Charge Sheet",
        "Memo of Evidence",
        "List of Documents",
        "GCR Report",
        "Accused Addition / Deletion Report",
        "Detention Forecast Register entry",
        "Tamil Nadu Act 14/1982 action (if any)"
      ]
    },
    {
      "id": "rape",
      "title": "Rape / Sexual Offences",
      "pages": "9–10",
      "sourceCount": 38,
      "items": [
        "Original Complaint",
        "First Information Report",
        "Passport of tapal orderly submitting FIR to designated Court",
        "District Legal Services Authority victim compensation recommendation",
        "Case Diary with page numbers",
        "Rough Sketch",
        "Observation Mahazar",
        "Confession Statement",
        "Seizure Mahazar",
        "Letters seized",
        "Clothes seized",
        "Lodge / Resort Receipt seized",
        "CCTV footage of Lodge / Resort",
        "Victim medical prescription",
        "Seized mobile / landline payment details",
        "Victim Interview Report",
        "Accused Interrogation Report",
        "Arrest Intimation",
        "Arrest Card",
        "Prisoner Search Register extract",
        "Victim Photograph",
        "Accused Photograph",
        "Form 91",
        "Remand Report",
        "Petition to add Section of Law",
        "Petition to Magistrate for medical examination of rescued victim",
        "Petition for statements u/s 164 Cr.P.C.",
        "Petition for Test Identification Parade",
        "Sexually Transmitted Disease Certificate of victim",
        "Victim Age Certificate",
        "Accused Potency Certificate",
        "Statement recorded u/s 164 Cr.P.C.",
        "Test Identification Parade proceedings",
        "Mobile provider 65-B IEA Certificate, CDR / CAF",
        "Witness Statements",
        "List of Documents",
        "Memorandum of Evidence",
        "Final Report"
      ]
    },
    {
      "id": "pocso",
      "title": "POCSO Act",
      "pages": "11–12",
      "sourceCount": 39,
      "items": [
        "First Information Report",
        "Complaint / Hospital Intimation",
        "Case Diary with page numbers",
        "SOC and Victim Statement Photograph / Video",
        "Observation Mahazar",
        "Rough Sketch",
        "Scientific / FP Expert visit",
        "SOC Seizure Mahazar",
        "Victim Clothes / Ornaments Seizure",
        "Witness Statements",
        "Victim Medical / Age Examination Requisition",
        "Vaginal Swab / Foreign Hair / Nail Marks / Blood Samples",
        "Victim Medical Examination / Age Certificate",
        "Form 91",
        "Section Alteration Report",
        "School Certificate / other age documents",
        "CDR Tower Dump and 65-B IEA Certificate",
        "Overt Act table for multiple accused",
        "Arrest of Accused",
        "Arrest Intimation",
        "Confession Statement",
        "S.27 IEA Recovery – weapon / materials / accused clothes",
        "Suspect Photograph / Finger Print at SOC",
        "Accused Medical / Age Examination Requisition",
        "DNA Test (if necessary)",
        "Accused Medical / Age Certificate",
        "Victim / kin identification of belongings",
        "Test Identification Parade",
        "Victim Statement u/s 164 Cr.P.C.",
        "Accused Approver (if necessary)",
        "Dated Case Diaries with documents",
        "IO / Law Officer Draft Opinion",
        "Charge Sheet within 60 days (source wording; verify current law)",
        "Memo of Evidence",
        "List of Documents",
        "GCR Report",
        "Accused Addition / Deletion Report",
        "Detention Forecast Register entry (if any)",
        "In-camera trial (source wording; verify current law)"
      ]
    },
    {
      "id": "missing",
      "title": "Missing Persons",
      "pages": "13–14",
      "sourceCount": 23,
      "items": [
        "Complaint",
        "First Information Report",
        "Missing Person Photograph",
        "Printed / widely distributed missing-person pamphlets",
        "Letter to Regional Joint Director Medical Services",
        "Letter to PCW / DCRB / MOB",
        "Letter to Transport Corporation Depot Managers",
        "Letter to Government Railway Police",
        "Local TV Channel broadcast",
        "Referral to Anti-Human / Anti-Child Trafficking Units",
        "CBCID letter for other State Nodal Officers",
        "Newspaper notices including vernacular newspapers",
        "Display pamphlets at railway / bus / offices",
        "Letter to District Child Protection Officer / NGOs",
        "Case Diary updated",
        "Rough Sketch",
        "CCTV footage from disappearance area",
        "Notebook / diaries / loose sheets seized",
        "Mobile / landline / payment details analysed",
        "Petition to add Section of Law",
        "School Transfer / Birth Certificate verified",
        "Missing Person's CDR obtained",
        "Witness Statements obtained"
      ]
    },
    {
      "id": "scst",
      "title": "SC/ST Prevention of Atrocities Act",
      "pages": "15–16",
      "sourceCount": 43,
      "items": [
        "First Information Report",
        "Complaint / Death Intimation",
        "SP Proceedings with date",
        "Case Diary with page numbers",
        "SOC Photograph / Video",
        "Observation Mahazar",
        "Rough Sketch",
        "Scientific Expert (if arson)",
        "SOC Seizure Mahazar",
        "Tahsildar / RDO Community Certificate Requisition",
        "Victim Community Certificate",
        "Accused Community Certificate",
        "Wound Certificate(s)",
        "Damage Certificate / Property Value",
        "PM / Wound Certificate",
        "Victim Relief Fund – Initial Proposal",
        "Victim Relief Fund – After Charge Sheet Proposal",
        "CDR Tower Dump / 65-B IEA Certificate",
        "Overt Act table for multiple accused",
        "Arrest of Accused",
        "Arrest Intimation",
        "Confession Statement",
        "S.27 IEA Recovery Mahazar / weapons",
        "Accused Photograph / Finger Print",
        "Remand Report",
        "Section Alteration / Addition Report",
        "PM Doctor opinion on weapon / injuries",
        "Motor Vehicle / documents / owner details",
        "MV Inspection of vehicles",
        "MVI Report / Damage / Value",
        "Firearms / Explosives / Acid",
        "Ballistics / Explosives Analysis",
        "Anticipatory Bail / Surrender / Police Custody",
        "Test Identification Parade",
        "Statements u/s 164 Cr.P.C.",
        "Dated Case Diaries and documents",
        "IO / Law Officer Draft Opinion",
        "Charge Sheet",
        "Memo of Evidence",
        "List of Documents",
        "GCR Report",
        "Accused Addition / Deletion Report",
        "Detention Forecast Register entry"
      ]
    },
    {
      "id": "blast",
      "title": "Bomb Blast / Explosion",
      "pages": "17–18",
      "sourceCount": 42,
      "items": [
        "First Information Report",
        "Complaint / Death Intimation",
        "Dying Declaration (if necessary)",
        "SOC Photograph / Video",
        "Observation Mahazar",
        "Rough Sketch",
        "Dog / FP / Scientific Expert / Bomb Disposal Squad Visit",
        "SOC Seizure Mahazar",
        "Inquest Report (if death)",
        "PM Requisition / History",
        "Viscera to FSL",
        "Skull Superimposition Test (if required)",
        "PM Constable Special Report with properties",
        "Form 91 – Court Properties",
        "CDR / Tower Locations and 65-B IEA Certificate",
        "CCTV 65-B IEA Certificate",
        "Arrest of Accused",
        "Arrest Intimation",
        "Confession Statement",
        "S.27 IEA Recovery Mahazar",
        "Accused Photograph / Finger Print",
        "Remand Report",
        "Custody Affidavit (if required)",
        "Search Intimation / Warrant",
        "House Search of accused premises",
        "Section Alteration / Addition Report",
        "Anticipatory Bail / Surrender / Custody",
        "Vehicle ownership and documents",
        "MVI Report / Vehicle Damage",
        "Explosives Analysis Report",
        "Viscera / Serology Reports",
        "Final Medical / PM Opinion",
        "Postmortem Certificate",
        "Test Identification Parade",
        "Statements u/s 161(3) Cr.P.C.",
        "Statements u/s 164 Cr.P.C.",
        "Accused Approver (if any)",
        "Accused Addition / Deletion Report",
        "Competent Authority Damage / Loss Certificate",
        "Final Report / Charge Sheet",
        "Memo of Evidence",
        "List of Documents / Witnesses"
      ]
    },
    {
      "id": "tnppdl",
      "title": "Tamil Nadu Public Property Damage / Loss Act",
      "pages": "19–20",
      "sourceCount": 33,
      "items": [
        "First Information Report",
        "Complaint Copy",
        "SOC Photograph / Video",
        "Observation Mahazar",
        "Rough Sketch",
        "SOC Seizure Mahazar",
        "Inflammable Article / Burnt Material Seizure and FSL",
        "Form 91 to Court",
        "Competent Authority Property Damage Certificate",
        "CDR / Tower Locations / 65-B IEA Certificate",
        "CCTV 65-B IEA Certificate",
        "Arrest of Accused",
        "Arrest Intimation",
        "Confession Statement",
        "S.27 IEA Recovery Mahazar",
        "Accused Photograph / Finger Print",
        "Remand Report",
        "Custody Affidavit (if required)",
        "Search Intimation / Warrant",
        "House Search",
        "Seizure during House Search / Tools",
        "Section Alteration / Addition Report",
        "Anticipatory Bail / Surrender / Custody",
        "Motor Vehicle / Ownership Documents",
        "FSL Report",
        "Test Identification Parade",
        "Statements u/s 161(3) Cr.P.C.",
        "Statements u/s 164 Cr.P.C.",
        "Accused Approver (if any)",
        "Accused Addition / Deletion Report",
        "Final Report / Charge Sheet",
        "Memo of Evidence",
        "List of Documents / Witnesses"
      ]
    },
    {
      "id": "cyber",
      "title": "Cyber Crime",
      "pages": "21–22",
      "sourceCount": 35,
      "items": [
        "First Information Report",
        "Complaint Copy",
        "Case Diary with page numbers",
        "SOC Photograph / Video",
        "Observation Mahazar",
        "Rough Sketch",
        "SOC Seizure Mahazar",
        "FP / Scientific Expert visit",
        "Witness Statements",
        "Form 91 – Court Properties",
        "CDR / IPDR / Tower Dump / 65-B IEA Certificate",
        "Notice u/s 91 Cr.P.C. – Social Media / Banks / Wallet / ISP / MSP",
        "Provider Replies with 65-B IEA Certificate",
        "Social Media / Email / Website Screenshots and 65-B IEA Certificate",
        "Overt Act table – Cyber tool, platform, motive, victim loss",
        "Arrest of Accused",
        "Arrest Intimation",
        "Confession Statement",
        "S.27 IEA Recovery – Mobile / Login / Computer / Storage",
        "Accused Photograph / Finger Print",
        "Remand Report",
        "Section Alteration / Addition Report",
        "TNFSL Computer Division Report",
        "Anticipatory Bail / Surrender / Custody",
        "Test Identification Parade",
        "Statements u/s 164 Cr.P.C.",
        "Accused Approver (if necessary)",
        "Dated Case Diaries and linked documents",
        "IO / Law Officer Draft Opinion",
        "Charge Sheet",
        "Memo of Evidence",
        "List of Documents",
        "Accused Addition / Deletion Report",
        "Detention Forecast Register entry",
        "Victim Compensation Proposals"
      ]
    },
    {
      "id": "ficn",
      "title": "Fake Indian Currency Notes",
      "pages": "23–24",
      "sourceCount": 41,
      "items": [
        "First Information Report",
        "FIR copy to superior officers",
        "FIR copy to complainant",
        "FICN Seizure Mahazar",
        "Fake Note Confirmation Certificate",
        "Arrest of Accused",
        "Accused Confession",
        "Confession Witness Statements",
        "Mahazar Witness Statements",
        "Witness Statements on possession / circulation / source",
        "PSR Copy",
        "Seized Property to Court via Form 91",
        "Arrest Card",
        "Arrest Memo",
        "Arrest Intimation",
        "Accused Medical Check-up Memo",
        "Remand Report",
        "Accused Photograph",
        "Accused Finger Print",
        "Accused Interrogation Report",
        "Vehicle used – details",
        "Accused Personal Property sent to Prison",
        "Weapons / Arms / Ammunition details",
        "FICN Serial Numbers / Denominations",
        "Genuine Currency Note particulars",
        "Printing Equipment particulars",
        "Printing Place Owner / Rental particulars",
        "Seizure Videography",
        "Low / High Quality status",
        "Expert Opinion obtained",
        "High Quality – consideration of UAP Act",
        "Permission to invoke UAP Act",
        "Intimation to Central Government through State Government",
        "Government Prosecution Sanction Order",
        "Arms Act Sanction from COP (if applicable)",
        "Draft Charge Sheet from APP",
        "Draft Charge Sheet approved by PP",
        "Final Report",
        "Memo of Evidence",
        "List of Documents",
        "GCR Report"
      ]
    }
  ]
};
