import json, random, os
from collections import defaultdict, Counter

OUT="data/textbook/class-11/history/unit-15.json"
random.seed(1502026)

# page_en, kind, description_en, answer_en, description_ta, answer_ta
F=[
# Introduction and causes
(225,"role","Power whose decline was accelerated by the Marathas","Mughal power","மராத்தியர்கள் வீழ்ச்சியடையச் செய்த முக்கிய சக்தி","முகலாய ஆட்சி"),
(225,"period","Decade in which Shivaji posed a strong challenge to Mughal power","1670s","சிவாஜி முகலாயருக்கு வலுவான சவால் விடுத்த காலம்","1670கள்"),
(225,"period","Period by which Marathas displaced Mughal power in central India","Middle of the 18th century","மராத்தியர்கள் மத்திய இந்தியாவில் முகலாய ஆதிக்கத்தை அகற்றிய காலம்","18ஆம் நூற்றாண்டின் நடுப்பகுதி"),
(225,"date","Year Nayak rule ended in Thanjavur","1674","தஞ்சாவூரில் நாயக்கர் ஆட்சி முடிந்த ஆண்டு","1674"),
(225,"person","Maratha general who invaded Thanjavur and established Maratha power there","Venkoji","தஞ்சாவூரில் மராத்திய ஆட்சியை நிறுவிய மராத்திய தளபதி","வெங்கோஜி"),
(225,"relation","Venkoji's relationship to Shivaji","Half-brother","வெங்கோஜிக்கும் சிவாஜிக்கும் உள்ள உறவு","ஒன்றுவிட்ட சகோதரர்"),
(225,"power","Army under whose banner Venkoji invaded Thanjavur","Bijapur forces","வெங்கோஜி தஞ்சாவூரை ஆக்கிரமித்தபோது வழிநடத்திய படை","பிஜாப்பூர் படை"),
(225,"period","Duration of Maratha rule in Thanjavur stated in the introduction","1674–1832","அறிமுகத்தில் கூறப்பட்ட தஞ்சாவூர் மராத்திய ஆட்சிக்காலம்","1674–1832"),
(225,"person","Ruler whose death in 1832 marked the end point cited for Thanjavur Maratha rule","Serfoji II","1832இல் இறந்து தஞ்சாவூர் மராத்திய ஆட்சியின் இறுதிக்காலத்துடன் தொடர்புடையவர்","இரண்டாம் சரபோஜி"),
(225,"region","Narrow strip of land central to the Maratha homeland","Konkan","மராத்தியர் தாயகத்தின் குறுகிய நிலப்பகுதி","கொங்கண்"),
(225,"feature","Physical feature that favoured Maratha military defence","Precipitous mountains","மராத்திய இராணுவப் பாதுகாப்புக்கு உதவிய நில அமைப்பு","செங்குத்தான மலைகள்"),
(225,"feature","Another physical feature favouring Maratha defence","Inaccessible valleys","மராத்திய பாதுகாப்புக்கு உதவிய மற்றொரு நில அமைப்பு","அணுக முடியாத பள்ளத்தாக்குகள்"),
(225,"feature","Fortification feature favouring Maratha defence","Impregnable hill-forts","மராத்திய பாதுகாப்புக்கு உதவிய கோட்டை அம்சம்","தகர்க்க முடியாத மலைக்கோட்டைகள்"),
(225,"quality","One martial quality claimed by the Marathas","Loyalty","மராத்தியர்கள் பெருமை கொண்ட போர்திறன் பண்புகளில் ஒன்று","விசுவாசம்"),
(225,"quality","One martial quality claimed by the Marathas","Courage","மராத்தியர்களின் போர்திறன் பண்புகளில் ஒன்று","துணிவு"),
(225,"quality","One martial quality claimed by the Marathas","Discipline","மராத்தியர்களின் போர்திறன் பண்புகளில் ஒன்று","ஒழுக்கம்"),
(225,"quality","One martial quality claimed by the Marathas","Cunningness","மராத்தியர்களின் போர்திறன் பண்புகளில் ஒன்று","தந்திரம்"),
(225,"quality","One martial quality claimed by the Marathas","Endurance","மராத்தியர்களின் போர்திறன் பண்புகளில் ஒன்று","தாங்கும் திறன்"),
(225,"service","Earlier rulers under whom Marathas had served before the Deccan Sultanates","Bahmani Sultans","தக்காண சுல்தானியங்களுக்கு முன் மராத்தியர்கள் சேவை செய்த ஆட்சியாளர்கள்","பாமினி சுல்தான்கள்"),
(225,"state","One post-Bahmani state under which Marathas served","Ahmednagar","பாமினி சிதைவுக்குப் பின் மராத்தியர்கள் சேவை செய்த அரசு","அகமதுநகர்"),
(225,"state","One post-Bahmani state under which Marathas served","Bijapur","பாமினி சிதைவுக்குப் பின் மராத்தியர்கள் சேவை செய்த அரசு","பிஜாப்பூர்"),
(225,"state","One post-Bahmani state under which Marathas served","Golconda","பாமினி சிதைவுக்குப் பின் மராத்தியர்கள் சேவை செய்த அரசு","கோல்கொண்டா"),
(225,"state","One post-Bahmani state under which Marathas served","Bidar","பாமினி சிதைவுக்குப் பின் மராத்தியர்கள் சேவை செய்த அரசு","பீதார்"),
(225,"state","One post-Bahmani state under which Marathas served","Berar","பாமினி சிதைவுக்குப் பின் மராத்தியர்கள் சேவை செய்த அரசு","பெரார்"),
(225,"warfare","Chief military strength of the Marathas","Guerrilla warfare","மராத்தியப் படையின் முக்கிய வலிமை","கெரில்லா போர்"),
(225,"tactic","Maratha tactic often executed at night","Surprise lightning attacks","மராத்தியர்கள் இரவில் பயன்படுத்திய முக்கிய போர் தந்திரம்","திடீர் மின்னல் தாக்குதல்கள்"),
(225,"movement","Movement that created a spirit of oneness among the Marathas","Bhakti movement","மராத்தியர்களில் ஒற்றுமை உணர்வை உருவாக்கிய இயக்கம்","பக்தி இயக்கம்"),
(225,"saint","Leading Bhakti saint associated with Maratha unity","Tukaram","மராத்திய ஒற்றுமையுடன் தொடர்புடைய பக்திச் சான்றோர்","துக்காராம்"),
(225,"saint","Leading Bhakti saint associated with Maratha unity","Ramdas","மராத்திய ஒற்றுமையுடன் தொடர்புடைய பக்திச் சான்றோர்","ராமதாஸ்"),
(225,"saint","Leading Bhakti saint associated with Maratha unity","Eknath","மராத்திய ஒற்றுமையுடன் தொடர்புடைய பக்திச் சான்றோர்","ஏகநாதர்"),
(225,"language","Language in which Bhakti hymns were sung among the Marathas","Marathi","மராத்தியர்களிடையே பக்திப் பாடல்கள் பாடப்பட்ட மொழி","மராத்தி"),
(226,"cause","External political decline that encouraged Maratha unity","Degeneration of Bijapur and Golkonda","மராத்தியர்களை ஒன்றுபடத் தூண்டிய வெளிப்புற அரசியல் காரணம்","பிஜாப்பூர் மற்றும் கோல்கொண்டாவின் சிதைவு"),
(226,"effect","Effect of Deccan wars on the Mughal treasury","Exhausted it","தக்காணப் போர்கள் முகலாய கருவூலத்தில் ஏற்படுத்திய விளைவு","அதை களைத்துவிட்டது"),
(226,"capital","Capital of Shivaji's kingdom named in the chapter","Raigarh (Raigad)","சிவாஜியின் அரசின் தலைநகரம்","ராய்கர் (ராய்கட்)"),

# Shivaji origins and rise
(226,"period","Life span of Shivaji","1627–1680","சிவாஜியின் வாழ்நாள்","1627–1680"),
(226,"place","Birthplace of Shivaji","Shivner near Junnar","சிவாஜி பிறந்த இடம்","ஜுன்னார் அருகிலுள்ள சிவ்னேர்"),
(226,"person","Father of Shivaji","Shahji Bhonsle","சிவாஜியின் தந்தை","ஷாஜி போன்ஸ்லே"),
(226,"person","Mother of Shivaji","Jijabai","சிவாஜியின் தாய்","ஜீஜாபாய்"),
(226,"dynasty","Lineage claimed for Shahji from his mother's side","Yadava rulers of Devagiri","ஷாஜியின் தாய் வழி வம்சத் தொடர்பு","தேவகிரியின் யாதவ அரசர்கள்"),
(226,"dynasty","Lineage claimed for Shahji from his father's side","Sisodias of Mewar","ஷாஜியின் தந்தை வழி வம்சத் தொடர்பு","மேவாரின் சிசோடியர்கள்"),
(226,"person","Ahmednagar statesman under whom Shahji served","Malik Ambar","ஷாஜி சேவை செய்த அகமதுநகர் அரசியல்வாதி","மாலிக் அம்பர்"),
(226,"period","Life span of Malik Ambar given here","1548–1626","இங்கு கொடுக்கப்பட்ட மாலிக் அம்பரின் வாழ்நாள்","1548–1626"),
(226,"origin","Ethnic/geographical background of Malik Ambar described in the chapter","Abyssinian","மாலிக் அம்பரின் பின்னணி","அபிசீனியர்"),
(226,"state","State whose service Shahji entered after Mughal annexation of Ahmadnagar","Bijapur","அகமதுநகர் முகலாயரால் இணைக்கப்பட்ட பின் ஷாஜி சேர்ந்த அரசு","பிஜாப்பூர்"),
(226,"person","Administrator who cared for Shivaji and Jijabai at Poona","Dadaji Kondadev","பூனாவில் சிவாஜி, ஜீஜாபாயை கவனித்த நிர்வாகி","தாதாஜி கொண்டதேவ்"),
(226,"place","Place where Dadaji Kondadev administered Shahji's jagirs","Poona","தாதாஜி கொண்டதேவ் ஷாஜியின் ஜாகீர்களை நிர்வகித்த இடம்","பூனா"),
(226,"group","Martial peasants and chiefs who supported Shivaji around Poona","Mavalis","பூனா சுற்றுப் பகுதிகளில் சிவாஜியை ஆதரித்த போர்திறன் மிக்க மக்கள்","மாவளிகள்"),
(226,"saint","Religious figure regarded by Shivaji as his guru","Ramdas","சிவாஜி தன் குருவாகக் கருதிய சமயத் தலைவர்","ராமதாஸ்"),
(226,"age","Age at which Shivaji began his military career","Nineteen","சிவாஜி இராணுவ வாழ்க்கையைத் தொடங்கிய வயது","பத்தொன்பது"),
(226,"date","Year Shivaji captured Torna","1646","சிவாஜி தோர்ணாவை கைப்பற்றிய ஆண்டு","1646"),
(226,"fort","First major fortress captured by Shivaji from Bijapur","Torna","பிஜாப்பூரிடமிருந்து சிவாஜி கைப்பற்றிய முதல் முக்கியக் கோட்டை","தோர்ணா"),
(226,"distance","Distance of Raigad east of Torna stated in the chapter","Five miles","தோர்ணாவிலிருந்து ராய்கட் கிழக்கே உள்ள தூரம்","ஐந்து மைல்கள்"),
(226,"date","Year of Dadaji Kondadev's death","1647","தாதாஜி கொண்டதேவ் இறந்த ஆண்டு","1647"),
(226,"fort","One fort brought under Shivaji's direct control after 1647","Baramati","1647க்கு பின் சிவாஜியின் நேரடி கட்டுப்பாட்டுக்குள் வந்த கோட்டை","பாராமதி"),
(226,"fort","One fort brought under Shivaji's direct control after 1647","Indapura","1647க்கு பின் சிவாஜியின் நேரடி கட்டுப்பாட்டுக்குள் வந்த கோட்டை","இந்தாபுரா"),
(226,"fort","One fort brought under Shivaji's direct control after 1647","Purandhar","1647க்கு பின் சிவாஜியின் நேரடி கட்டுப்பாட்டுக்குள் வந்த கோட்டை","புரந்தர்"),
(226,"fort","One fort brought under Shivaji's direct control after 1647","Kondana","1647க்கு பின் சிவாஜியின் நேரடி கட்டுப்பாட்டுக்குள் வந்த கோட்டை","கொண்டானா"),
(226,"town","Important town already captured by the Marathas","Kalyan","மராத்தியர்கள் ஏற்கனவே கைப்பற்றிய முக்கிய நகரம்","கல்யாண்"),
(226,"person","Mughal Viceroy of the Deccan with whom Shahji negotiated","Prince Murad","ஷாஜி பேச்சுவார்த்தை நடத்திய முகலாய தக்காண வைஸ்ராய்","இளவரசர் முராத்"),
(226,"date","Year Shahji was released by the Sultan of Bijapur","1649","பிஜாப்பூர் சுல்தான் ஷாஜியை விடுவித்த ஆண்டு","1649"),
(226,"period","Years during which Shivaji refrained from military activity","1649–1655","சிவாஜி இராணுவ நடவடிக்கைகளிலிருந்து விலகியிருந்த காலம்","1649–1655"),
(226,"date","Year Shivaji restarted his military activity","1656","சிவாஜி மீண்டும் இராணுவ நடவடிக்கைகளைத் தொடங்கிய ஆண்டு","1656"),
(226,"place","Satara district territory captured by Shivaji in 1656","Javli","1656இல் சிவாஜி கைப்பற்றிய சதாரா மாவட்டப் பகுதி","ஜாவளி"),
(226,"fort","New fort built west of Javli","Pratapgarh","ஜாவளியின் மேற்கே கட்டப்பட்ட புதிய கோட்டை","பிரதாப்கர்"),
(226,"distance","Distance of Pratapgarh west of Javli","Two miles","ஜாவளியிலிருந்து பிரதாப்கர் மேற்கே உள்ள தூரம்","இரண்டு மைல்கள்"),
(226,"person","Bijapur ruler whose death in November 1656 changed the political situation","Mohammad Adilshah","நவம்பர் 1656இல் இறந்த பிஜாப்பூர் அரசர்","முகமது ஆதில் ஷா"),
(226,"person","Young successor to Mohammad Adilshah","Adilshah II","முகமது ஆதில் ஷாவுக்கு பின் வந்த இளம் வாரிசு","இரண்டாம் ஆதில் ஷா"),
(226,"age","Age of Adilshah II at succession","Eighteen","ஆட்சியேற்றபோது இரண்டாம் ஆதில் ஷாவின் வயது","பதினெட்டு"),
(226,"place","One Deccan fort captured by Aurangzeb in 1657","Bidar","1657இல் ஔரங்கசீப் கைப்பற்றிய தக்காணக் கோட்டை","பீதார்"),
(226,"place","One Deccan fort captured by Aurangzeb in 1657","Kalyani","1657இல் ஔரங்கசீப் கைப்பற்றிய தக்காணக் கோட்டை","கல்யாணி"),
(226,"place","One Deccan fort captured by Aurangzeb in 1657","Purandar","1657இல் ஔரங்கசீப் கைப்பற்றிய தக்காணக் கோட்டை","புரந்தர்"),
(226,"region","Region invaded by Shivaji when Aurangzeb left for Delhi","North Konkan","ஔரங்கசீப் டெல்லி சென்றபோது சிவாஜி படையெடுத்த பகுதி","வட கொங்கண்"),
(226,"town","Town captured by Shivaji in North Konkan","Bhivandi","வட கொங்கணில் சிவாஜி கைப்பற்றிய நகரம்","பிவண்டி"),
(226,"fort","Fort captured by Shivaji during North Konkan campaign","Mahuli","வட கொங்கண் படையெடுப்பில் சிவாஜி கைப்பற்றிய கோட்டை","மஹுலி"),
(226,"person","Bijapur general sent against Shivaji in 1659","Afzal Khan","1659இல் சிவாஜிக்கு எதிராக அனுப்பப்பட்ட பிஜாப்பூர் தளபதி","அப்சல் கான்"),
(226,"nickname","Derisive term used by Afzal Khan for Shivaji","Mountain-rat","சிவாஜியை இழிவாக அழைக்க அப்சல் கான் பயன்படுத்திய சொல்","மலை எலி"),
(227,"region","Region ravaged by Marathas after outwitting Afzal Khan","South Konkan","அப்சல் கானை முறியடித்த பின் மராத்தியர்கள் சூறையாடிய பகுதி","தென் கொங்கண்"),
(227,"district","District ravaged by Maratha forces after Afzal Khan episode","Kolhapur","அப்சல் கான் சம்பவத்திற்குப் பின் மராத்தியர்கள் சூறையாடிய மாவட்டம்","கோலாப்பூர்"),
(227,"fort","Fort captured by Marathas after Afzal Khan episode","Panhala","அப்சல் கான் சம்பவத்திற்குப் பின் மராத்தியர்கள் கைப்பற்றிய கோட்டை","பன்ஹாலா"),
(227,"result","Political result of prolonged Bijapur-Shivaji conflict","Shivaji was recognised as ruler of territories in his possession","நீண்ட பிஜாப்பூர்-சிவாஜி மோதலின் அரசியல் முடிவு","சிவாஜி தன் கட்டுப்பாட்டிலிருந்த பகுதிகளின் ஆட்சியாளராக அங்கீகரிக்கப்பட்டார்"),
(227,"date","Month and year Aurangzeb ascended the Mughal throne","July 1658","ஔரங்கசீப் முகலாய அரியணை ஏறிய மாதம் மற்றும் ஆண்டு","ஜூலை 1658"),
(227,"person","Mughal governor appointed in the Deccan in 1660 to crush Shivaji","Shaista Khan","1660இல் சிவாஜியை ஒடுக்க நியமிக்கப்பட்ட முகலாய தக்காண ஆளுநர்","ஷாயிஸ்தா கான்"),
(227,"number","Number of soldiers Shivaji used in the night raid on Poona","400","பூனா இரவுத் தாக்குதலில் சிவாஜி பயன்படுத்திய வீரர்கள் எண்ணிக்கை","400"),
(227,"disguise","Disguise used by Shivaji's soldiers to enter Poona","Marriage party","பூனாவில் நுழைய சிவாஜி வீரர்கள் எடுத்த வேடம்","திருமணக் குழு"),
(227,"date","Month and year Shaista Khan was recalled from the Deccan","December 1663","ஷாயிஸ்தா கான் தக்காணத்திலிருந்து திரும்ப அழைக்கப்பட்ட மாதம் மற்றும் ஆண்டு","டிசம்பர் 1663"),
(227,"date","Year Shivaji first attacked Surat","1664","சிவாஜி முதன்முதலில் சூரத்தைத் தாக்கிய ஆண்டு","1664"),
(227,"place","Major Mughal port on the Arabian Sea attacked by Shivaji","Surat","சிவாஜி தாக்கிய அரபிக்கடலின் முக்கிய முகலாய துறைமுகம்","சூரத்"),
(227,"person","Rajput general sent by Aurangzeb against Shivaji","Raja Jai Singh","சிவாஜிக்கு எதிராக ஔரங்கசீப் அனுப்பிய ராஜபுத்திர தளபதி","ராஜா ஜெய்சிங்"),
(227,"person","Deccan governor at the time of Jai Singh's campaign against Shivaji","Prince Muazzam","ஜெய்சிங் சிவாஜிக்கு எதிராகப் போரிட்டபோது தக்காண ஆளுநர்","இளவரசர் முஅஸ்ஸம்"),
(227,"alternate_name","Later imperial name of Prince Muazzam","Bahadur Shah I","இளவரசர் முஅஸ்ஸத்தின் பிற்கால பேரரசுப் பெயர்","முதலாம் பகதூர் ஷா"),
(227,"date","Month and year Purandar was besieged","June 1665","புரந்தர் முற்றுகையிடப்பட்ட மாதம் மற்றும் ஆண்டு","ஜூன் 1665"),
(227,"treaty","Treaty signed between Shivaji and Jai Singh","Treaty of Purandar","சிவாஜி மற்றும் ஜெய்சிங் இடையிலான ஒப்பந்தம்","புரந்தர் ஒப்பந்தம்"),
(227,"date","Exact date of the Treaty of Purandar","11 June 1665","புரந்தர் ஒப்பந்தத்தின் துல்லிய தேதி","11 ஜூன் 1665"),
(227,"term","Mughal rank Shivaji agreed to serve as under the Treaty of Purandar","Mansabdar","புரந்தர் ஒப்பந்தத்தின்படி சிவாஜி ஏற்க ஒப்புக்கொண்ட முகலாயப் பதவி","மன்சப்தார்"),
(227,"goal","Military assistance Shivaji agreed to give the Mughals","Help conquer Bijapur","முகலாயருக்கு சிவாஜி வழங்க ஒப்புக்கொண்ட இராணுவ உதவி","பிஜாப்பூரை வெல்ல உதவுதல்"),
(227,"date","Month and year Shivaji and Sambhaji reached Agra","May 1666","சிவாஜி, சம்பாஜி ஆக்ரா சென்ற மாதம் மற்றும் ஆண்டு","மே 1666"),
(227,"escape","Method by which Shivaji escaped Mughal confinement in Agra","Hiding in a fruit basket","ஆக்ரா சிறைப்பிடிப்பிலிருந்து சிவாஜி தப்பிய முறை","பழக்கூடையில் மறைந்து"),
(227,"date","Year Shivaji resumed belligerent policy after Agra","1666","ஆக்ராவிற்குப் பின் சிவாஜி மீண்டும் தீவிரப் போர் கொள்கையைத் தொடங்கிய ஆண்டு","1666"),
(227,"rank","Mansab granted to Sambhaji","5000","சம்பாஜிக்கு வழங்கப்பட்ட மன்சப் எண்ணிக்கை","5000"),
(227,"date","Year Shivaji renewed major conflict with the Mughals","1670","சிவாஜி முகலாயருடன் மீண்டும் பெரிய மோதலைத் தொடங்கிய ஆண்டு","1670"),
(227,"region","Jagir region whose partial resumption angered Shivaji","Berar","ஒரு பகுதி ஜாகீர் மீளப்பெறப்பட்டதால் சிவாஜி கோபமடைந்த பகுதி","பெரார்"),
(227,"date","Year Shivaji sacked Surat for the second time","1670","சிவாஜி சூரத்தை இரண்டாவது முறையாக சூறையாடிய ஆண்டு","1670"),
(227,"tax","Annual tribute imposed on Surat by the Marathas in 1672","Chauth","1672இல் சூரத்தில் மராத்தியர்கள் விதித்த ஆண்டு கப்பம்","சௌத்"),
(227,"fraction","Meaning of Chauth as a share","One fourth of revenue","சௌத் என்ற வரியின் பங்கு","வருவாயின் நான்கில் ஒரு பங்கு"),
(228,"date","Exact coronation date of Shivaji","6 June 1674","சிவாஜியின் முடிசூட்டு விழாவின் துல்லிய தேதி","6 ஜூன் 1674"),
(228,"place","Place of Shivaji's coronation","Raigarh","சிவாஜியின் முடிசூட்டு நடந்த இடம்","ராய்கர்"),
(228,"title","Title assumed by Shivaji at coronation","Chhatrapathi","முடிசூட்டில் சிவாஜி ஏற்ற பட்டம்","சத்திரபதி"),
(228,"meaning","Meaning of Chhatrapathi in the chapter","Supreme king","பாடநூலில் சத்திரபதி என்ற சொல்லின் பொருள்","உயரிய மன்னன்"),
(228,"date","Year Shivaji began southern conquests","1676","சிவாஜி தெற்குப் படையெடுப்புகளைத் தொடங்கிய ஆண்டு","1676"),
(228,"state","State with whose Sultan Shivaji signed a secret treaty","Golkonda","சிவாஜி ரகசிய ஒப்பந்தம் செய்த சுல்தானியம்","கோல்கொண்டா"),
(228,"place","One major southern fort captured by Shivaji","Senji","சிவாஜி கைப்பற்றிய முக்கிய தென்னகக் கோட்டை","செஞ்சி"),
(228,"place","Another major southern fort captured by Shivaji","Vellore","சிவாஜி கைப்பற்றிய மற்றொரு முக்கிய தென்னகக் கோட்டை","வேலூர்"),
(228,"person","Half-brother whom Shivaji allowed to continue administering Thanjavur","Venkoji (Ekoji)","தஞ்சாவூரை தொடர்ந்து நிர்வகிக்க சிவாஜி அனுமதித்த ஒன்றுவிட்ட சகோதரர்","வெங்கோஜி (ஏகோஜி)"),
(228,"state","Nayak kingdom that promised a large tribute to Shivaji","Madurai","சிவாஜிக்கு பெரிய கப்பம் வழங்க ஒப்புக்கொண்ட நாயக்க அரசு","மதுரை"),
(228,"role","Defensive role of Senji for Shivaji's successors","Second line of defence","சிவாஜியின் வாரிசுகளுக்கு செஞ்சியின் பாதுகாப்புப் பங்கு","இரண்டாம் பாதுகாப்புக் கோடு"),
(228,"person","Eldest son of Shivaji","Sambhaji","சிவாஜியின் மூத்த மகன்","சம்பாஜி"),
(228,"date","Year of Shivaji's death","1680","சிவாஜி இறந்த ஆண்டு","1680"),
(228,"age","Age of Shivaji at death","53","சிவாஜி இறந்த வயது","53"),
(228,"extent","Northern-western extent of Shivaji's kingdom at his death","Western Ghats and Konkan between Kalyan and Goa","சிவாஜி இறந்தபோது அவரது அரசின் வடமேற்கு பரப்பு","கல்யாண் முதல் கோவா வரையிலான மேற்கு தொடர்ச்சி மலை மற்றும் கொங்கண்"),
(228,"extent","Southern Karnataka extent of Shivaji's kingdom","Belgaum to the bank of Tungabhadra","சிவாஜியின் தெற்கு கர்நாடகப் பரப்பு","பெல்காம் முதல் துங்கபத்ரா கரை வரை"),

# After Shivaji
(229,"person","Successor of Shivaji","Sambhaji","சிவாஜியின் வாரிசு","சம்பாஜி"),
(229,"date","Year Sambhaji invaded Mughal territory after Shivaji's death","1681","சிவாஜி இறந்த ஒரு ஆண்டு பின் சம்பாஜி முகலாயப் பகுதியைத் தாக்கிய ஆண்டு","1681"),
(229,"place","Berar town captured by Sambhaji","Bahadurpur","சம்பாஜி கைப்பற்றிய பெரார் நகரம்","பகதூர்பூர்"),
(229,"date","Year Bijapur was annexed by Aurangzeb","1686","ஔரங்கசீப் பிஜாப்பூரை இணைத்த ஆண்டு","1686"),
(229,"date","Year Golkonda was annexed by Aurangzeb","1687","ஔரங்கசீப் கோல்கொண்டாவை இணைத்த ஆண்டு","1687"),
(229,"person","Aurangzeb's rebellious son protected by Sambhaji","Prince Akbar II","சம்பாஜி பாதுகாப்பு அளித்த ஔரங்கசீப்பின் கிளர்ச்சியாளர் மகன்","இளவரசர் அக்பர் II"),
(229,"date","Year Sambhaji was captured and killed by Mughal forces","1689","சம்பாஜி முகலாயரால் பிடிக்கப்பட்டு கொல்லப்பட்ட ஆண்டு","1689"),
(229,"person","Younger brother of Sambhaji who continued resistance","Rajaram","சம்பாஜிக்கு பின் எதிர்ப்பைத் தொடர்ந்த இளைய சகோதரர்","ராஜாராம்"),
(229,"place","Tamil fort from which Rajaram renewed the Maratha struggle","Senji","ராஜாராம் மராத்தியப் போராட்டத்தைத் தொடர்ந்து நடத்திய தமிழ்நாட்டு கோட்டை","செஞ்சி"),
(229,"date","Year of Rajaram's death","1700","ராஜாராம் இறந்த ஆண்டு","1700"),
(229,"person","Widow of Rajaram who continued Maratha resistance","Tara Bai","ராஜாராம் இறந்த பின் மராத்திய எதிர்ப்பைத் தொடர்ந்த விதவை","தாராபாய்"),
(229,"number","Size of the army Tara Bai sent toward Hyderabad","50,000 horsemen and infantry","ஹைதராபாத் நோக்கி தாராபாய் அனுப்பிய படையின் அளவு","50,000 குதிரைப்படை மற்றும் காலாட்படை"),
(229,"port","Major port whose trade was disrupted after Maratha attack on Hyderabad region","Masulipatnam","ஹைதராபாத் தாக்குதலுக்குப் பின் வணிகம் பாதிக்கப்பட்ட முக்கிய துறைமுகம்","மசூலிப்பட்டினம்"),
(229,"date","Year Aurangzeb died while Marathas still held many forts","1707","மராத்தியர்கள் பல கோட்டைகளை வைத்திருந்தபோது ஔரங்கசீப் இறந்த ஆண்டு","1707"),
(229,"person","Son of Sambhaji released after Aurangzeb's death","Shahu","ஔரங்கசீப் இறப்பிற்குப் பின் விடுவிக்கப்பட்ட சம்பாஜியின் மகன்","சாஹு"),
(229,"date","Year Shahu ascended the Maratha throne","1708","சாஹு மராத்திய அரியணை ஏறிய ஆண்டு","1708"),
(229,"person","Statesman who strongly supported Shahu's accession","Balaji Viswanath","சாஹுவின் ஆட்சியேற்றத்தை வலுவாக ஆதரித்தவர்","பாலாஜி விஸ்வநாத்"),
(229,"date","Year Balaji Viswanath was appointed Peshwa","1713","பாலாஜி விஸ்வநாத் பேஷ்வாவாக நியமிக்கப்பட்ட ஆண்டு","1713"),
(229,"place","Place to which Shahu retired","Satara","சாஹு ஓய்வு பெற்ற இடம்","சதாரா"),
(229,"place","City from which the Peshwa began to rule","Poona","பேஷ்வா ஆட்சி செய்யத் தொடங்கிய நகரம்","பூனா"),
(229,"capital","Capital of Tara Bai's rival government","Kolhapur","தாராபாயின் போட்டி அரசின் தலைநகரம்","கோலாப்பூர்"),
(229,"person","Second wife of Rajaram who imprisoned Tara Bai","Raja Bai","தாராபாயை சிறையில் அடைத்த ராஜாராமின் இரண்டாம் மனைவி","ராஜாபாய்"),
(229,"person","Son of Raja Bai who became ruler of Kolhapur","Sambhaji II","கோலாப்பூர் அரசனான ராஜாபாயின் மகன்","இரண்டாம் சம்பாஜி"),
(229,"date","Year Tara Bai and her son were imprisoned","1714","தாராபாய் மற்றும் அவரது மகன் சிறைபிடிக்கப்பட்ட ஆண்டு","1714"),
(229,"date","Year of Shahu's death","1749","சாஹு இறந்த ஆண்டு","1749"),
(229,"person","Ruler who ascended after Shahu and became a titular head","Rama Raja","சாஹுவுக்குப் பின் ஆட்சிக்கு வந்து பெயரளவு தலைவரானவர்","ராம ராஜா"),
(229,"date","Year Tara Bai died","1761","தாராபாய் இறந்த ஆண்டு","1761"),
(229,"date","Year Rama Raja died","1777","ராம ராஜா இறந்த ஆண்டு","1777"),
(229,"person","Adopted son of Rama Raja who ruled as a nonentity","Shahu II","ராம ராஜாவின் தத்துப்புத்திரராக பெயரளவில் ஆட்சி செய்தவர்","இரண்டாம் சாஹு"),
(229,"date","Year Shahu II died","1808","இரண்டாம் சாஹு இறந்த ஆண்டு","1808"),
(229,"person","Son of Shahu II deposed by the British in 1839","Pratap Singh","1839இல் ஆங்கிலேயரால் பதவி நீக்கப்பட்ட இரண்டாம் சாஹுவின் மகன்","பிரதாப் சிங்"),
(229,"date","Year Pratap Singh was deposed","1839","பிரதாப் சிங் பதவி நீக்கப்பட்ட ஆண்டு","1839"),
(229,"date","Year Pratap Singh died as a prisoner","1847","பிரதாப் சிங் கைதியாக இறந்த ஆண்டு","1847"),
(229,"person","Younger brother of Pratap Singh installed by the British","Shaji Appa Saheb (Shaji II)","ஆங்கிலேயரால் ஆட்சிக்கு கொண்டுவரப்பட்ட பிரதாப் சிங்கின் தம்பி","ஷாஜி அப்பா சாஹேப் (இரண்டாம் ஷாஜி)"),
(229,"date","Year Shaji II died without a successor","1848","இரண்டாம் ஷாஜி வாரிசின்றி இறந்த ஆண்டு","1848"),

# Shivaji administration
(229,"council","Council of eight ministers under Shivaji","Ashta Pradhan","சிவாஜியின் எட்டு அமைச்சர்கள் கொண்ட சபை","அஷ்ட பிரதான்"),
(229,"role","Nature of the Ashta Pradhan's functions","Advisory","அஷ்ட பிரதானின் பணியின் தன்மை","ஆலோசனை"),
(229,"office","Prime minister under Shivaji","Mukhya Pradhan or Peshwa","சிவாஜியின் பிரதம அமைச்சர் பதவி","முக்கிய பிரதான் அல்லது பேஷ்வா"),
(229,"function","Main duty of the Peshwa under Shivaji","General welfare and interests of the State","சிவாஜி கால பேஷ்வாவின் முக்கிய கடமை","அரசின் பொதுநலனும் நலவாழ்வும்"),
(229,"office","Finance minister under Shivaji","Amatya","சிவாஜியின் நிதி அமைச்சர்","அமாத்யா"),
(229,"function","Duty of the Amatya","Checked and countersigned public accounts","அமாத்யாவின் கடமை","அரசுக் கணக்குகளைச் சரிபார்த்து எதிர் கையொப்பமிடுதல்"),
(229,"office","Minister maintaining records of the king's activities and court proceedings","Walkia-Nawis or Mantri","அரசரின் செயல்கள் மற்றும் நீதிமன்ற நிகழ்வுகளை பதிவு செய்த அமைச்சர்","வாக்கியா-நவீஸ் அல்லது மந்திரி"),
(229,"office","Foreign secretary under Shivaji","Summant or Dabir","சிவாஜியின் வெளிநாட்டு செயலாளர்","சுமந்த் அல்லது தபீர்"),
(229,"function","Duty of Summant/Dabir","Advise on war and peace and receive envoys","சுமந்த்/தபீரின் கடமை","போர், அமைதி குறித்து ஆலோசித்து தூதர்களை ஏற்றுக்கொள்வது"),
(229,"office","Home secretary under Shivaji","Sachiv or Shuru Nawis","சிவாஜியின் உள்துறை செயலாளர்","சச்சிவ் அல்லது ஷுரு நவீஸ்"),
(229,"function","Duty of Sachiv","Look after royal correspondence and revise drafts","சச்சிவின் கடமை","அரசரின் கடிதப் பரிவர்த்தனையை கவனித்து வரைவு திருத்துதல்"),
(230,"office","Ecclesiastical head under Shivaji","Pandit Rao or Danadhyaksha","சிவாஜியின் சமயத் தலைவர்","பண்டித் ராவ் அல்லது தானாத்யக்ஷா"),
(230,"function","Duty of Pandit Rao","Religion, ceremonies and charities","பண்டித் ராவின் கடமை","சமயம், சடங்குகள் மற்றும் தானங்கள்"),
(230,"office","Chief justice under Shivaji","Nyayadhish","சிவாஜியின் தலைமை நீதிபதி","நியாயாதீஷ்"),
(230,"office","Commander-in-chief under Shivaji","Sari Naubat","சிவாஜியின் தலைமைத் தளபதி","சாரி நவ்பத்"),
(230,"number","Number of departments under Shivaji's ministers","Eighteen","சிவாஜியின் அமைச்சர்களின் கீழ் இருந்த துறைகள் எண்ணிக்கை","பதினெட்டு"),
(230,"number","Number of provinces into which Shivaji divided his kingdom","Four","சிவாஜி தனது அரசை பிரித்த மாகாணங்கள் எண்ணிக்கை","நான்கு"),
(230,"term","Administrative subdivisions of Shivaji's provinces","Pranths","சிவாஜி மாகாணங்களின் நிர்வாகப் பிரிவுகள்","பிராந்துகள்"),
(230,"policy","Shivaji's policy toward jagir grants","Abandoned the practice","ஜாகீர் வழங்கல் குறித்து சிவாஜியின் கொள்கை","அந்த முறையை கைவிட்டார்"),
(230,"payment","How Shivaji paid government officers","In cash","சிவாஜி அரச அதிகாரிகளுக்கு ஊதியம் வழங்கிய முறை","பணமாக"),
(230,"policy","Hereditary status of offices under Shivaji","No office was to be hereditary","சிவாஜி கால பதவிகளின் மரபுரிமை நிலை","எந்தப் பதவியும் மரபுரிமை அல்ல"),
(230,"centre","Nerve-centre of activities in a Pranth","Fort","ஒரு பிராந்தின் செயல்பாட்டு மையம்","கோட்டை"),
(230,"unit","Lowest unit of Shivaji's administration","Village","சிவாஜி நிர்வாகத்தின் அடிப்படை அலகு","கிராமம்"),
(230,"character","Character of Shivaji's revenue administration","Humane and beneficent to cultivators","சிவாஜியின் வருவாய் நிர்வாகத்தின் தன்மை","விவசாயிகளுக்கு மனிதநேயமும் நன்மையும் உடையது"),
(230,"method","Basis of Shivaji's land revenue assessment","Careful survey and assessment","சிவாஜியின் நிலவரி மதிப்பீட்டின் அடிப்படை","கவனமான நில அளவீடு மற்றும் மதிப்பீடு"),
(230,"rate","Initial state demand under Shivaji","30% of gross produce","சிவாஜி காலத்தின் தொடக்க அரசுப் பங்கு","மொத்த விளைச்சலின் 30%"),
(230,"rate","Later state demand under Shivaji","40% of gross produce","பின்னர் சிவாஜி காலத்தில் வசூலிக்கப்பட்ட அரசுப் பங்கு","மொத்த விளைச்சலின் 40%"),
(230,"relief","Famine relief under Shivaji","Loans of money and grain repayable in instalments","சிவாஜி கால பஞ்ச நிவாரணம்","தவணைகளில் திருப்பிச் செலுத்தும் பணம் மற்றும் தானியக் கடன்"),
(230,"relief","Another form of agricultural assistance under Shivaji","Loans for cattle and seed","சிவாஜி கால விவசாய உதவியின் மற்றொரு வடிவம்","மாடுகள் மற்றும் விதைகள் வாங்கக் கடன்"),
(230,"tax","Tax amounting to one-fourth of revenue","Chauth","வருவாயின் நான்கில் ஒரு பங்கான வரி","சௌத்"),
(230,"tax","Additional 10% levy claimed by Shivaji","Sardeshmukhi","சிவாஜி வசூலித்த கூடுதல் 10% வரி","சர்தேஷ்முகி"),
(230,"rate","Rate of Sardeshmukhi","10%","சர்தேஷ்முகி வரி விகிதம்","10%"),
(230,"title","Superior head over many Desais or Deshmukhs","Sardeshmukh","பல தேசாய்/தேச்முக்களின் மேல்நிலைத் தலைவர்","சர்தேஷ்முக்"),
(230,"army","Type of army organized by Shivaji","Standing army","சிவாஜி அமைத்த படையின் வகை","நிலையான படை"),
(230,"policy","Shivaji's approach to hereditary military appointments","Discouraged them","மரபுரிமை இராணுவ நியமனங்கள் குறித்து சிவாஜியின் நிலை","ஊக்கமளிக்கவில்லை"),
(230,"army","One division of Shivaji's army","Infantry","சிவாஜியின் படையின் ஒரு பிரிவு","காலாட்படை"),
(230,"army","One division of Shivaji's army","Cavalry","சிவாஜியின் படையின் ஒரு பிரிவு","குதிரைப்படை"),
(230,"army","One division of Shivaji's army","Elephant corps","சிவாஜியின் படையின் ஒரு பிரிவு","யானைப்படை"),
(230,"army","One division of Shivaji's army","Artillery","சிவாஜியின் படையின் ஒரு பிரிவு","பீரங்கிப்படை"),
(230,"number","Number of soldiers in the smallest infantry unit","Nine","சிறிய காலாட்படை அலகில் வீரர்கள் எண்ணிக்கை","ஒன்பது"),
(230,"office","Head of the smallest infantry unit","Naik","சிறிய காலாட்படை அலகின் தலைவர்","நாயக்"),
(230,"number","Horsemen under one havildar","25","ஒரு ஹவில்தாரின் கீழ் இருந்த குதிரைவீரர்கள்","25"),
(230,"office","Officer over a unit of 25 horsemen","Havildar","25 குதிரைவீரர்கள் கொண்ட அலகின் அதிகாரி","ஹவில்தார்"),
(230,"number","Havildars under one jamaladar","Five","ஒரு ஜமால்தாரின் கீழ் இருந்த ஹவில்தார்கள்","ஐந்து"),
(230,"number","Jamaladars under one hazari","Ten","ஒரு ஹசாரியின் கீழ் இருந்த ஜமால்தார்கள்","பத்து"),
(230,"office","Supreme commander of cavalry","Sari Naubat","குதிரைப்படையின் உயர்ந்த தளபதி","சாரி நவ்பத்"),
(230,"class","Cavalry soldiers whose horses were supplied by the state","Bargirs","அரசால் குதிரைகள் வழங்கப்பட்ட குதிரைப்படை வீரர்கள்","பார்கிர்கள்"),
(230,"class","Mercenary horsemen who supplied their own horses","Shiledars","தங்கள் சொந்தக் குதிரைகளை வைத்திருந்த கூலி குதிரைவீரர்கள்","ஷிலேதார்கள்"),
(230,"justice","Nature of Shivaji's justice administration","Rudimentary","சிவாஜியின் நீதி நிர்வாகத்தின் தன்மை","ஆரம்பநிலை"),
(230,"institution","Village body functioning in justice under Shivaji","Panchayat","சிவாஜி கால கிராம நீதியில் செயல்பட்ட அமைப்பு","பஞ்சாயத்து"),
(230,"office","Village officer trying criminal cases","Patel","குற்றவியல் வழக்குகளை விசாரித்த கிராம அதிகாரி","படேல்"),
(230,"office","Chief justice hearing appeals under Shivaji","Nyayadhish","மேல்முறையீடுகளை விசாரித்த தலைமை நீதிபதி","நியாயாதீஷ்"),
(230,"court","Final court of appeal under Shivaji","Hazir Majlim","சிவாஜி கால இறுதி மேல்முறையீட்டு நீதிமன்றம்","ஹசிர் மஜ்லிம்"),

# Peshwas and expansion
(231,"period","Period of Peshwa rule","1713–1818","பேஷ்வா ஆட்சிக்காலம்","1713–1818"),
(231,"meaning","Meaning of the Persian word Peshwa","Foremost or First Minister","பாரசீகச் சொல் பேஷ்வாவின் பொருள்","முதன்மை அல்லது முதல் அமைச்சர்"),
(231,"person","First powerful Peshwa","Balaji Viswanath","முதல் சக்திவாய்ந்த பேஷ்வா","பாலாஜி விஸ்வநாத்"),
(231,"period","Tenure of Balaji Viswanath as Peshwa","1713–1720","பாலாஜி விஸ்வநாதின் பேஷ்வா காலம்","1713–1720"),
(231,"person","Powerful naval chief on the western coast during Balaji Viswanath's time","Kanhoji Angre","பாலாஜி விஸ்வநாத் கால மேற்கு கடற்கரை வலுவான கடற்படைத் தலைவர்","கன்ஹோஜி ஆங்க்ரே"),
(231,"support","Side supported by Kanhoji Angre during the civil war","Tara Bai","உள்நாட்டுப் போரில் கன்ஹோஜி ஆங்க்ரே ஆதரித்தவர்","தாராபாய்"),
(231,"policy","Practice revived under Balaji Viswanath","Granting jagirs","பாலாஜி விஸ்வநாத் மீண்டும் அறிமுகப்படுத்திய நடைமுறை","ஜாகீர் வழங்குதல்"),
(231,"policy","Institutional change made to the Peshwa office under Balaji Viswanath","Made hereditary","பாலாஜி விஸ்வநாத் கால பேஷ்வா பதவியில் ஏற்பட்ட மாற்றம்","மரபுரிமை ஆக்கப்பட்டது"),
(231,"period","Tenure of Baji Rao I as Peshwa","1720–1740","முதலாம் பாஜிராவின் பேஷ்வா காலம்","1720–1740"),
(231,"relation","Relationship of Baji Rao I to Balaji Viswanath","Son","முதலாம் பாஜிராவுக்கும் பாலாஜி விஸ்வநாத்துக்கும் உள்ள உறவு","மகன்"),
(231,"person","Maratha emperor who appointed Baji Rao I as Peshwa","Shahu","முதலாம் பாஜிராவை பேஷ்வாவாக நியமித்த மராத்திய மன்னர்","சாஹு"),
(231,"enemy","Regional ruler defeated by Baji Rao I","Nizam of Hyderabad","முதலாம் பாஜிராவால் தோற்கடிக்கப்பட்ட பிராந்திய அரசர்","ஹைதராபாத் நிஜாம்"),
(231,"enemy","Rajput official defeated by Baji Rao I","Rajput Governor of Malwa","முதலாம் பாஜிராவால் தோற்கடிக்கப்பட்ட ராஜபுத்திர அதிகாரி","மாளவத்தின் ராஜபுத்திர ஆளுநர்"),
(231,"enemy","Official defeated by Baji Rao I","Governor of Gujarat","முதலாம் பாஜிராவால் தோற்கடிக்கப்பட்ட அதிகாரி","குஜராத் ஆளுநர்"),
(231,"region","Region freed by Baji Rao I from Mughal control","Bundelkhand","முதலாம் பாஜிரா முகலாயக் கட்டுப்பாட்டிலிருந்து விடுவித்த பகுதி","புந்தேல்கண்ட்"),
(231,"share","Territorial share gained by Marathas from Bundelkhand","One third","புந்தேல்கண்டிலிருந்து மராத்தியர்கள் பெற்ற பகுதி","மூன்றில் ஒரு பங்கு"),
(231,"person","Commander-in-chief defeated and killed by Baji Rao I at Dabhai","Trimbak Rao","தபாய் போரில் முதலாம் பாஜிராவால் தோற்கடிக்கப்பட்ட தலைமைத் தளபதி","திரிம்பக் ராவ்"),
(231,"battle","Battle near Baroda in which Trimbak Rao was killed","Battle of Dabhai","திரிம்பக் ராவ் கொல்லப்பட்ட பரோடா அருகிலான போர்","தபாய் போர்"),
(231,"date","Year of the Battle of Dabhai","1731","தபாய் போரின் ஆண்டு","1731"),
(231,"treaty","Treaty forcing Sambhaji of Kolhapur to accept Shahu's sovereignty","Treaty of Warna","கோலாப்பூர் சம்பாஜியை சாஹுவின் மேலாதிக்கத்தை ஏற்கச் செய்த ஒப்பந்தம்","வர்ணா ஒப்பந்தம்"),
(231,"date","Year of the Treaty of Warna","1731","வர்ணா ஒப்பந்தத்தின் ஆண்டு","1731"),
(231,"place","Portuguese possession captured by Marathas in 1738","Thana","1738இல் மராத்தியர்கள் போர்த்துக்கீசியரிடமிருந்து கைப்பற்றிய பகுதி","தானா"),
(231,"place","Portuguese possession captured by Marathas in 1738","Salsette","1738இல் மராத்தியர்கள் போர்த்துக்கீசியரிடமிருந்து கைப்பற்றிய பகுதி","சால்செட்"),
(231,"place","Portuguese possession captured by Marathas in 1738","Bassein","1738இல் மராத்தியர்கள் போர்த்துக்கீசியரிடமிருந்து கைப்பற்றிய பகுதி","பசேன்"),
(231,"right","Right secured by the English through friendly overtures to the Marathas","Free trade in the Deccan","மராத்தியர்களுடன் நட்புறவு மூலம் ஆங்கிலேயர் பெற்ற உரிமை","தக்காணத்தில் சுதந்திர வாணிபம்"),
(231,"period","Tenure of Balaji Baji Rao as Peshwa","1740–1761","பாலாஜி பாஜி ராவின் பேஷ்வா காலம்","1740–1761"),
(231,"alternate_name","Popular name of Balaji Baji Rao","Nana Sahib","பாலாஜி பாஜி ராவின் பிரபலப் பெயர்","நானா சாஹிப்"),
(231,"quality","Administrative strength of Balaji Baji Rao","Expert in financial matters","பாலாஜி பாஜி ராவின் நிர்வாகத் திறன்","நிதி விஷயங்களில் நிபுணர்"),
(231,"person","Arcot Nawab's son-in-law who threatened Thanjavur","Chanda Sahib","தஞ்சாவூரை அச்சுறுத்திய ஆர்க்காடு நவாபின் மருமகன்","சந்தா சாஹிப்"),
(231,"place","City captured by Chanda Sahib before threatening Thanjavur","Tiruchirappalli","தஞ்சாவூரை அச்சுறுத்துவதற்கு முன் சந்தா சாஹிப் கைப்பற்றிய நகரம்","திருச்சிராப்பள்ளி"),
(231,"date","Year Thanjavur appealed to Shahu for help","1739","தஞ்சாவூர் சாஹுவிடம் உதவி கேட்ட ஆண்டு","1739"),
(231,"person","Maratha commander sent by the Peshwa to Thanjavur","Raghoji Bhonsle","தஞ்சாவூருக்கு பேஷ்வா அனுப்பிய மராத்திய தளபதி","ரகோஜி போன்ஸ்லே"),
(231,"relation","Relationship of Raghoji Bhonsle to Shahu","Brother-in-law","ரகோஜி போன்ஸ்லே மற்றும் சாஹுவின் உறவு","மைத்துனர்"),
(231,"person","Nawab of Arcot defeated and killed by Raghoji Bhonsle","Dost Ali","ரகோஜி போன்ஸ்லே தோற்கடித்து கொன்ற ஆர்க்காடு நவாப்","தோஸ்த் அலி"),
(231,"date","Year Dost Ali was defeated and killed","1740","தோஸ்த் அலி தோற்கடித்து கொல்லப்பட்ட ஆண்டு","1740"),
(231,"result","Fate of Chanda Sahib after Maratha capture of Tiruchirappalli","Imprisoned","மராத்தியர்கள் திருச்சிராப்பள்ளியை கைப்பற்றிய பின் சந்தா சாஹிபின் நிலை","சிறைபிடிக்கப்பட்டார்"),
(231,"person","Successor of Dost Ali who retook Arcot and Tiruchirappalli","Mohammed Ali","ஆர்க்காடு, திருச்சிராப்பள்ளியை மீட்ட தோஸ்த் அலியின் வாரிசு","முகமது அலி"),
(231,"date","Year Mohammed Ali retook Arcot and Tiruchirappalli","1743","முகமது அலி ஆர்க்காடு, திருச்சிராப்பள்ளியை மீட்ட ஆண்டு","1743"),
(231,"person","Peshwa's cousin later sent to the Carnatic","Sadasiva Rao","பின்னர் கர்நாடகத்திற்கு அனுப்பப்பட்ட பேஷ்வாவின் உறவினர்","சதாசிவ ராவ்"),
(232,"battle","Battle marking the climax of Maratha military might","Battle of Udgir","மராத்திய இராணுவ வலிமையின் உச்சமாகக் கூறப்பட்ட போர்","உத்கீர் போர்"),
(232,"date","Year of the Battle of Udgir","1760","உத்கீர் போரின் ஆண்டு","1760"),
(232,"cause","Political event that triggered the Udgir conflict","War of succession after Nizam Asaf Jah's death","உத்கீர் மோதலுக்கான அரசியல் காரணம்","நிஜாம் ஆசப் ஜா இறப்புக்குப் பிந்தைய வாரிசுரிமைப் போர்"),
(232,"person","Maratha commander who won Udgir","Sadasiva Rao","உத்கீர் போரில் வென்ற மராத்திய தளபதி","சதாசிவ ராவ்"),
(232,"place","One territory taken over by the Peshwa after Udgir","Bijapur","உத்கீர் வெற்றிக்குப் பின் பேஷ்வா கைப்பற்றிய பகுதி","பிஜாப்பூர்"),
(232,"place","One territory taken over by the Peshwa after Udgir","Aurangabad","உத்கீர் வெற்றிக்குப் பின் பேஷ்வா கைப்பற்றிய பகுதி","அவுரங்காபாத்"),
(232,"place","One territory taken over by the Peshwa after Udgir","Daulatabad","உத்கீர் வெற்றிக்குப் பின் பேஷ்வா கைப்பற்றிய பகுதி","தௌலதாபாத்"),
(232,"place","One territory taken over by the Peshwa after Udgir","Ahmednagar","உத்கீர் வெற்றிக்குப் பின் பேஷ்வா கைப்பற்றிய பகுதி","அகமதுநகர்"),
(232,"place","One territory taken over by the Peshwa after Udgir","Burhanpur","உத்கீர் வெற்றிக்குப் பின் பேஷ்வா கைப்பற்றிய பகுதி","புர்ஹான்பூர்"),
(232,"period","Years of six Maratha expeditions that brought Rajputana under domination","1741–1748","ராஜபுத்தானாவை மராத்திய ஆதிக்கத்திற்கு கொண்டுவந்த ஆறு படையெடுப்புகளின் காலம்","1741–1748"),
(232,"date","Year Nawab of Bengal ceded Orissa to the Marathas","1751","வங்காள நவாப் ஒரிசாவை மராத்தியர்களுக்கு ஒப்படைத்த ஆண்டு","1751"),
(232,"date","Year Marathas entered Delhi to expel Afghans and Rohillas","1752","ஆப்கானியர், ரோஹில்லாக்களை விரட்ட மராத்தியர்கள் டெல்லி நுழைந்த ஆண்டு","1752"),
(232,"person","Wazir made with Maratha help and turned into their puppet","Imad-ul-Mulk","மராத்தியர் உதவியுடன் வசீராகி அவர்களது பொம்மையானவர்","இமாத்-உல்-முல்க்"),
(232,"person","Founder of the Durrani Empire in Afghanistan","Ahmad Shah Abdali","ஆப்கானிஸ்தானில் துர்ராணி பேரரசை நிறுவியவர்","அகமது ஷா அப்தாலி"),
(232,"battle","Battle in 1757 in which Marathas did not help Siraj-ud-Daulah","Battle of Plassey","1757இல் சிராஜ்-உத்-தௌலாவுக்கு மராத்தியர்கள் உதவாத போர்","பிளாசி போர்"),

# Panipat
(232,"battle","Decisive battle of 1761 between Marathas and Abdali","Third Battle of Panipat","1761இல் மராத்தியர்களுக்கும் அப்தாலிக்கும் இடையிலான தீர்மானப் போர்","மூன்றாம் பானிப்பட் போர்"),
(232,"date","Year of the Third Battle of Panipat","1761","மூன்றாம் பானிப்பட் போரின் ஆண்டு","1761"),
(232,"result","Long-term consequence attributed to Panipat","Paved the way for rise of British power","பானிப்பட் போருக்குக் கூறப்படும் நீண்டகால விளைவு","ஆங்கிலேய சக்தியின் எழுச்சிக்கு வழிவகுத்தது"),
(232,"person","Afghan ruler whose invasion was prompted by Mughal neglect of the north-west frontier","Nadir Shah","முகலாயர் வடமேற்கு எல்லையை புறக்கணித்ததால் இந்தியாவைத் தாக்கிய ஆப்கான் அரசர்","நாதிர் ஷா"),
(232,"person","Mughal ruler who gave asylum to Afghan rebels despite Nadir Shah's demands","Muhammad Shah","நாதிர் ஷாவின் கோரிக்கைகளை மீறி ஆப்கான் கிளர்ச்சியாளர்களுக்கு தஞ்சம் அளித்த முகலாயர்","முகமது ஷா"),
(232,"date","Year Nadir Shah's Indian invasion began","1739","நாதிர் ஷாவின் இந்திய படையெடுப்பு தொடங்கிய ஆண்டு","1739"),
(232,"place","City plundered by Nadir Shah","Delhi","நாதிர் ஷா சூறையாடிய நகரம்","டெல்லி"),
(232,"object","Famous diamond carried away by Nadir Shah","Kohinoor","நாதிர் ஷா எடுத்துச் சென்ற புகழ்பெற்ற வைரம்","கோஹினூர்"),
(232,"object","Famous royal throne carried away by Nadir Shah","Peacock Throne","நாதிர் ஷா எடுத்துச் சென்ற புகழ்பெற்ற அரச அரியணை","மயிலாசனம்"),
(232,"date","Year Nadir Shah was assassinated","1747","நாதிர் ஷா கொல்லப்பட்ட ஆண்டு","1747"),
(232,"person","Former general of Nadir Shah who became ruler of Afghanistan","Ahmad Shah Abdali","நாதிர் ஷாவின் முன்னாள் தளபதியாக இருந்து ஆப்கானிஸ்தான் அரசனானவர்","அகமது ஷா அப்தாலி"),
(232,"territory","One territory ceded by the Mughal emperor to Abdali","Multan","முகலாயப் பேரரசர் அப்தாலிக்கு ஒப்படைத்த பகுதி","முல்தான்"),
(232,"territory","Another territory ceded by the Mughal emperor to Abdali","Punjab","முகலாயப் பேரரசர் அப்தாலிக்கு ஒப்படைத்த பகுதி","பஞ்சாப்"),
(232,"person","Governor of Punjab appointed by the Mughal emperor but acting as Abdali's agent","Mir Mannu","முகலாயர் நியமித்தும் அப்தாலியின் முகவராக செயல்பட்ட பஞ்சாப் ஆளுநர்","மீர் மன்னு"),
(232,"person","Delhi Wazir who helped Mir Mannu's widow appoint Mir Munim","Imad-ul-Mulk","மீர் மன்னுவின் விதவைக்கு மீர் முனிம் நியமிக்க உதவிய டெல்லி வசீர்","இமாத்-உல்-முல்க்"),
(232,"person","Governor appointed in Punjab without Abdali's consent","Mir Munim","அப்தாலியின் அனுமதியின்றி பஞ்சாப் ஆளுநராக நியமிக்கப்பட்டவர்","மீர் முனிம்"),
(232,"date","Month and year Abdali captured and pillaged Delhi","January 1757","அப்தாலி டெல்லியை கைப்பற்றி சூறையாடிய மாதம் மற்றும் ஆண்டு","ஜனவரி 1757"),
(232,"place","Religious city desecrated by Abdali's forces","Mathura","அப்தாலியின் படையால் சேதப்படுத்தப்பட்ட புனித நகரம்","மதுரா"),
(232,"place","Another religious city desecrated by Abdali's forces","Brindavan","அப்தாலியின் படையால் சேதப்படுத்தப்பட்ட மற்றொரு புனித நகரம்","பிருந்தாவன்"),
(232,"office","Agent appointed by Abdali in Delhi before leaving","Mir Bakshi","டெல்லியில் அப்தாலி நியமித்த முகவர்","மீர் பக்ஷி"),
(232,"person","Son of Abdali made Viceroy of Lahore","Timur Shah","லாகூர் வைஸ்ராயாக நியமிக்கப்பட்ட அப்தாலியின் மகன்","திமூர் ஷா"),
(233,"person","Maratha leader who led an expedition toward Delhi after Abdali left","Malhar Rao Holkar","அப்தாலி சென்ற பின் டெல்லி நோக்கிப் படையெடுத்த மராத்திய தலைவர்","மல்ஹர் ராவ் ஹோல்கர்"),
(233,"person","Maratha leader who accompanied Malhar Rao Holkar in the northern expedition","Raghunatha Rao","வடக்கு படையெடுப்பில் மல்ஹர் ராவுடன் சென்றவர்","ரகுநாத ராவ்"),
(233,"place","City captured by the Marathas in 1758 after Sirhind","Lahore","1758இல் சிர்ஹிந்திற்குப் பின் மராத்தியர்கள் கைப்பற்றிய நகரம்","லாகூர்"),
(233,"place","Territory captured by Marathas before Lahore in 1758","Sirhind","1758இல் லாகூருக்கு முன் மராத்தியர்கள் கைப்பற்றிய பகுதி","சிர்ஹிந்த்"),
(233,"date","Month and year Abdali returned to India before Panipat","October 1759","பானிப்பட்டுக்கு முன் அப்தாலி இந்தியா திரும்பிய மாதம் மற்றும் ஆண்டு","அக்டோபர் 1759"),
(233,"person","Maratha commander sent to Punjab and killed by Abdali","Dattaji Scindia","பஞ்சாபுக்கு அனுப்பப்பட்டு அப்தாலியால் கொல்லப்பட்ட மராத்திய தளபதி","தத்தாஜி சிந்தியா"),
(233,"relation","Dattaji Scindia's relationship to Mahadji Scindia","Brother","தத்தாஜி சிந்தியா மற்றும் மகாத்ஜி சிந்தியாவின் உறவு","சகோதரர்"),
(233,"person","Maratha chief defeated at Sikandara","Malhar Rao Holkar","சிகந்தராவில் தோற்கடிக்கப்பட்ட மராத்திய தலைவர்","மல்ஹர் ராவ் ஹோல்கர்"),
(233,"person","Commander appointed over the huge Maratha army sent against Abdali","Sadasiva Rao","அப்தாலிக்கு எதிராக அனுப்பப்பட்ட பெரிய மராத்தியப் படையின் உண்மைத் தளபதி","சதாசிவ ராவ்"),
(233,"person","Rohilkhand ally of Abdali","Najib-ud-Daulah","அப்தாலியின் ரோஹில்கண்ட் கூட்டாளர்","நஜீப்-உத்-தௌலா"),
(233,"person","Oudh ally of Abdali","Shuja-ud-Daulah","அப்தாலியின் அவத் கூட்டாளர்","ஷுஜா-உத்-தௌலா"),
(233,"person","Nominal commander of the Maratha army at Panipat","Vishwas Rao","பானிப்பட்டில் மராத்தியப் படையின் பெயரளவிலான தளபதி","விஸ்வாஸ் ராவ்"),
(233,"relation","Vishwas Rao's relationship to the Peshwa","Young son","விஸ்வாஸ் ராவுக்கும் பேஷ்வாவுக்கும் உள்ள உறவு","இளம் மகன்"),
(233,"person","Actual commander of the Maratha army at Panipat","Sadasiva Rao","பானிப்பட்டில் மராத்தியப் படையின் உண்மைத் தளபதி","சதாசிவ ராவ்"),
(233,"person","Mughal emperor assassinated before Panipat","Alamgir II","பானிப்பட்டுக்கு முன் கொல்லப்பட்ட முகலாயப் பேரரசர்","இரண்டாம் ஆலம்கீர்"),
(233,"person","Son of Alamgir II who crowned himself after his father's death","Shah Alam II","ஆலம்கீர் II இறந்த பின் தன்னை பேரரசராக அறிவித்த மகன்","இரண்டாம் ஷா ஆலம்"),
(233,"person","Rival enthroned by the Wazir after Alamgir II's assassination","Shah Jahan III","ஆலம்கீர் II கொலைக்குப் பின் வசீரால் அரியணை ஏற்றப்பட்டவர்","மூன்றாம் ஷாஜகான்"),
(233,"action","What Sadasiva Rao did to Shah Jahan III","Deposed him","சதாசிவ ராவ் மூன்றாம் ஷாஜகானுக்கு செய்தது","பதவி நீக்கினார்"),
(233,"date","Exact date of the Third Battle of Panipat","14 January 1761","மூன்றாம் பானிப்பட் போரின் துல்லிய தேதி","14 ஜனவரி 1761"),
(233,"result","Outcome for the Maratha army at Panipat","Completely routed","பானிப்பட்டில் மராத்தியப் படையின் முடிவு","முழுமையாகத் தோற்கடிக்கப்பட்டது"),
(233,"person","Peshwa's son killed at Panipat","Viswas Rao","பானிப்பட்டில் கொல்லப்பட்ட பேஷ்வாவின் மகன்","விஸ்வாஸ் ராவ்"),
(233,"person","Maratha commander killed at Panipat","Sadasiva Rao","பானிப்பட்டில் கொல்லப்பட்ட மராத்திய தளபதி","சதாசிவ ராவ்"),
(233,"date","Month and year Balaji Baji Rao died after news of Panipat","June 1761","பானிப்பட் செய்திக்குப் பின் பாலாஜி பாஜி ராவ் இறந்த மாதம் மற்றும் ஆண்டு","ஜூன் 1761"),
(233,"person","Mughal emperor recognised by Abdali after Panipat","Shah Alam II","பானிப்பட்டுக்குப் பின் அப்தாலி அங்கீகரித்த முகலாயப் பேரரசர்","இரண்டாம் ஷா ஆலம்"),
(233,"period","Time within which Marathas restored much of their northern power after Panipat","Ten years","பானிப்பட்டுக்குப் பின் மராத்தியர்கள் வடக்கில் தங்கள் சக்தியை மீட்ட காலம்","பத்து ஆண்டுகள்"),

# Madhav Rao and later Peshwas
(233,"period","Tenure of Peshwa Madhav Rao I","1761–1772","முதலாம் மாதவ ராவின் பேஷ்வா காலம்","1761–1772"),
(233,"relation","Madhav Rao I's relationship to Balaji Baji Rao","Son","முதலாம் மாதவ ராவுக்கும் பாலாஜி பாஜி ராவுக்கும் உள்ள உறவு","மகன்"),
(233,"person","Regent for Madhav Rao I","Raghoba","முதலாம் மாதவ ராவின் பகர ஆட்சியாளர்","ரகோபா"),
(233,"relation","Raghoba's relationship to the Peshwa family","Younger brother of Balaji Baji Rao","ரகோபாவின் குடும்ப உறவு","பாலாஜி பாஜி ராவின் இளைய சகோதரர்"),
(233,"date","Year Madhav Rao fought a fierce battle with the Nizam of Hyderabad","1763","மாதவ ராவ் ஹைதராபாத் நிஜாமுடன் கடுமையாகப் போரிட்ட ஆண்டு","1763"),
(233,"period","Years of Madhav Rao's successful expeditions against Haider Ali","1765–1767","ஹைதர் அலிக்கு எதிரான மாதவ ராவின் வெற்றிகரமான படையெடுப்புகள்","1765–1767"),
(233,"person","Mysore ruler fought by Madhav Rao I","Haider Ali","முதலாம் மாதவ ராவால் எதிர்க்கப்பட்ட மைசூர் அரசர்","ஹைதர் அலி"),
(233,"date","Year Madhav Rao regained lost territories and forced Haider Ali into treaty","1772","மாதவ ராவ் இழந்த பகுதிகளை மீட்டு ஹைதர் அலியை ஒப்பந்தத்திற்கு உட்படுத்திய ஆண்டு","1772"),
(233,"group","North Indian power defeated by Madhav Rao to restore Maratha influence","Rohillas","மராத்திய செல்வாக்கை மீட்டெடுக்க மாதவ ராவ் தோற்கடித்த வடஇந்திய சக்தி","ரோஹில்லாக்கள்"),
(233,"date","Year Marathas brought Shah Alam II back to Delhi","1771","மராத்தியர்கள் இரண்டாம் ஷா ஆலத்தை டெல்லிக்கு மீண்டும் அழைத்த ஆண்டு","1771"),
(233,"territory","One territory ceded by Shah Alam II to the Marathas","Kora","இரண்டாம் ஷா ஆலம் மராத்தியர்களுக்கு ஒப்படைத்த பகுதி","கோரா"),
(233,"territory","Another territory ceded by Shah Alam II to the Marathas","Allahabad","இரண்டாம் ஷா ஆலம் மராத்தியர்களுக்கு ஒப்படைத்த பகுதி","அலகாபாத்"),
(233,"date","Year Narayan Rao became Peshwa","1772","நாராயண் ராவ் பேஷ்வாவான ஆண்டு","1772"),
(233,"date","Year Narayan Rao was murdered","1773","நாராயண் ராவ் கொல்லப்பட்ட ஆண்டு","1773"),
(233,"person","Posthumous son of Narayan Rao proclaimed Peshwa","Sawai Madhav Rao (Madhav Rao II)","நாராயண் ராவின் மரணத்திற்குப் பின் பிறந்து பேஷ்வாவாக்கப்பட்ட மகன்","சவாய் மாதவ ராவ் (இரண்டாம் மாதவ ராவ்)"),
(233,"age","Age at which Sawai Madhav Rao was proclaimed Peshwa","Forty days","சவாய் மாதவ ராவ் பேஷ்வாவாக அறிவிக்கப்பட்ட வயது","நாற்பது நாட்கள்"),
(233,"person","Last Peshwa","Baji Rao II","கடைசி பேஷ்வா","இரண்டாம் பாஜிராவ்"),
(233,"relation","Baji Rao II's relationship to Raghunath Rao","Son","இரண்டாம் பாஜிராவுக்கும் ரகுநாத ராவுக்கும் உள்ள உறவு","மகன்"),

# Anglo-Maratha wars
(234,"period","First Anglo-Maratha War","1775–1782","முதல் ஆங்கிலேய-மராத்தியப் போர்","1775–1782"),
(234,"person","Infant Peshwa during the First Anglo-Maratha War","Madhav Rao Narayan","முதல் ஆங்கிலேய-மராத்தியப் போரின் போது இருந்த குழந்தை பேஷ்வா","மாதவ ராவ் நாராயண்"),
(234,"person","Regent for the infant Madhav Rao Narayan","Nana Fadnavis","குழந்தை மாதவ ராவ் நாராயணின் பகர ஆட்சியாளர்","நானா பட்னவிஸ்"),
(234,"person","Claimant supported by the Bombay Company administration","Ragunath Rao","பம்பாய் கம்பெனி நிர்வாகம் ஆதரித்த உரிமைக்கோரியவர்","ரகுநாத ராவ்"),
(234,"place","Territory sought by the Company for supporting Ragunath Rao","Salsette","ரகுநாத ராவை ஆதரிப்பதற்குப் பதிலாக கம்பெனி கேட்ட பகுதி","சால்செட்"),
(234,"place","Another territory sought by the Company for supporting Ragunath Rao","Bassein","ரகுநாத ராவை ஆதரிப்பதற்குப் பதிலாக கம்பெனி கேட்ட பகுதி","பசேன்"),
(234,"person","Maratha chief who turned pro-British during the First Anglo-Maratha War","Mahadaji Scindia","முதல் ஆங்கிலேய-மராத்தியப் போரில் ஆங்கிலேய ஆதரவாளராக மாறிய மராத்திய தலைவர்","மகாதாஜி சிந்தியா"),
(234,"state","Maratha house that turned pro-British along with Scindia","Bhonsle of Nagpur","சிந்தியாவுடன் ஆங்கிலேய ஆதரவாளராக மாறிய மராத்திய வீடு","நாக்பூர் போன்ஸ்லே"),
(234,"treaty","Treaty ending the First Anglo-Maratha War","Treaty of Salbai","முதல் ஆங்கிலேய-மராத்தியப் போரை முடித்த ஒப்பந்தம்","சால்பாய் ஒப்பந்தம்"),
(234,"date","Year of the Treaty of Salbai","1782","சால்பாய் ஒப்பந்த ஆண்டு","1782"),
(234,"result","Fate of Ragunath Rao under the Treaty of Salbai","Pensioned off","சால்பாய் ஒப்பந்தத்தின்படி ரகுநாத ராவின் நிலை","ஓய்வூதியம் வழங்கப்பட்டது"),
(234,"period","Approximate peace period after Salbai","About two decades","சால்பாய்க்குப் பின் நிலவிய அமைதிக்காலம்","சுமார் இருபது ஆண்டுகள்"),
(234,"period","Second Anglo-Maratha War","1803–1806","இரண்டாம் ஆங்கிலேய-மராத்தியப் போர்","1803–1806"),
(234,"event","Death that triggered a scramble for possessions before the Second Anglo-Maratha War","Death of Nana Fadnavis","இரண்டாம் போர் முன் சொத்து சச்சரவுக்கு காரணமான மரணம்","நானா பட்னவிஸ் மரணம்"),
(234,"person","Peshwa dethroned before the Treaty of Bassein","Baji Rao II","பசேன் ஒப்பந்தத்திற்கு முன் பதவி நீக்கப்பட்ட பேஷ்வா","இரண்டாம் பாஜிராவ்"),
(234,"person","Governor-General who forced the Subsidiary Alliance on Baji Rao II","Lord Wellesley","இரண்டாம் பாஜிராவுக்கு துணைப்படைத் திட்டத்தைத் திணித்த ஆளுநர்-பொது","லார்ட் வெல்லெஸ்லி"),
(234,"treaty","Treaty signed by Baji Rao II accepting British help","Treaty of Bassein","ஆங்கிலேய உதவியை ஏற்று இரண்டாம் பாஜிராவ் கையெழுத்திட்ட ஒப்பந்தம்","பசேன் ஒப்பந்தம்"),
(234,"date","Year Treaty of Bassein was signed","1802","பசேன் ஒப்பந்தம் கையெழுத்தான ஆண்டு","1802"),
(234,"income","Income value of territory to be ceded under the Treaty of Bassein","Rs. 26 lakhs","பசேன் ஒப்பந்தத்தின்படி ஒப்படைக்க வேண்டிய நிலத்தின் வருமான மதிப்பு","ரூ. 26 லட்சம்"),
(234,"result","Military arrangement accepted by Maratha leaders after defeat in Second War","Subsidiary Alliance","இரண்டாம் போர்த் தோல்விக்குப் பின் ஏற்கப்பட்ட இராணுவ ஏற்பாடு","துணைப்படைத் திட்டம்"),
(234,"territory","One territory gained by the British after the Second Anglo-Maratha War","Doab","இரண்டாம் போருக்குப் பின் ஆங்கிலேயர் பெற்ற பகுதி","தோஆப்"),
(234,"territory","One territory gained by the British after the Second Anglo-Maratha War","Ahmednagar","இரண்டாம் போருக்குப் பின் ஆங்கிலேயர் பெற்ற பகுதி","அகமதுநகர்"),
(234,"territory","One territory gained by the British after the Second Anglo-Maratha War","Broach","இரண்டாம் போருக்குப் பின் ஆங்கிலேயர் பெற்ற பகுதி","பரோச்"),
(234,"period","Third Anglo-Maratha War","1817–1818","மூன்றாம் ஆங்கிலேய-மராத்தியப் போர்","1817–1818"),
(234,"person","Gaikwar's prime minister whose murder intensified conflict before the Third War","Gangadhar Sastri","மூன்றாம் போருக்கு முன் கொலை செய்யப்பட்ட காயக்குவாடின் பிரதமர்","கங்காதர் சாஸ்திரி"),
(234,"person","Favourite of Baji Rao II accused of killing Gangadhar Sastri","Trimbakji","கங்காதர் சாஸ்திரி கொலையில் குற்றம்சாட்டப்பட்ட இரண்டாம் பாஜிராவின் நெருங்கியவர்","திரிம்பக்ஜி"),
(234,"person","British Resident at Poona who pressed for Trimbakji's imprisonment","Mountstuart Elphinstone","திரிம்பக்ஜியை சிறையில் அடைக்க அழுத்தம் கொடுத்த பூனா பிரிட்டிஷ் ரெசிடெண்ட்","மவுண்ட்ஸ்டுவார்ட் எல்பின்ஸ்டன்"),
(234,"treaty","Treaty forced on the Peshwa at Poona in 1817","Treaty of Poona","1817இல் பேஷ்வாவுக்கு திணிக்கப்பட்ட ஒப்பந்தம்","பூனா ஒப்பந்தம்"),
(234,"term","Position Baji Rao II resigned under the 1817 treaty","Headship of the Maratha confederacy","1817 ஒப்பந்தத்தின்படி இரண்டாம் பாஜிரா கைவிட்ட பதவி","மராத்திய கூட்டமைப்பின் தலைமை"),
(234,"territory","Territory ceded by Baji Rao II to the British in 1817","Konkan","1817இல் இரண்டாம் பாஜிரா ஆங்கிலேயருக்கு ஒப்படைத்த பகுதி","கொங்கண்"),
(234,"state","Independence Baji Rao II had to recognise in 1817","Gaikwar","1817இல் இரண்டாம் பாஜிரா அங்கீகரிக்க வேண்டிய சுதந்திர அரசு","காயக்குவாட்"),
(234,"event","Action by Baji Rao II that openly triggered the Third War","Burning the Poona Residency","மூன்றாம் போரை வெளிப்படையாகத் தூண்டிய இரண்டாம் பாஜிராவின் செயல்","பூனா ரெசிடென்சியை எரித்தல்"),
(234,"person","British general who captured Poona and pursued Baji Rao II","General Smith","பூனாவை கைப்பற்றி இரண்டாம் பாஜிராவைத் துரத்திய பிரிட்டிஷ் தளபதி","ஜெனரல் ஸ்மித்"),
(234,"place","One battle where General Smith defeated Baji Rao II's forces","Ashta","ஜெனரல் ஸ்மித் இரண்டாம் பாஜிராவின் படையைத் தோற்கடித்த இடம்","அஷ்டா"),
(234,"place","One battle where General Smith defeated Baji Rao II's forces","Kirkee","ஜெனரல் ஸ்மித் இரண்டாம் பாஜிராவின் படையைத் தோற்கடித்த இடம்","கிர்கீ"),
(234,"place","One battle where General Smith defeated Baji Rao II's forces","Korgaon","ஜெனரல் ஸ்மித் இரண்டாம் பாஜிராவின் படையைத் தோற்கடித்த இடம்","கோர்காவ்"),
(234,"date","Year Baji Rao II surrendered","1818","இரண்டாம் பாஜிரா சரணடைந்த ஆண்டு","1818"),
(234,"person","British official to whom Baji Rao II surrendered","Elphinstone","இரண்டாம் பாஜிரா சரணடைந்த பிரிட்டிஷ் அதிகாரி","எல்பின்ஸ்டன்"),
(234,"result","Institution abolished by the British after the Third Anglo-Maratha War","Peshwai","மூன்றாம் போருக்குப் பின் ஆங்கிலேயர் ஒழித்த நிறுவனம்","பேஷ்வா பதவி"),
(234,"result","What the British did with Peshwa dominions","Annexed them","பேஷ்வாவின் பகுதிகளை ஆங்கிலேயர் செய்தது","இணைத்துக் கொண்டனர்"),
(235,"date","Year until which Baji Rao II lived as a pensioned prisoner","1851","இரண்டாம் பாஜிரா ஓய்வூதிய கைதியாக வாழ்ந்த இறுதி ஆண்டு","1851"),
(235,"person","Descendant of Shivaji made king of a small Satara kingdom","Pratap Singh","சதாரா சிற்றரசின் மன்னனாக்கப்பட்ட சிவாஜி வம்சத்தவர்","பிரதாப் சிங்"),
(235,"result","Political organisation dissolved after the Third Anglo-Maratha War","Maratha Confederacy","மூன்றாம் போருக்குப் பின் கலைக்கப்பட்ட அரசியல் அமைப்பு","மராத்திய கூட்டமைப்பு"),
(235,"houses","Three houses named in the Maratha Confederacy","Bhonsle, Holkar and Scindia","மராத்திய கூட்டமைப்பில் குறிப்பிடப்பட்ட மூன்று வீடுகள்","போன்ஸ்லே, ஹோல்கர், சிந்தியா"),
(235,"person","Former Poona Resident who became Governor of Bombay","Mountstuart Elphinstone","பூனா ரெசிடெண்டாக இருந்து பம்பாய் ஆளுநரானவர்","மவுண்ட்ஸ்டுவார்ட் எல்பின்ஸ்டன்"),

# Peshwa administration
(235,"period","Period of Maratha administration under the Peshwas","1714–1818","பேஷ்வா கால மராத்திய நிர்வாகத்தின் காலம்","1714–1818"),
(235,"feature","Status of the Peshwa office under Shivaji originally","Not hereditary","சிவாஜி காலத்தில் பேஷ்வா பதவியின் நிலை","மரபுரிமை அல்ல"),
(235,"person","Peshwa whose ability made the office supreme and hereditary","Balaji Vishwanath","பேஷ்வா பதவியை உயர்த்தி மரபுரிமை ஆக்கியவர்","பாலாஜி விஸ்வநாத்"),
(235,"centre","Centre of Maratha administration under the Peshwas","Peshwa Secretariat at Poona","பேஷ்வா கால மராத்திய நிர்வாக மையம்","பூனா பேஷ்வா செயலகம்"),
(235,"record","Register recording daily revenues, grants and foreign payments","Daily register","தினசரி வருவாய், மானியம், வெளிநாட்டு தொகைகளைப் பதிவு செய்த ஆவணம்","தினசரி பதிவு"),
(235,"office","Governor of a larger province under the Peshwas","Sar-subahdar","பேஷ்வா கால பெரிய மாகாணத்தின் ஆளுநர்","சர்-சுபாதார்"),
(235,"term","One term for provincial divisions under the Peshwas","Subahs","பேஷ்வா கால மாகாணப் பிரிவுகளில் ஒரு பெயர்","சுபாக்கள்"),
(235,"term","Another term for provincial divisions under the Peshwas","Pranths","பேஷ்வா கால மாகாணப் பிரிவுகளில் மற்றொரு பெயர்","பிராந்துகள்"),
(235,"office","Peshwa representative in districts","Mamlatdar","பேஷ்வா கால மாவட்ட பிரதிநிதி","மாம்லத்தார்"),
(235,"office","Another Peshwa representative in districts","Kamavistar","பேஷ்வா கால மாவட்டத்தின் மற்றொரு பிரதிநிதி","கமாவிஸ்தார்"),
(235,"office","District officer in charge of accounts and oversight","Deshmukh","கணக்குகள் மற்றும் மேற்பார்வைக்கு பொறுப்பான மாவட்ட அதிகாரி","தேச்முக்"),
(235,"office","Another district officer in charge of accounts and oversight","Deshpande","கணக்குகள் மற்றும் மேற்பார்வைக்கு பொறுப்பான மற்றொரு மாவட்ட அதிகாரி","தேச்பாண்டே"),
(235,"system","Description of Peshwa district administration created by overlapping officers","Checks and balances","பேஷ்வா மாவட்ட நிர்வாகத்தில் ஏற்பட்ட அமைப்பு","கட்டுப்பாடும் சமநிலையும்"),
(235,"term","Heavy security sum collected from Mamlatdars on first appointment","Rasad","மாம்லத்தார்களிடமிருந்து முதல் நியமனத்தில் வசூலிக்கப்பட்ட பெரிய பாதுகாப்புத் தொகை","ரசத்"),
(235,"unit","Basic unit of Peshwa administration","Village","பேஷ்வா நிர்வாகத்தின் அடிப்படை அலகு","கிராமம்"),
(235,"office","Chief village officer under the Peshwas","Patel","பேஷ்வா கால கிராமத் தலைவர்","படேல்"),
(235,"function","Main fiscal duty of the Patel","Remit revenue collections to the centre","படேலின் முக்கிய நிதிப் பொறுப்பு","வருவாயை மையத்திற்கு அனுப்புதல்"),
(235,"feature","Nature of the Patel's post","Hereditary","படேல் பதவியின் தன்மை","மரபுரிமை"),
(235,"office","Village accountant and record-keeper","Kulkarni","கிராமக் கணக்காளர் மற்றும் பதிவாளர்","குல்கர்னி"),
(235,"labour","Compulsory labour performed by village artisans","Begar","கிராமக் கைவினைஞர்கள் செய்த கட்டாய உழைப்பு","பெகார்"),
(235,"office","Chief urban officer under the Peshwas","Kotwal","பேஷ்வா கால நகரத் தலைவர்","கோத்வால்"),
(235,"function","One duty of the Kotwal","Maintenance of peace and order","கோத்வாலின் ஒரு கடமை","அமைதி மற்றும் ஒழுங்கு பராமரித்தல்"),
(235,"function","One duty of the Kotwal","Regulation of prices","கோத்வாலின் ஒரு கடமை","விலை கட்டுப்பாடு"),
(235,"function","One duty of the Kotwal","Settlement of civil disputes","கோத்வாலின் ஒரு கடமை","சிவில் தகராறுகளைத் தீர்த்தல்"),
(235,"function","One duty of the Kotwal","Sending monthly accounts to government","கோத்வாலின் ஒரு கடமை","மாதாந்திர கணக்குகளை அரசுக்கு அனுப்புதல்"),
(235,"revenue","Main source of Peshwa income","Land revenue","பேஷ்வா அரசின் முக்கிய வருவாய் ஆதாரம்","நிலவரி"),
(235,"system","Revenue method adopted by Peshwas instead of Shivaji's produce-sharing","Tax farming","சிவாஜியின் விளைச்சல் பங்கு முறைக்கு பதிலாக பேஷ்வாக்கள் பின்பற்றிய முறை","வரி குத்தகை"),
(235,"basis","Basis used to fix land taxes","Fertility of the land","நிலவரி நிர்ணயத்தின் அடிப்படை","நிலத்தின் வளம்"),
(236,"revenue","Natural resource yielding income to the Peshwa government","Forests","பேஷ்வா அரசுக்கு வருமானம் அளித்த இயற்கை வளம்","காடுகள்"),
(236,"produce","Forest product whose sale yielded revenue","Grass","அரசுக்கு வருமானம் அளித்த காட்டு உற்பத்தி","புல்"),
(236,"produce","Forest product whose sale yielded revenue","Bamboo","அரசுக்கு வருமானம் அளித்த காட்டு உற்பத்தி","மூங்கில்"),
(236,"produce","Forest product whose sale yielded revenue","Fuel wood","அரசுக்கு வருமானம் அளித்த காட்டு உற்பத்தி","எரிபொருள் மரம்"),
(236,"produce","Forest product whose sale yielded revenue","Honey","அரசுக்கு வருமானம் அளித்த காட்டு உற்பத்தி","தேன்"),
(236,"classes","Number of land classes under Peshwa assessment","Three","பேஷ்வா நில மதிப்பீட்டில் நில வகைகள் எண்ணிக்கை","மூன்று"),
(236,"factor","One basis for the three land classes","Kinds of crops","மூன்று நில வகைகளுக்கான ஒரு அடிப்படை","பயிர்களின் வகைகள்"),
(236,"factor","One basis for the three land classes","Irrigation facilities","மூன்று நில வகைகளுக்கான ஒரு அடிப்படை","பாசன வசதிகள்"),
(236,"factor","One basis for the three land classes","Productivity","மூன்று நில வகைகளுக்கான ஒரு அடிப்படை","உற்பத்தித் திறன்"),
(236,"right","Officer through whom villagers could represent land rights to higher authorities","Patel","கிராமவாசிகள் தங்கள் நில உரிமையை மேலதிகாரிகளிடம் முன்வைத்த அதிகாரி","படேல்"),
(236,"tax","One major extra revenue source under the Peshwas","Chauth","பேஷ்வா கால முக்கிய கூடுதல் வருவாய் ஆதாரம்","சௌத்"),
(236,"tax","Another major extra revenue source under the Peshwas","Sardeshmukhi","பேஷ்வா கால முக்கிய கூடுதல் வருவாய் ஆதாரம்","சர்தேஷ்முகி"),
(236,"share","Share of Chauth allotted to the ruler","25 percent","சௌத்தில் அரசருக்கான பங்கு","25 சதவீதம்"),
(236,"share","Share of Chauth allotted to Maratha officials and military heads","66 percent","சௌத்தில் மராத்திய அதிகாரிகள் மற்றும் இராணுவத் தலைவர்களுக்கு வழங்கிய பங்கு","66 சதவீதம்"),
(236,"share","Share of Chauth allotted to Pant Sachiv","6 percent","சௌத்தில் பந்த் சச்சிவுக்கான பங்கு","6 சதவீதம்"),
(236,"share","Share of Chauth allotted to tax collectors","3 percent","சௌத்தில் வரி வசூலாளர்களுக்கான பங்கு","3 சதவீதம்"),
(236,"office","Official identified as Pant Sachiv","Chief, a Brahman by birth","பந்த் சச்சிவ் குறித்து பாடநூல் கூறும் அடையாளம்","பிராமணப் பிறப்புடைய தலைமை அதிகாரி"),
(236,"mint","Who could mint coins after paying royalty and obtaining a licence","Goldsmiths","ராயல்டி செலுத்தி உரிமம் பெற்று நாணயம் உற்பத்தி செய்தவர்கள்","பொற்கொல்லர்கள்"),
(236,"date","Year private mints were closed","1760","தனியார் நாணயச்சாலைகள் மூடப்பட்ட ஆண்டு","1760"),
(236,"result","Institution created after closure of private mints","Central mint","தனியார் நாணயச்சாலைகள் மூடப்பட்ட பின் உருவாக்கப்பட்டது","மத்திய நாணயச்சாலை"),
(236,"tax","Tax imposed on remarriage of widows","Widow-remarriage tax","விதவை மறுமணத்திற்கு விதிக்கப்பட்ட வரி","விதவை மறுமண வரி"),
(236,"tax","Tax imposed on sheep and buffaloes","Livestock tax","ஆடுகள் மற்றும் எருமைகளுக்கு விதிக்கப்பட்ட வரி","கால்நடை வரி"),
(236,"tax","Fee charged for use of pasture","Pasture fee","மேய்ச்சலுக்காக வசூலிக்கப்பட்ட கட்டணம்","மேய்ச்சல் கட்டணம்"),
(236,"tax","Tax levied on melon cultivation in river beds","Melon cultivation tax","நதிப்படுகையில் முலாம்பழச் சாகுபடிக்கு விதிக்கப்பட்ட வரி","முலாம்பழச் சாகுபடி வரி"),
(236,"tax","Duty on inheritance","Succession duty","வாரிசுரிமைக்கு விதிக்கப்பட்ட வரி","வாரிசுரிமை வரி"),
(236,"tax","Emergency tax equal to one year's income of the taxpayer","Kurja-Patti or Tasti-Patti","வரி செலுத்துபவரின் ஒரு ஆண்டு வருமானத்துக்கு சமமான அவசர வரி","குர்ஜா-பட்டி அல்லது தஸ்தி-பட்டி"),
(236,"fee","Fee charged on money bonds in the administration of justice","25 percent","பணப் பத்திரங்களுக்கு நீதி நிர்வாகத்தில் வசூலிக்கப்பட்ட கட்டணம்","25 சதவீதம்"),
(236,"exemption","Group exempted from duty on imported things for personal use","Brahmins","தங்களது பயன்பாட்டிற்கான இறக்குமதிப் பொருட்களுக்கு வரிவிலக்கு பெற்றோர்","பிராமணர்கள்"),
(236,"watchmen","Community generally employed as village watchmen","Mahars","கிராமக் காவலர்களாக பொதுவாக நியமிக்கப்பட்ட சமூகத்தினர்","மஹார்கள்"),
(236,"office","Police superintendent referred to in urban administration","Nagarka","நகர நிர்வாகத்தில் குறிப்பிடப்பட்ட காவல் மேற்பார்வையாளர்","நகர்கா"),
(236,"justice","Overall condition of the Peshwa judicial system","Very imperfect","பேஷ்வா நீதிமுறையின் மொத்த நிலை","மிகவும் குறைபாடானது"),
(236,"feature","Status of codified law under Peshwas","No codified law","பேஷ்வா கால சட்டக் குறியீட்டின் நிலை","குறியீட்டு சட்டம் இல்லை"),
(236,"priority","Method given high priority in civil disputes","Arbitration","சிவில் தகராறுகளில் முன்னுரிமை பெற்ற முறை","மத்தியஸ்தம்"),
(236,"institution","Body deciding cases when arbitration failed","Panchayat","மத்தியஸ்தம் தோல்வியுற்றால் வழக்கைத் தீர்த்த அமைப்பு","பஞ்சாயத்து"),
(236,"appeal","Officer receiving appeals from panchayat decisions","Mamlatdar","பஞ்சாயத்து தீர்ப்புக்கு மேல்முறையீடு ஏற்ற அதிகாரி","மாம்லத்தார்"),
(236,"hierarchy","Highest authority in criminal judicial hierarchy","Raja Chhatrapati","குற்றவியல் நீதி வரிசையின் உயர்ந்த அதிகாரி","ராஜா சத்திரபதி"),
(236,"method","Coercive method used to obtain confessions","Flogging and torture","ஒப்புதல் வாங்க பயன்படுத்தப்பட்ட கட்டாய முறை","அடி மற்றும் சித்திரவதை"),
(236,"model","Military system on which Peshwa forces were modelled","Mughal military system","பேஷ்வா கால மராத்தியப் படை மாதிரி எடுத்த இராணுவ அமைப்பு","முகலாய இராணுவ அமைப்பு"),
(237,"recruitment","Contrast between Shivaji and Peshwa recruitment","Peshwas recruited from all India and social groups","சிவாஜியுடன் ஒப்பிடும் போது பேஷ்வா ஆட்சேர்ப்பு முறை","இந்தியா முழுவதிலிருந்தும் அனைத்து சமூகக் குழுக்களிலிருந்தும் ஆட்சேர்ப்பு"),
(237,"group","One non-Maratha group in the Peshwa army","Arabs","பேஷ்வா படையில் இருந்த மராத்தியரல்லாத குழு","அரபியர்கள்"),
(237,"group","One non-Maratha group in the Peshwa army","Abyssinians","பேஷ்வா படையில் இருந்த மராத்தியரல்லாத குழு","அபிசீனியர்கள்"),
(237,"group","One non-Maratha group in the Peshwa army","Rajputs","பேஷ்வா படையில் இருந்த மராத்தியரல்லாத குழு","ராஜபுத்திரர்கள்"),
(237,"group","One non-Maratha group in the Peshwa army","Rohillas","பேஷ்வா படையில் இருந்த மராத்தியரல்லாத குழு","ரோஹில்லாக்கள்"),
(237,"group","One non-Maratha group in the Peshwa army","Sikhs","பேஷ்வா படையில் இருந்த மராத்தியரல்லாத குழு","சீக்கியர்கள்"),
(237,"army","Main strength of the Maratha army under the Peshwas","Cavalry","பேஷ்வா கால மராத்தியப் படையின் முக்கிய வலிமை","குதிரைப்படை"),
(237,"obligation","Annual duty of every jagirdar to the Peshwa army","Bring a stipulated number of horsemen for muster","ஒவ்வொரு ஜாகீர்தாரின் ஆண்டு இராணுவக் கடமை","குறிப்பிட்ட எண்ணிக்கையிலான குதிரைவீரர்களை அணிவகுப்புக்கு கொண்டுவருதல்"),
(237,"classes","Number of cavalry classes based on horse quality","Three","குதிரைத் தரத்தின் அடிப்படையில் குதிரைப்படை வகைகள் எண்ணிக்கை","மூன்று"),
(237,"recruitment","Source of Peshwa infantry manpower","Other parts of the country","பேஷ்வா காலாட்படைக்கான ஆட்சேர்ப்பு ஆதாரம்","நாட்டின் பிற பகுதிகள்"),
(237,"group","One group in Peshwa infantry paid more than Maratha soldiers","Arabs","மராத்திய வீரர்களைவிட அதிக ஊதியம் பெற்ற காலாட்படை குழு","அரபியர்கள்"),
(237,"group","One group in Peshwa infantry paid more than Maratha soldiers","Rohillas","மராத்திய வீரர்களைவிட அதிக ஊதியம் பெற்ற காலாட்படை குழு","ரோஹில்லாக்கள்"),
(237,"group","One group in Peshwa infantry paid more than Maratha soldiers","Sikhs","மராத்திய வீரர்களைவிட அதிக ஊதியம் பெற்ற காலாட்படை குழு","சீக்கியர்கள்"),
(237,"group","One group in Peshwa infantry paid more than Maratha soldiers","Sindhis","மராத்திய வீரர்களைவிட அதிக ஊதியம் பெற்ற காலாட்படை குழு","சிந்திகள்"),
(237,"artillery","People who mostly manned Maratha artillery","Portuguese and Indian Christians","மராத்திய பீரங்கிப்படையை பெரும்பாலும் இயக்கியவர்கள்","போர்த்துக்கீசியரும் இந்திய கிறித்தவர்களும்"),
(237,"artillery","European group later recruited into Maratha artillery","English","பின்னர் மராத்திய பீரங்கிப்படையில் சேர்க்கப்பட்ட ஐரோப்பியர்கள்","ஆங்கிலேயர்கள்"),
(237,"navy","Purpose of Maratha navy","Guard ports, check piracy and collect customs","மராத்திய கடற்படையின் நோக்கம்","துறைமுகங்களை காக்க, கடற்கொள்ளையைத் தடுக்க, சுங்கம் வசூலிக்க"),
(237,"person","Peshwa who built naval bases at Konkan, Khanderi and Vijayadurg","Balaji Vishwanath","கொங்கண், கந்தேரி, விஜயதுர்கில் கடற்படைத் தளங்கள் அமைத்த பேஷ்வா","பாலாஜி விஸ்வநாத்"),
(237,"base","One Maratha naval base","Khanderi","மராத்திய கடற்படைத் தளங்களில் ஒன்று","கந்தேரி"),
(237,"base","One Maratha naval base","Vijayadurg","மராத்திய கடற்படைத் தளங்களில் ஒன்று","விஜயதுர்க்"),

# Marathas in Tamil Nadu and Desinghu
(237,"ruler","Vijayanagar ruler who developed the Nayankara system","Krishna Devaraya","நாயக்கர் முறையை வளர்த்த விஜயநகர அரசர்","கிருஷ்ணதேவராயர்"),
(237,"period","Reign of Krishna Devaraya given in this section","1509–1529","இப்பகுதியில் கொடுக்கப்பட்ட கிருஷ்ணதேவராயரின் ஆட்சிக்காலம்","1509–1529"),
(237,"nayankara","One of the three large Nayankaras in Tamil country","Senji","தமிழ்நாட்டின் மூன்று பெரிய நாயக்கராட்சிகளில் ஒன்று","செஞ்சி"),
(237,"nayankara","One of the three large Nayankaras in Tamil country","Thanjavur","தமிழ்நாட்டின் மூன்று பெரிய நாயக்கராட்சிகளில் ஒன்று","தஞ்சாவூர்"),
(237,"nayankara","One of the three large Nayankaras in Tamil country","Madurai","தமிழ்நாட்டின் மூன்று பெரிய நாயக்கராட்சிகளில் ஒன்று","மதுரை"),
(237,"title","Title of subordinate chieftains under the Nayankara system","Palayakkarars","நாயக்கர் முறையின் கீழ் இருந்த சிற்றரசர்களின் பட்டம்","பாளையக்காரர்கள்"),
(237,"term","Name of their fiefdoms","Palayams","பாளையக்காரர்களின் பீடபூமி/ஆட்சிப்பகுதி பெயர்","பாளையங்கள்"),
(237,"date","Year Nayak rule at Thanjavur was eclipsed in this section","1673","தஞ்சாவூர் நாயக்கர் ஆட்சி மறைந்த ஆண்டு","1673"),
(237,"person","Maratha general whose troops captured Thanjavur from Nayak power","Venkoji","நாயக்கர்களிடமிருந்து தஞ்சாவூரை கைப்பற்றிய மராத்திய தளபதி","வெங்கோஜி"),
(237,"person","Bundela Rajput appointed Kiladar of Senji in 1700","Swarup Singh","1700இல் செஞ்சியின் கிலாதாராக நியமிக்கப்பட்ட புந்தேலா ராஜபுத்திரர்","ஸ்வரூப் சிங்"),
(237,"office","Meaning of Kiladar","Fort commandant","கிலாதார் என்ற பதவியின் பொருள்","கோட்டைத் தளபதி"),
(237,"date","Year Swarup Singh was appointed at Senji","1700","ஸ்வரூப் சிங் செஞ்சியில் நியமிக்கப்பட்ட ஆண்டு","1700"),
(237,"date","Year of Swarup Singh's death","1714","ஸ்வரூப் சிங் இறந்த ஆண்டு","1714"),
(237,"person","Son of Swarup Singh known as Raja Desinghu","Tej Singh","ராஜா தேசிங்கு என அறியப்பட்ட ஸ்வரூப் சிங்கின் மகன்","தேஜ் சிங்"),
(237,"person","Nawab angered by Desinghu's refusal to pay tribute","Sadat-ul-lah Khan","தேசிங்கு கப்பம் செலுத்த மறுத்ததால் கோபமடைந்த நவாப்","சதத்-உல்-லா கான்"),
(237,"age","Age of Raja Desinghu when killed","Twenty-two","ராஜா தேசிங்கு கொல்லப்பட்ட வயது","இருபத்திரண்டு"),
(237,"practice","Fate of Desinghu's young wife after his death","Committed sati","தேசிங்கு இறந்த பின் அவரது இளம் மனைவியின் நிலை","சதி செய்தார்"),
(237,"memory","Medium through which Desinghu's gallantry was immortalised","Popular Tamil ballads","தேசிங்குவின் வீரத்தை நிலைநிறுத்திய இலக்கிய வடிவம்","பிரபல தமிழ் நாட்டுப்புறப் பாடல்கள்"),

# Thanjavur Marathas and Serfoji
(238,"date","Year Venkoji crowned himself king and Maratha rule began in Thanjavur","1676","வெங்கோஜி தன்னை மன்னராக முடிசூட்டி தஞ்சாவூரில் மராத்திய ஆட்சி தொடங்கிய ஆண்டு","1676"),
(238,"date","Year Shivaji invaded the Carnatic and displaced Venkoji","1677","சிவாஜி கர்நாடகத்தில் படையெடுத்து வெங்கோஜியை நீக்கிய ஆண்டு","1677"),
(238,"person","Half-brother placed by Shivaji on the Thanjavur throne","Santaji","சிவாஜி தஞ்சாவூர் அரியணையில் அமர்த்திய ஒன்றுவிட்ட சகோதரர்","சந்தாஜி"),
(238,"person","Son who succeeded Venkoji in Thanjavur","Shahji","வெங்கோஜிக்கு பின் தஞ்சாவூரில் ஆட்சிக்கு வந்த மகன்","ஷாஜி"),
(238,"person","Brother of Shahji who succeeded because Shahji had no heir","Serfoji I","ஷாஜிக்கு வாரிசில்லை என்பதால் அடுத்து ஆட்சிக்கு வந்த சகோதரர்","முதலாம் சரபோஜி"),
(238,"period","Reign of Serfoji I","1712–1728","முதலாம் சரபோஜியின் ஆட்சிக்காலம்","1712–1728"),
(238,"person","Brother who succeeded Serfoji I","Tukkoji","முதலாம் சரபோஜிக்கு பின் ஆட்சிக்கு வந்த சகோதரர்","துக்கோஜி"),
(238,"person","Ruler who succeeded Tukkoji","Pratap Singh","துக்கோஜிக்கு பின் ஆட்சிக்கு வந்தவர்","பிரதாப் சிங்"),
(238,"period","Reign of Pratap Singh","1739–1763","பிரதாப் சிங்கின் ஆட்சிக்காலம்","1739–1763"),
(238,"person","Son of Pratap Singh who ruled until 1787","Thuljaji","1787 வரை ஆட்சி செய்த பிரதாப் சிங்கின் மகன்","துல்ஜாஜி"),
(238,"date","Year Thuljaji's rule ended","1787","துல்ஜாஜியின் ஆட்சி முடிந்த ஆண்டு","1787"),
(238,"age","Age at which Serfoji II was crowned","Ten","இரண்டாம் சரபோஜி முடிசூட்டப்பட்ட வயது","பத்து"),
(238,"person","Regent for the young Serfoji II","Amarsingh","இளம் இரண்டாம் சரபோஜியின் பகர ஆட்சியாளர்","அமர்சிங்"),
(238,"result","Political concession forced on Serfoji II by the English","Ceded administration of the kingdom to the British","ஆங்கிலேயர் இரண்டாம் சரபோஜியிடம் திணித்த அரசியல் ஒப்புதல்","அரசின் நிர்வாகத்தை ஆங்கிலேயரிடம் ஒப்படைத்தார்"),
(238,"status","Dynastic status of Serfoji II in Thanjavur","Last ruler of the Bhonsle dynasty there","தஞ்சாவூரில் இரண்டாம் சரபோஜியின் வம்ச நிலை","அங்குள்ள போன்ஸ்லே வம்சத்தின் கடைசி அரசர்"),
(238,"person","German missionary who taught Serfoji II","Friedrich Schwartz","இரண்டாம் சரபோஜிக்கு கல்வி கற்பித்த ஜெர்மன் மறைப்பணியாளர்","பிரிட்ரிக் ஸ்வார்ட்ஸ்"),
(238,"achievement","Linguistic achievement of Serfoji II","Mastered several European languages","இரண்டாம் சரபோஜியின் மொழித் திறன்","பல ஐரோப்பிய மொழிகளில் தேர்ச்சி"),
(238,"institution","Library substantially expanded by Serfoji II","Saraswati Mahal Library","இரண்டாம் சரபோஜி பெரிதும் விரிவுபடுத்திய நூலகம்","சரஸ்வதி மஹால் நூலகம்"),
(238,"technology","Printing initiative of Serfoji II","Press for Marathi and Sanskrit","இரண்டாம் சரபோஜியின் அச்சுத் திட்டம்","மராத்தி மற்றும் சமஸ்கிருத அச்சகம்"),
(238,"education","Educational initiative of Serfoji II","Free modern public schools","இரண்டாம் சரபோஜியின் கல்வித் திட்டம்","இலவச நவீன பொதுப்பள்ளிகள்"),
(238,"person","Missionary scholar at Tranquebar admired by Serfoji II","C.S. John","தரங்கம்பாடியில் இரண்டாம் சரபோஜி மதித்த மறைப்பணியாளர் அறிஞர்","சி.எஸ். ஜான்"),
(238,"date","Year C.S. John submitted a free-school project to the colonial government","1812","சி.எஸ். ஜான் இலவசப் பள்ளித் திட்டத்தை காலனித்துவ அரசிடம் சமர்ப்பித்த ஆண்டு","1812"),
(238,"person","Madras governor who proposed elementary public schools in the 1820s","Thomas Munro","1820களில் தொடக்கப் பொதுப்பள்ளிகளை முன்மொழிந்த மதராஸ் ஆளுநர்","தாமஸ் மன்ரோ"),
(238,"date","Year the Company government established a modern school for natives in Madras","1841","மதராசில் பூர்வகுடிகளுக்கான நவீனப் பள்ளியை கம்பெனி நிறுவிய ஆண்டு","1841"),
(238,"date","Year from which German missionaries had run free schools in southern provinces","1707","தென் மாகாணங்களில் ஜெர்மன் மறைப்பணியாளர்கள் இலவசப் பள்ளிகளை நடத்திய தொடக்க ஆண்டு","1707"),
(238,"date","Year Serfoji II established the first modern public school for non-Christian natives","1803","மதமாற்றமில்லா பூர்வகுடிகளுக்கான முதல் நவீன பொதுப்பள்ளியை இரண்டாம் சரபோஜி நிறுவிய ஆண்டு","1803"),
(238,"script","Script used for Marathi in court records held at Saraswati Mahal","Modi","சரஸ்வதி மஹாலில் உள்ள மராத்தி அரண்மனைப் பதிவுகளின் எழுத்துமுறை","மோடி"),
(239,"innovation","New learning introduced by Serfoji II in state-run schools","Navavidya","இரண்டாம் சரபோஜி அரசுப் பள்ளிகளில் அறிமுகப்படுத்திய புதிய கற்றல்","நவவித்யா"),
(239,"date","Year of the education report for Governor Munro's census","1823","மன்ரோவின் கல்வி கணக்கெடுப்பிற்கான அறிக்கையின் ஆண்டு","1823"),
(239,"number","Total free schools in wider Thanjavur district in the 1823 report","44","1823 அறிக்கையில் பெரிய தஞ்சாவூர் மாவட்டத்தின் மொத்த இலவசப் பள்ளிகள்","44"),
(239,"number","Free schools run by Serfoji's government in the 1823 report","21","1823 அறிக்கையில் சரபோஜி அரசு நடத்திய இலவசப் பள்ளிகள்","21"),
(239,"number","Free schools run by missionaries in the 1823 report","19","1823 அறிக்கையில் மறைப்பணியாளர்கள் நடத்திய இலவசப் பள்ளிகள்","19"),
(239,"number","Free school run by a temple in the 1823 report","One","1823 அறிக்கையில் கோவில் நடத்திய இலவசப் பள்ளி","ஒன்று"),
(239,"number","Schools run free by teachers themselves in the 1823 report","Three","1823 அறிக்கையில் ஆசிரியர்களே இலவசமாக நடத்திய பள்ளிகள்","மூன்று"),
(239,"institution","King's favourite almshouse associated with a free school","Muktambal Chattiram","அரசரின் விருப்பமான சத்திரமும் இலவசப் பள்ளியுடனும் தொடர்புடைய இடம்","முக்தாம்பாள் சத்திரம்"),
(239,"date","Year Muktambal Chattiram was established","1803","முக்தாம்பாள் சத்திரம் நிறுவப்பட்ட ஆண்டு","1803"),
(239,"number","Teachers at Muktambal Chattiram free school in 1822","15","1822இல் முக்தாம்பாள் சத்திரப் பள்ளியில் இருந்த ஆசிரியர்கள் எண்ணிக்கை","15"),
(239,"number","Students at Muktambal Chattiram free school in 1822","464","1822இல் முக்தாம்பாள் சத்திரப் பள்ளி மாணவர்கள் எண்ணிக்கை","464"),
(239,"place","Village where Serfoji supported a free school for needy Christians","Kannandangudi","தேவையுள்ள கிறித்தவர்களுக்கான இலவசப் பள்ளியை சரபோஜி ஆதரித்த கிராமம்","கண்ணந்தங்குடி"),
(239,"institution","Research institution founded by Serfoji II for herbal medicine","Dhanvantari Mahal","மூலிகை மருத்துவ ஆராய்ச்சிக்காக இரண்டாம் சரபோஜி நிறுவிய நிறுவனம்","தன்வந்திரி மஹால்"),
(239,"innovation","Medical record practice introduced at Dhanvantari Mahal","Maintaining patient case-sheets","தன்வந்திரி மஹாலில் அறிமுகப்படுத்தப்பட்ட மருத்துவப் பதிவு முறை","நோயாளி வழக்குத் தாள்கள் பராமரித்தல்"),
(239,"system","One medical system represented in Dhanvantari Mahal research","Modern medicine","தன்வந்திரி மஹால் ஆராய்ச்சியில் இருந்த ஒரு மருத்துவ முறை","நவீன மருத்துவம்"),
(239,"system","One medical system represented in Dhanvantari Mahal research","Ayurveda","தன்வந்திரி மஹால் ஆராய்ச்சியில் இருந்த ஒரு மருத்துவ முறை","ஆயுர்வேதம்"),
(239,"system","One medical system represented in Dhanvantari Mahal research","Unani","தன்வந்திரி மஹால் ஆராய்ச்சியில் இருந்த ஒரு மருத்துவ முறை","யூனானி"),
(239,"system","One medical system represented in Dhanvantari Mahal research","Siddha","தன்வந்திரி மஹால் ஆராய்ச்சியில் இருந்த ஒரு மருத்துவ முறை","சித்த மருத்துவம்"),
(239,"number","Volumes of medical research produced under Serfoji II","Eighteen","இரண்டாம் சரபோஜி காலத்தில் உருவாக்கப்பட்ட மருத்துவ ஆராய்ச்சி தொகுதிகள்","பதினெட்டு"),
(239,"art","Traditional art patronised by Serfoji II","Dance","இரண்டாம் சரபோஜி ஆதரித்த பாரம்பரியக் கலை","நடனம்"),
(239,"art","Traditional art patronised by Serfoji II","Music","இரண்டாம் சரபோஜி ஆதரித்த பாரம்பரியக் கலை","இசை"),
(239,"work","Work authored by Serfoji II","Kumarasambhava Champu","இரண்டாம் சரபோஜி எழுதிய நூல்","குமாரசம்பவ சம்பு"),
(239,"work","Work authored by Serfoji II","Devendra Kuravanji","இரண்டாம் சரபோஜி எழுதிய நூல்","தேவேந்திர குறவஞ்சி"),
(239,"work","Work authored by Serfoji II","Mudrarakshaschaya","இரண்டாம் சரபோஜி எழுதிய நூல்","முத்ராராக்ஷசச்சாயா"),
(239,"instrument","Western musical instrument introduced into Carnatic music by Serfoji II","Clarinet","இரண்டாம் சரபோஜி கர்நாடக இசையில் அறிமுகப்படுத்திய மேற்கத்திய கருவி","கிளாரினெட்"),
(239,"instrument","Western musical instrument introduced into Carnatic music by Serfoji II","Violin","இரண்டாம் சரபோஜி கர்நாடக இசையில் அறிமுகப்படுத்திய மேற்கத்திய கருவி","வயலின்"),
(239,"painting","Style of painting popularised by Serfoji II","Thanjavur style","இரண்டாம் சரபோஜி பிரபலப்படுத்திய ஓவிய பாணி","தஞ்சாவூர் பாணி"),
(239,"interest","One personal interest of Serfoji II","Coin-collecting","இரண்டாம் சரபோஜியின் தனிப்பட்ட ஆர்வங்களில் ஒன்று","நாணயச் சேகரிப்பு"),
(239,"interest","One personal interest of Serfoji II","Gardening","இரண்டாம் சரபோஜியின் தனிப்பட்ட ஆர்வங்களில் ஒன்று","தோட்டக்கலை"),
(239,"interest","One personal interest of Serfoji II","Martial arts","இரண்டாம் சரபோஜியின் தனிப்பட்ட ஆர்வங்களில் ஒன்று","போர்க்கலை"),
(239,"sport","One activity patronised by Serfoji II","Chariot-racing","இரண்டாம் சரபோஜி ஆதரித்த ஒரு விளையாட்டு","தேர்பந்தயம்"),
(239,"sport","One activity patronised by Serfoji II","Hunting","இரண்டாம் சரபோஜி ஆதரித்த ஒரு செயல்","வேட்டை"),
(239,"sport","One activity patronised by Serfoji II","Bull-fighting","இரண்டாம் சரபோஜி ஆதரித்த ஒரு விளையாட்டு","காளைச் சண்டை"),
(239,"achievement","Zoological initiative of Serfoji II","First zoological garden in Tamil Nadu","இரண்டாம் சரபோஜியின் விலங்கியல் சாதனை","தமிழ்நாட்டின் முதல் விலங்கியல் பூங்கா"),
(239,"place","Location of Serfoji II's zoological garden","Thanjavur palace premises","இரண்டாம் சரபோஜியின் விலங்கியல் பூங்கா அமைந்த இடம்","தஞ்சாவூர் அரண்மனை வளாகம்"),
(239,"date","Exact date of Serfoji II's death","7 March 1832","இரண்டாம் சரபோஜி இறந்த துல்லிய தேதி","7 மார்ச் 1832"),
(239,"duration","Approximate length of Serfoji II's rule","Almost forty years","இரண்டாம் சரபோஜியின் ஆட்சிக்காலத்தின் சுமார் நீளம்","கிட்டத்தட்ட நாற்பது ஆண்டுகள்"),
(239,"number","Approximate number attending Serfoji II's funeral procession","More than 90,000","இரண்டாம் சரபோஜியின் இறுதி ஊர்வலத்தில் கலந்து கொண்டோர்","90,000க்கும் மேல்"),
(239,"person","Churchman quoted praising Serfoji II's princely deportment","Rev. Bishop Heber","இரண்டாம் சரபோஜியின் அரச குணத்தைப் புகழ்ந்த சமயத் தலைவர்","ரெவ. பிஷப் ஹீபர்"),

# Glossary
(242,"term","Meaning of impregnable in the glossary","Indestructible","கலைச்சொல் பகுதியில் impregnable என்பதன் பொருள்","தகர்க்க முடியாத"),
(242,"term","Meaning of ravage in the glossary","Plunder","கலைச்சொல் பகுதியில் ravage என்பதன் பொருள்","சூறையாடு"),
(242,"term","Meaning of belligerent policy in the glossary","Policy of intense war force","கலைச்சொல் பகுதியில் belligerent policy என்பதன் பொருள்","தீவிரமாகப் போரிடும் கொள்கை"),
(242,"term","Meaning of relentless in the glossary","Unyielding","கலைச்சொல் பகுதியில் relentless என்பதன் பொருள்","விட்டுக்கொடுக்காத"),
(242,"term","Meaning of endorsement in the glossary","Approval","கலைச்சொல் பகுதியில் endorsement என்பதன் பொருள்","ஒப்புதல்"),
(242,"term","Meaning of breach in the glossary","Violate","கலைச்சொல் பகுதியில் breach என்பதன் பொருள்","மீறு"),
(242,"term","Meaning of solidarity in the glossary","Unity for causes","கலைச்சொல் பகுதியில் solidarity என்பதன் பொருள்","ஒற்றுமை"),
(242,"term","Meaning of pedagogy in the glossary","Teaching method","கலைச்சொல் பகுதியில் pedagogy என்பதன் பொருள்","கற்பிக்கும் கலை"),
]

def norm(s): return " ".join(str(s).split()).strip()

facts=[]; seen=set()
for row in F:
    p,k,de,ae,dt,at=row
    key=(norm(de).lower(),norm(ae).lower())
    if key in seen: continue
    seen.add(key)
    facts.append({"page_en":p,"kind":k,"desc_en":norm(de),"ans_en":norm(ae),"desc_ta":norm(dt),"ans_ta":norm(at)})

pools=defaultdict(list)
for f in facts: pools[f["kind"]].append(f)

def distractors(f,n=3):
    cand=[x for x in pools[f["kind"]] if x["ans_en"].lower()!=f["ans_en"].lower()]
    cand.sort(key=lambda x:(abs(x["page_en"]-f["page_en"]),x["ans_en"]))
    out=[]; used=set()
    for x in cand:
        a=x["ans_en"].lower()
        if a not in used:
            out.append(x); used.add(a)
        if len(out)==n: break
    if len(out)<n:
        for x in facts:
            a=x["ans_en"].lower()
            if a!=f["ans_en"].lower() and a not in used:
                out.append(x); used.add(a)
            if len(out)==n: break
    return out

def make_opts(f,seed):
    arr=[f]+distractors(f,3)
    random.Random(seed).shuffle(arr)
    return [x["ans_en"] for x in arr],[x["ans_ta"] for x in arr],arr.index(f)

questions=[]; qid=1
def add(page,qen,qta,oe,ot,c,een,eta,typ):
    global qid
    questions.append({
      "id":f"C11H15-Q{qid:04d}",
      "quiz":(qid-1)//20+1,
      "page_en":page,
      "q_en":qen,"q_ta":qta,
      "opts_en":oe,"opts_ta":ot,
      "correct":c,"exp_en":een,"exp_ta":eta,"type":typ
    })
    qid+=1

for i,f in enumerate(facts):
    een=f'{f["desc_en"]}: {f["ans_en"]}.'
    eta=f'{f["desc_ta"]}: {f["ans_ta"]}.'
    for j,(typ,pfx_en,pfx_ta) in enumerate([
      ("direct","What is the correct textbook answer for: ","இதற்கான சரியான பாடநூல் விடை எது: "),
      ("association","Which option is correctly associated with the following description: ","பின்வரும் விளக்கத்துடன் சரியாகப் பொருந்தும் விடை எது: "),
      ("recognition","Identify the term/person/place that the textbook links with this fact: ","இந்த பாடநூல் உண்மையுடன் தொடர்புடைய பெயர்/சொல்/இடத்தைத் தேர்ந்தெடுக்கவும்: ")
    ]):
        oe,ot,c=make_opts(f,15000+i*31+j*100003)
        add(f["page_en"],pfx_en+f["desc_en"]+"?",pfx_ta+f["desc_ta"]+"?",oe,ot,c,een,eta,typ)

comb_en=["Both I and II are correct","I is correct; II is incorrect","I is incorrect; II is correct","Both I and II are incorrect"]
comb_ta=["I மற்றும் II இரண்டும் சரி","I சரி; II தவறு","I தவறு; II சரி","I மற்றும் II இரண்டும் தவறு"]
for i,f in enumerate(facts):
    g=facts[(i+1)%len(facts)]
    mode=i%4
    iok=mode in (0,1); iiok=mode in (0,2)
    wf=distractors(f,1)[0]; wg=distractors(g,1)[0]
    a1=f["ans_en"] if iok else wf["ans_en"]; t1=f["ans_ta"] if iok else wf["ans_ta"]
    a2=g["ans_en"] if iiok else wg["ans_en"]; t2=g["ans_ta"] if iiok else wg["ans_ta"]
    qen=f'Consider the following statements:\nI. {f["desc_en"]} — {a1}.\nII. {g["desc_en"]} — {a2}.\nWhich option is correct?'
    qta=f'பின்வரும் கூற்றுகளைக் கவனிக்கவும்:\nI. {f["desc_ta"]} — {t1}.\nII. {g["desc_ta"]} — {t2}.\nசரியான விடை எது?'
    exen=["Both Statement I and Statement II are correct.","Statement I is correct and Statement II is incorrect.","Statement I is incorrect and Statement II is correct.","Both Statement I and Statement II are incorrect."][mode]
    exta=["கூற்று I மற்றும் II இரண்டும் சரி.","கூற்று I சரி; கூற்று II தவறு.","கூற்று I தவறு; கூற்று II சரி.","கூற்று I மற்றும் II இரண்டும் தவறு."][mode]
    add(max(f["page_en"],g["page_en"]),qen,qta,comb_en,comb_ta,mode,exen,exta,"statement-analysis")

# exact de-dupe then renumber
unique=[]; sigs=set()
for q in questions:
    s=(q["q_en"],tuple(q["opts_en"]))
    if s in sigs: continue
    sigs.add(s); unique.append(q)
questions=unique
for i,q in enumerate(questions,1):
    q["id"]=f"C11H15-Q{i:04d}"
    q["quiz"]=(i-1)//20+1

quiz_count=(len(questions)+19)//20
sets=[{"id":i,"title_en":f"Quiz {i} · Competitive Review","title_ta":f"வினாடி வினா {i} · போட்டித் தேர்வு மீள்பார்வை"} for i in range(1,quiz_count+1)]
counts=Counter("ABCD"[q["correct"]] for q in questions)
dups=len(questions)-len({(q["q_en"],tuple(q["opts_en"])) for q in questions})

out={"meta":{
  "board":"Tamil Nadu State Board","class":11,"subject":"History","edition":2025,"unit":15,
  "unit_en":"The Marathas","unit_ta":"மராத்தியர்கள்",
  "source":"Government of Tamil Nadu Higher Secondary First Year History, Revised Edition 2025, English and Tamil editions supplied by the user",
  "total_questions":len(questions),"base_facts":len(facts),"quiz_sets":sets,
  "question_style":"Maximum useful source-grounded bilingual competitive-exam coverage from Unit 15: causes of Maratha rise; Shivaji's early career, Mughal and Bijapur conflicts, coronation and southern campaigns; successors; Ashta Pradhan, revenue, military and justice; rise and expansion of the Peshwas; Third Battle of Panipat; Madhav Rao I; three Anglo-Maratha Wars; Peshwa administration, taxation, policing, judiciary, army and navy; Maratha rule in Tamil Nadu, Raja Desinghu and Serfoji II.",
  "quality_policy":"Four-option bilingual MCQs grounded in the supplied 2025 English and Tamil textbooks. Activities and assignments are excluded. Distinct textbook facts are reinforced through direct recall, association, recognition and statement-analysis formats.",
  "page_reference_note":"page_en refers to the printed English textbook page.",
  "qa_all_four_options":all(len(q["opts_en"])==4 and len(q["opts_ta"])==4 for q in questions),
  "qa_valid_correct_indexes":all(0<=q["correct"]<4 for q in questions),
  "qa_duplicate_ids":len(questions)-len({q["id"] for q in questions}),
  "qa_exact_duplicate_question_options":dups,
  "qa_answer_position_counts":dict(counts)
},"questions":questions}

os.makedirs(os.path.dirname(OUT),exist_ok=True)
with open(OUT,"w",encoding="utf-8") as fp:
    json.dump(out,fp,ensure_ascii=False,indent=2)
print(f"Wrote {OUT}: {len(facts)} facts, {len(questions)} questions, {quiz_count} quizzes")
