import json, random, os
from collections import defaultdict, Counter

OUT="data/textbook/class-11/history/unit-16.json"
random.seed(1602026)

# page_en, kind, description_en, answer_en, description_ta, answer_ta
F=[
# Introduction
(243,"date","Conventional starting year of British rule in India after Plassey","1757","பிளாசி போருக்குப் பின் இந்தியாவில் ஆங்கிலேய ஆட்சியின் வழக்கமான தொடக்க ஆண்டு","1757"),
(243,"battle","Battle conventionally associated with the beginning of British rule in India","Battle of Plassey","இந்தியாவில் ஆங்கிலேய ஆட்சியின் தொடக்கத்துடன் தொடர்புடைய போர்","பிளாசி போர்"),
(243,"company","Company that defeated the Nawab of Bengal at Plassey","English East India Company","பிளாசி போரில் வங்காள நவாபை தோற்கடித்த நிறுவனம்","ஆங்கில கிழக்கிந்தியக் கம்பெனி"),
(243,"period","Period by which Europeans had arrived in India","Beginning of the sixteenth century","ஐரோப்பியர்கள் இந்தியா வந்திருந்த காலம்","16ஆம் நூற்றாண்டின் தொடக்கம்"),
(243,"commodity","One spice Europeans originally sought in India","Pepper","ஐரோப்பியர்கள் இந்தியாவில் முதலில் தேடிய மசாலாப் பொருள்","மிளகு"),
(243,"commodity","One spice Europeans originally sought in India","Cinnamon","ஐரோப்பியர்கள் இந்தியாவில் முதலில் தேடிய மசாலாப் பொருள்","இலவங்கப்பட்டை"),
(243,"commodity","One spice Europeans originally sought in India","Cloves","ஐரோப்பியர்கள் இந்தியாவில் முதலில் தேடிய மசாலாப் பொருள்","கிராம்பு"),
(243,"nation","First Europeans to establish themselves in India","Portuguese","இந்தியாவில் முதலில் நிலைநிறுத்திக் கொண்ட ஐரோப்பியர்கள்","போர்த்துக்கீசியர்கள்"),
(243,"person","Navigator who discovered the direct sea route from Europe to India around the Cape of Good Hope","Vasco da Gama","கேப் ஆஃப் குட் ஹோப் வழியாக ஐரோப்பாவிலிருந்து இந்தியாவுக்கான நேரடி கடல்வழியை கண்டுபிடித்தவர்","வாஸ்கோ ட காமா"),
(243,"route","African cape used in the direct sea route to India","Cape of Good Hope","இந்தியாவிற்கான நேரடி கடல்வழியில் பயன்படுத்தப்பட்ட ஆப்பிரிக்க முனை","கேப் ஆஃப் குட் ஹோப்"),
(243,"date","Year the Portuguese conquered Goa","1510","போர்த்துக்கீசியர்கள் கோவாவை கைப்பற்றிய ஆண்டு","1510"),
(243,"place","Political headquarters of the Portuguese in India","Goa","இந்தியாவில் போர்த்துக்கீசியர்களின் அரசியல் தலைமையகம்","கோவா"),
(243,"place","One eastern centre linked to Portuguese headquarters at Goa","Malacca","கோவா போர்த்துக்கீசிய தலைமையகத்துடன் தொடர்புடைய கிழக்குப் பகுதி","மலாக்கா"),
(243,"place","Another eastern centre linked to Portuguese headquarters at Goa","Java","கோவா போர்த்துக்கீசிய தலைமையகத்துடன் தொடர்புடைய மற்றொரு கிழக்குப் பகுதி","ஜாவா"),
(243,"method","Basis of Portuguese control of Indian Ocean trade","Political aggressiveness and naval superiority","இந்தியப் பெருங்கடல் வாணிபத்தை போர்த்துக்கீசியர்கள் கட்டுப்படுத்திய அடிப்படை","அரசியல் தாக்குதலும் கடற்படை மேலாதிக்கமும்"),
(243,"fort","Portuguese fort helping control Arabian Sea shipping","Daman","அரபிக்கடல் கப்பல் போக்குவரத்தை கட்டுப்படுத்த உதவிய போர்த்துக்கீசியக் கோட்டை","டாமன்"),
(243,"fort","Portuguese fort helping control Arabian Sea shipping","Diu","அரபிக்கடல் கப்பல் போக்குவரத்தை கட்டுப்படுத்த உதவிய போர்த்துக்கீசியக் கோட்டை","டையூ"),
(243,"nation","European nation that modelled activities on the Portuguese blueprint","Dutch","போர்த்துக்கீசிய மாதிரியைப் பின்பற்றிய ஐரோப்பிய நாடு","டச்சுக்காரர்கள்"),
(243,"nation","Another European nation that modelled activities on the Portuguese blueprint","English","போர்த்துக்கீசிய மாதிரியைப் பின்பற்றிய மற்றொரு ஐரோப்பிய நாடு","ஆங்கிலேயர்கள்"),
(243,"result","Process culminating in British conquest of Bengal","Engagement of European trading companies with Indian rulers, merchants and society","வங்காளத்தை ஆங்கிலேயர் கைப்பற்றுவதில் முடிந்த செயல்முறை","இந்திய அரசர்கள், வணிகர்கள், சமூகத்துடன் ஐரோப்பிய வணிக நிறுவனங்களின் தொடர்ந்த தொடர்பு"),

# Mughal political situation 1600-1650
(244,"period","Period when the Mughal Empire was at the peak of its power in this chapter","1600–1650","இந்த அத்தியாயத்தில் முகலாயப் பேரரசு உச்சத்தில் இருந்த காலம்","1600–1650"),
(244,"source","Source providing contemporary accounts of Mughal India by European visitors","Travel journals","ஐரோப்பிய பயணிகள் முகலாய இந்தியாவைப் பற்றிய சமகாலத் தகவல்களை வழங்கிய ஆதாரம்","பயணக் குறிப்புகள்"),
(244,"ruler","Mughal ruler who had achieved his imperial dream by 1600","Akbar","1600க்குள் தனது பேரரசு கனவை அடைந்த முகலாய அரசர்","அக்பர்"),
(244,"region","Western region conquered by Akbar in 1573","Gujarat","1573இல் அக்பர் கைப்பற்றிய மேற்குப் பகுதி","குஜராத்"),
(244,"date","Year Akbar conquered Gujarat","1573","அக்பர் குஜராத்தை கைப்பற்றிய ஆண்டு","1573"),
(244,"port","Port giving the Mughals access to West Asia and Europe","Surat","முகலாயருக்கு மேற்கு ஆசியா மற்றும் ஐரோப்பாவுடன் அணுகலை வழங்கிய துறைமுகம்","சூரத்"),
(244,"function","Religious travel function of Surat","Departure point for pilgrim ships to Mecca","சூரத்தின் சமயப் பயணப் பங்கு","மக்கா யாத்திரைக் கப்பல்கள் புறப்படும் இடம்"),
(244,"number","Number of governors at Surat under the Mughals","Two","முகலாய கால சூரத்தில் இருந்த ஆளுநர்கள் எண்ணிக்கை","இரண்டு"),
(244,"office","One Surat governor's responsibility","Civilian affairs and customs revenue","சூரத் நகர ஆளுநரின் முக்கிய பொறுப்பு","பொது நிர்வாகமும் சுங்க வருவாயும்"),
(244,"river","River beside which the Surat castle was built","Tapti","சூரத் கோட்டை கட்டப்பட்ட ஆற்றின் பெயர்","தப்தி"),
(244,"region","Eastern region Akbar tried to bring under firm Mughal control","Bengal","அக்பர் முகலாய ஆட்சிக்குள் கொண்டு வர முயன்ற கிழக்குப் பகுதி","வங்காளம்"),
(244,"ruler","Mughal ruler under whom Bengal became a subah integrated into the empire","Jahangir","வங்காளம் சுபாவாக முகலாயப் பேரரசில் ஒருங்கிணைக்கப்பட்ட அரசர்","ஜஹாங்கீர்"),
(244,"person","Revenue administrator who revamped Akbar's revenue system","Todar Mal","அக்பரின் வருவாய் முறையை மறுசீரமைத்த நிர்வாகி","தோடர்மால்"),
(244,"nation","European traders who arrived at Surat before the English in the early 1600s","Dutch","1600களின் தொடக்கத்தில் ஆங்கிலேயருக்கு முன் சூரத் வந்த ஐரோப்பிய வணிகர்கள்","டச்சுக்காரர்கள்"),
(244,"term","Name used for European business premises that also functioned as warehouses","Factories","கிடங்குகளாகவும் செயல்பட்ட ஐரோப்பிய வணிக நிலையங்களின் பெயர்","ஃபாக்டரிகள்"),
(244,"restriction","Territorial restriction placed on Dutch and English at Surat","No territorial authority over the city","சூரத்தில் டச்சு, ஆங்கிலேயருக்கு விதிக்கப்பட்ட நில உரிமைத் தடை","நகரின் எந்தப் பகுதியிலும் அரசியல் நில அதிகாரம் இல்லை"),
(244,"date","Year the English acquired Bombay islands","1668","ஆங்கிலேயர்கள் பம்பாய் தீவுகளைப் பெற்ற ஆண்டு","1668"),
(244,"date","Year Bombay became English headquarters","1687","பம்பாய் ஆங்கிலேய தலைமையகமான ஆண்டு","1687"),
(244,"objective","English objective in developing Bombay","Alternate base for operations","பம்பாயை வளர்த்த ஆங்கிலேய நோக்கம்","மாற்று செயல்பாட்டு தளம்"),
(244,"port","Commercial centre still preferred under Mughal protection despite Bombay","Surat","பம்பாய் இருந்தபோதும் முகலாய பாதுகாப்பில் வணிகர்கள் விரும்பிய மையம்","சூரத்"),

# South India 1600-1650
(244,"region","Area presenting a contrast to Mughal central stability","South India, especially Tamil region","முகலாய மையநிலைத்தன்மைக்கு மாறுபட்ட பகுதி","தென்னிந்தியா, குறிப்பாக தமிழகம்"),
(244,"kingdom","One Nayak kingdom in the Tamil region","Madurai","தமிழகத்தின் நாயக்க அரசுகளில் ஒன்று","மதுரை"),
(244,"kingdom","One Nayak kingdom in the Tamil region","Thanjavur","தமிழகத்தின் நாயக்க அரசுகளில் ஒன்று","தஞ்சாவூர்"),
(244,"kingdom","One Nayak kingdom in the Tamil region","Senji","தமிழகத்தின் நாயக்க அரசுகளில் ஒன்று","செஞ்சி"),
(244,"battle","Battle whose outcome weakened Vijayanagar central authority","Battle of Talikota","விஜயநகர மைய அதிகாரத்தை பலவீனப்படுத்திய போர்","தாலிகோட்டா போர்"),
(244,"date","Year of the Battle of Talikota","1565","தாலிகோட்டா போரின் ஆண்டு","1565"),
(244,"state","One Deccan state whose forces defeated Vijayanagar at Talikota","Ahmednagar","தாலிகோட்டாவில் விஜயநகரத்தை தோற்கடித்த தக்காண அரசுகளில் ஒன்று","அகமதுநகர்"),
(244,"state","One Deccan state whose forces defeated Vijayanagar at Talikota","Bijapur","தாலிகோட்டாவில் விஜயநகரத்தை தோற்கடித்த தக்காண அரசுகளில் ஒன்று","பிஜாப்பூர்"),
(244,"state","One Deccan state whose forces defeated Vijayanagar at Talikota","Golkonda","தாலிகோட்டாவில் விஜயநகரத்தை தோற்கடித்த தக்காண அரசுகளில் ஒன்று","கோல்கொண்டா"),
(245,"chief","Notable local chief who asserted independence in Ramanathapuram","Setupati","ராமநாதபுரத்தில் சுதந்திரத்தை வலியுறுத்திய குறிப்பிடத்தக்க உள்ளூர் தலைவர்","சேதுபதி"),
(245,"period","Period of repeated political conflicts in the Tamil region","1590–1649","தமிழகத்தில் பல அரசியல் மோதல்கள் நடந்த காலம்","1590–1649"),
(245,"rivals","Two Nayak kingdoms that repeatedly fought for superiority","Madurai and Thanjavur","மேலாதிக்கத்திற்காக மீண்டும் மீண்டும் போரிட்ட நாயக்க அரசுகள்","மதுரை மற்றும் தஞ்சாவூர்"),
(245,"date","Year Golkonda invaded the Coromandel","1646","கோல்கொண்டா கொரோமண்டலை ஆக்கிரமித்த ஆண்டு","1646"),
(245,"extent","Area annexed by Golkonda in 1646","Between Pulicat and San Thome","1646இல் கோல்கொண்டா இணைத்த பகுதி","பழவேற்காடு மற்றும் சாந்தோம் இடைப்பட்ட பகுதி"),
(245,"need","Commercial reason Europeans needed a Coromandel base","To procure piece goods for trade with Indonesian spice islands","கொரோமண்டல் தளம் தேவைப்பட்ட ஐரோப்பியர்களின் வணிகக் காரணம்","இந்தோனேசிய மசாலா தீவுகளுடன் வாணிபத்திற்கு துணிகளைப் பெறுதல்"),
(245,"place","Dutch settlement acquired from the Nayak of Senji","Pulicat (Pazhaverkadu)","செஞ்சி நாயக்கரிடமிருந்து டச்சுக்காரர்கள் பெற்ற குடியேற்றம்","பழவேற்காடு"),
(245,"fort","Fort built by the Dutch at Pulicat","Castle Geldria","பழவேற்காட்டில் டச்சுக்காரர்கள் கட்டிய கோட்டை","காஸில் கெல்ட்ரியா"),
(245,"person","Local chief who granted land to the English for Fort St. George","Damarla Venkatadri Nayak","செயின்ட் ஜார்ஜ் கோட்டை கட்ட ஆங்கிலேயருக்கு நிலம் வழங்கிய உள்ளூர் தலைவர்","தாமர்லா வெங்கடாத்ரி நாயக்"),
(245,"fort","English fort built in 1639","Fort St. George","1639இல் ஆங்கிலேயர்கள் கட்டிய கோட்டை","செயின்ட் ஜார்ஜ் கோட்டை"),
(245,"date","Year Fort St. George was built","1639","செயின்ட் ஜார்ஜ் கோட்டை கட்டப்பட்ட ஆண்டு","1639"),
(245,"city","City that grew from the English settlement around Fort St. George","Chennai (Madras)","செயின்ட் ஜார்ஜ் கோட்டையைச் சுற்றிய ஆங்கிலேய குடியேற்றத்திலிருந்து வளர்ந்த நகரம்","சென்னை (மதராஸ்)"),
(245,"presidency","Colonial presidency for which Chennai became capital","Madras Presidency","சென்னை தலைநகராக இருந்த காலனித்துவ மாகாணம்","மதராஸ் பிரெசிடென்சி"),

# 1650-1750 political changes
(245,"ruler","Mughal emperor who pursued major Deccan expansion","Aurangzeb","தக்காண விரிவாக்கத்தை தீவிரமாக முன்னெடுத்த முகலாய பேரரசர்","ஔரங்கசீப்"),
(245,"period","Decade in which Ahmednagar, Bijapur and Golkonda were conquered by Aurangzeb","1680s","ஔரங்கசீப் அகமதுநகர், பிஜாப்பூர், கோல்கொண்டாவை கைப்பற்றிய காலம்","1680கள்"),
(245,"city","Southern extent to which Mughal control reached under Aurangzeb","Chennai","ஔரங்கசீப் கால முகலாய கட்டுப்பாடு தெற்கில் சென்றடைந்த இடம்","சென்னை"),
(245,"person","Maratha leader whose rise exposed Mughal weakness","Shivaji","முகலாய பலவீனத்தை வெளிப்படுத்திய மராத்திய தலைவர்","சிவாஜி"),
(245,"date","Year Shivaji first attacked Surat","1664","சிவாஜி முதன்முதலில் சூரத்தைத் தாக்கிய ஆண்டு","1664"),
(245,"date","Year Shivaji's second raid devastated Surat","1670","சிவாஜியின் இரண்டாம் சூரத் தாக்குதல் நடந்த ஆண்டு","1670"),
(245,"result","Effect of Shivaji's second Surat raid","Trade took several years to recover","சிவாஜியின் இரண்டாம் சூரத் தாக்குதலின் விளைவு","வாணிபம் மீள பல ஆண்டுகள் பிடித்தது"),
(245,"state","Tamil Nayak state conquered by Shivaji but later taken by Mughals","Senji","சிவாஜி கைப்பற்றிய பின் முகலாயரால் கைப்பற்றப்பட்ட தமிழ்நாட்டு நாயக்க அரசு","செஞ்சி"),
(245,"state","Tamil Nayak state that survived as Maratha-ruled state","Thanjavur","மராத்திய ஆட்சியில் தொடர்ந்த தமிழ்நாட்டு நாயக்க அரசு","தஞ்சாவூர்"),
(245,"role","Cultural role of Maratha Thanjavur","Cultural capital of the Tamil region","மராத்திய தஞ்சாவூரின் பண்பாட்டு பங்கு","தமிழகத்தின் பண்பாட்டு தலைநகரம்"),
(245,"date","Year Aurangzeb died","1707","ஔரங்கசீப் இறந்த ஆண்டு","1707"),
(245,"term","Name given to states formed by former Mughal viceroys after Aurangzeb","Successor states","ஔரங்கசீப்புக்குப் பின் முன்னாள் முகலாய வைஸ்ராய்கள் உருவாக்கிய அரசுகளின் பெயர்","வாரிசு அரசுகள்"),
(245,"state","One successor state after Mughal decline","Oudh","முகலாய வீழ்ச்சிக்குப் பின் உருவான வாரிசு அரசு","அவத்"),
(245,"state","One successor state after Mughal decline","Bengal","முகலாய வீழ்ச்சிக்குப் பின் உருவான வாரிசு அரசு","வங்காளம்"),
(245,"state","One successor state after Mughal decline","Hyderabad","முகலாய வீழ்ச்சிக்குப் பின் உருவான வாரிசு அரசு","ஹைதராபாத்"),
(245,"state","One successor state after Mughal decline","Carnatic","முகலாய வீழ்ச்சிக்குப் பின் உருவான வாரிசு அரசு","கர்நாடகம்"),
(245,"process","Early step toward British rule arising from Nawab debts","Assignment of land for English revenue collection","நவாப்களின் கடனால் ஆங்கிலேய ஆட்சிக்கான ஆரம்ப படி","ஆங்கிலேயருக்கு நிலவருவாய் வசூலிக்க நிலங்கள் ஒதுக்கப்பட்டமை"),
(245,"meaning","Original meaning of the name Carnatic","Region occupied by Kannada-speaking people","கர்நாடகம் என்ற பெயரின் ஆரம்பப் பொருள்","கன்னட மொழி பேசும் மக்கள் வாழ்ந்த பகுதி"),
(245,"extent","Eighteenth-century Carnatic location","Between Eastern and Western Ghats","18ஆம் நூற்றாண்டு கர்நாடகத்தின் நில அமைவு","கிழக்கு மற்றும் மேற்கு தொடர்ச்சி மலைகள் இடையே"),
(245,"ruler","Ruler controlling the Carnatic region","Nawab of Arcot","கர்நாடகப் பகுதியை கட்டுப்படுத்திய ஆட்சியாளர்","ஆர்க்காடு நவாப்"),
(246,"movement","Dutch headquarters shifted from Pulicat to","Nagapattinam","டச்சு தலைமையகம் பழவேற்காட்டிலிருந்து மாற்றப்பட்ட இடம்","நாகப்பட்டினம்"),
(246,"focus","Region to which Dutch shifted strategic focus","Indonesian spice-producing islands","டச்சுக்காரர்கள் தங்கள் முக்கிய கவனத்தை மாற்றிய பகுதி","இந்தோனேசிய மசாலா தீவுகள்"),
(246,"capital","Dutch capital in Indonesia","Jakarta (Batavia)","இந்தோனேசியாவில் டச்சு தலைநகரம்","ஜகார்த்தா (படேவியா)"),
(246,"city","English town that grew prosperous on Coromandel coast","Chennai","கொரோமண்டல் கடற்கரையில் வளர்ந்த ஆங்கில நகரம்","சென்னை"),
(246,"date","Approximate year by which Surat merchants sought Dutch or English protection","1750","சூரத் வணிகர்கள் டச்சு அல்லது ஆங்கில பாதுகாப்பை நாடத் தொடங்கிய சுமார் ஆண்டு","1750"),
(246,"port","Port that became viable alternative to Surat","Bombay","சூரத்துக்கு மாற்றாக முக்கிய வாணிப மையமான துறைமுகம்","பம்பாய்"),

# Economy
(246,"economy","Primary character of India's economy","Agricultural economy","இந்திய பொருளாதாரத்தின் அடிப்படை தன்மை","வேளாண் பொருளாதாரம்"),
(246,"crop","One commercial crop widely grown","Sugarcane","பெருமளவில் பயிரிடப்பட்ட வணிகப் பயிர்","கரும்பு"),
(246,"crop","One commercial crop widely grown","Oil seeds","பெருமளவில் பயிரிடப்பட்ட வணிகப் பயிர்","எண்ணெய் விதைகள்"),
(246,"crop","One commercial crop widely grown","Cotton","பெருமளவில் பயிரிடப்பட்ட வணிகப் பயிர்","பருத்தி"),
(246,"crop","One commercial crop widely grown","Indigo","பெருமளவில் பயிரிடப்பட்ட வணிகப் பயிர்","அவுரி"),
(246,"trade","Important internal trade product","Food grains","இந்திய உள்நாட்டு வாணிபத்தின் முக்கிய பொருள்","தானியங்கள்"),
(246,"trade","Important internal trade product","Ghee","இந்திய உள்நாட்டு வாணிபத்தின் முக்கிய பொருள்","நெய்"),
(246,"trade","Important internal trade product","Sugar","இந்திய உள்நாட்டு வாணிபத்தின் முக்கிய பொருள்","சர்க்கரை"),
(246,"route","Region supplying food grains to Tamil country","Andhra region and Bengal","தமிழகத்திற்கு தானியங்கள் வழங்கிய பகுதிகள்","ஆந்திரப் பகுதி மற்றும் வங்காளம்"),
(246,"route","West-coast region exporting food grains to Malabar","Gujarat","மலபாருக்கு தானியங்கள் ஏற்றுமதி செய்த மேற்குக் கடற்கரை பகுதி","குஜராத்"),
(246,"commodity","Commodity received by Gujarat in return from Malabar","Pepper","மலபாரிலிருந்து குஜராத் பெற்ற பரிமாற்றப் பொருள்","மிளகு"),
(246,"commodity","Commodity received by Gujarat in return from Malabar","Cinnamon","மலபாரிலிருந்து குஜராத் பெற்ற பரிமாற்றப் பொருள்","இலவங்கப்பட்டை"),
(246,"commodity","Commodity received by Gujarat in return from Malabar","Ginger","மலபாரிலிருந்து குஜராத் பெற்ற பரிமாற்றப் பொருள்","இஞ்சி"),
(246,"destination","Dutch overseas destination receiving Indian food grains","Sri Lanka","இந்திய தானியங்கள் சென்ற டச்சு வெளிநாட்டு இலக்கு","இலங்கை"),
(246,"destination","Another Dutch overseas destination receiving Indian food grains","Batavia","இந்திய தானியங்கள் சென்ற மற்றொரு டச்சு வெளிநாட்டு இலக்கு","படேவியா"),
(246,"industry","Second most important economic activity in India","Weaving","இந்தியாவின் இரண்டாவது முக்கிய பொருளாதாரச் செயல்","நெசவு"),
(246,"activity","Subsidiary activity supporting weaving","Spinning","நெசவுக்கு துணையான தொழில்","நூல் நூற்பு"),
(246,"activity","Subsidiary activity supporting weaving","Dyeing","நெசவுக்கு துணையான தொழில்","சாயமிடுதல்"),
(246,"location","Primary location of luxury crafts like metalwork","Urban areas","உலோக வேலை போன்ற ஆடம்பரக் கைவினைகளின் முக்கிய இடம்","நகரப் பகுதிகள்"),
(246,"location","Primary location of weaving","Rural areas","நெசவின் முக்கிய உற்பத்தி இடம்","கிராமப்புறங்கள்"),
(246,"chemical","Chemical used by Indian dyers to produce permanent colour","Alum","நிலையான நிறம் உருவாக்க இந்திய சாயக்காரர்கள் பயன்படுத்திய வேதிப்பொருள்","படிகாரம்"),
(246,"fabric","Painted fabric for which Coromandel was famous","Kalamkari","கொரோமண்டல் புகழ்பெற்ற வர்ணப்பட்ட துணி","கலம்காரி"),
(246,"market","Major sixteenth-century overseas market for Coromandel painted fabrics","Indonesian islands","கொரோமண்டல் வர்ணப்பட்ட துணிகளின் முக்கிய 16ஆம் நூற்றாண்டு வெளிநாட்டு சந்தை","இந்தோனேசிய தீவுகள்"),
(246,"export","Most important Indian export to the world","Cotton fabrics","உலகிற்கு இந்தியாவின் மிக முக்கிய ஏற்றுமதி","பருத்தித் துணிகள்"),
(246,"period","Period through which cotton remained a major export","Well into the eighteenth century","பருத்தித் துணி முக்கிய ஏற்றுமதியாகத் தொடர்ந்த காலம்","18ஆம் நூற்றாண்டின் பெரும்பகுதி வரை"),

# Marketing and merchants
(246,"concept","Economic condition caused by widespread production for external markets","Commercialization beyond subsistence","வெளிச் சந்தைக்கான பரவலான உற்பத்தியால் ஏற்பட்ட பொருளாதார நிலை","சுயநிறைவைத் தாண்டிய வாணிபமயமாக்கல்"),
(246,"class","Group linking rural producers with urban and external markets","Merchants","கிராம உற்பத்தியாளர்களை நகர மற்றும் வெளிச் சந்தைகளுடன் இணைத்தவர்கள்","வணிகர்கள்"),
(246,"network","Lowest level of extensive market circuits","Village markets","வாணிப வலையமைப்பின் அடிப்படை நிலை","கிராமச் சந்தைகள்"),
(246,"network","Highest domestic-commercial level before overseas gateways","Large urban commercial centres","வெளிநாட்டு வாயில்களுக்கு முன் உள்ள பெரிய உள்நாட்டு வணிக மையங்கள்","பெரிய நகர வணிக மையங்கள்"),
(246,"network","Gateways to markets outside India","Ports","இந்தியாவுக்கு வெளியான சந்தைகளுக்கான வாயில்கள்","துறைமுகங்கள்"),
(247,"class","Base of the merchant pyramid","Traders and retailers serving smaller centres","வணிகர் பிரமிடின் அடித்தளம்","சிறு மையங்களைச் சேவித்த வியாபாரிகள் மற்றும் சில்லறை வணிகர்கள்"),
(247,"class","Top of the merchant pyramid","Great merchants engaged in overseas trade","வணிகர் பிரமிடின் உச்சி","வெளிநாட்டு வாணிபத்தில் ஈடுபட்ட பெரிய வணிகர்கள்"),
(247,"agents","Middle tier connecting great merchants and hinterland producers","Brokers and sub-brokers","பெரிய வணிகர்களையும் உள்நாட்டு உற்பத்தியாளர்களையும் இணைத்த நடுத்தர அடுக்கு","தரகர்கள் மற்றும் துணைத் தரகர்கள்"),
(247,"term","Money-changers who tested coin purity and acted as bankers","Shroffs","நாணயத் தூய்மையைச் சோதித்து வங்கியாளர்களாக செயல்பட்டவர்கள்","ஷ்ராஃப்கள்"),
(247,"term","Bills of exchange used by merchants","Hundis","வணிகர்கள் பயன்படுத்திய பரிமாற்றக் கடிதங்கள்","ஹுண்டிகள்"),
(247,"function","Purpose of hundis","Transfer money without moving cash physically","ஹுண்டிகளின் முக்கிய நோக்கம்","பணத்தை நேரடியாக எடுத்துச் செல்லாமல் பரிமாறுதல்"),
(247,"merchant","Merchant community of Surat","Banias","சூரத்தின் வணிகக் குழு","பனியாக்கள்"),
(247,"merchant","Another merchant community of Surat","Parsi merchants","சூரத்தின் மற்றொரு வணிகக் குழு","பார்சி வணிகர்கள்"),
(247,"merchant","Leading merchant title/community of Ahmedabad","Nagarseths","அகமதாபாத்தின் முக்கிய வணிகத் தலைவர்கள்","நகர்சேத்துகள்"),
(247,"merchant","Powerful banking-merchant family of Bengal","Jagat Seths","வங்காளத்தின் சக்திவாய்ந்த வங்கியாளர்-வணிகர் குடும்பம்","ஜகத் சேத்துகள்"),
(247,"observation","Condition of weavers and peasants noted by European observers","Pitifully poor","ஐரோப்பிய பார்வையாளர்கள் குறிப்பிட்ட நெசவாளர்கள் மற்றும் விவசாயிகளின் நிலை","மிகவும் வறுமையானது"),
(247,"period","Number of famines in Madras region between 1678 and 1750","At least ten","1678–1750 இடையே மதராஸ் பகுதியில் ஏற்பட்ட பஞ்சங்கள்","குறைந்தது பத்து"),
(247,"result","Extreme result of famine for rural poor","Selling themselves into slavery","பஞ்சத்தால் கிராம ஏழைகளுக்கு ஏற்பட்ட மிகக் கடுமையான விளைவு","தங்களை அடிமைகளாக விற்றல்"),
(247,"source","European records frequently mentioning slaves shipped to Batavia","Dutch records from Coromandel","படேவியாவுக்கு அனுப்பப்பட்ட அடிமைகளை அடிக்கடி குறிப்பிடும் ஐரோப்பிய பதிவுகள்","கொரோமண்டல் டச்சு பதிவுகள்"),

# Overseas trade
(247,"system","Trade system into which east and west coast commerce was incorporated","Indian Ocean trade","கிழக்கு, மேற்கு கடற்கரை வாணிபம் இணைக்கப்பட்ட பெரிய வாணிப அமைப்பு","இந்தியப் பெருங்கடல் வாணிபம்"),
(247,"period","Century by which Indian Ocean trade had stabilized into a well-set pattern","Sixteenth century","இந்தியப் பெருங்கடல் வாணிபம் நிலையான வடிவம் பெற்ற நூற்றாண்டு","16ஆம் நூற்றாண்டு"),
(247,"place","Entrepot receiving ships from China and Far East","Malacca","சீனா மற்றும் தூர கிழக்கிலிருந்து கப்பல்கள் வந்த இடைநிலைத் துறைமுகம்","மலாக்கா"),
(247,"term","Name for intermediate ports in overseas trade","Entrepots","வெளிநாட்டு வாணிபத்தின் இடைநிலைத் துறைமுகங்களின் பெயர்","என்ட்ரெபோ துறைமுகங்கள்"),
(247,"port","West-coast entrepot that gradually declined relative to Gujarat ports","Calicut","குஜராத் துறைமுகங்களை ஒப்பிடும் போது வீழ்ச்சியடைந்த மேற்குக் கடற்கரை இடைநிலைத் துறைமுகம்","காலிக்கட்"),
(247,"port","Gujarat port serving as major entrepot","Cambay","குஜராத்தின் முக்கிய இடைநிலைத் துறைமுகம்","காம்பே"),
(247,"port","Another Gujarat entrepot","Surat","குஜராத்தின் மற்றொரு இடைநிலைத் துறைமுகம்","சூரத்"),
(247,"export","One locally produced item exchanged at entrepots","Pepper","இடைநிலைத் துறைமுகங்களில் பரிமாறப்பட்ட உள்ளூர் பொருள்","மிளகு"),
(247,"export","One locally produced item exchanged at entrepots","Spices","இடைநிலைத் துறைமுகங்களில் பரிமாறப்பட்ட உள்ளூர் பொருள்","மசாலா"),
(247,"export","One locally produced item exchanged at entrepots","Dyes","இடைநிலைத் துறைமுகங்களில் பரிமாறப்பட்ட உள்ளூர் பொருள்","சாயங்கள்"),
(247,"export","One locally produced item exchanged at entrepots","Clothes","இடைநிலைத் துறைமுகங்களில் பரிமாறப்பட்ட உள்ளூர் பொருள்","துணிகள்"),
(247,"port","Coromandel port serving ships from Burma and Malay peninsula","Masulipatnam","பர்மா மற்றும் மலாய் தீபகற்பக் கப்பல்களுக்கு சேவை செய்த கொரோமண்டல் துறைமுகம்","மசூலிப்பட்டினம்"),
(247,"port","Another Coromandel intermediate port","Pulicat","கொரோமண்டல் கடற்கரையின் மற்றொரு இடைநிலைத் துறைமுகம்","பழவேற்காடு"),

# European trade logic and merchant collaboration
(247,"shock","First major external shock to established Indian Ocean trade","Arrival of Europeans beginning with Portuguese","இந்தியப் பெருங்கடல் வாணிபத்திற்கு ஏற்பட்ட முதல் பெரிய வெளிப்புற அதிர்ச்சி","போர்த்துக்கீசியர்களுடன் தொடங்கிய ஐரோப்பியர் வருகை"),
(247,"objective","Primary commercial interest of Europeans in Asia","Secure spices directly for Europe","ஆசியாவில் ஐரோப்பியர்களின் முதன்மை வணிக நோக்கம்","ஐரோப்பாவுக்காக மசாலாப் பொருட்களை நேரடியாகப் பெறுதல்"),
(247,"old_route","Old route by which spices reached Mediterranean","Persian Gulf ports and overland routes","மசாலாப் பொருட்கள் மத்தியதரைக்கடலை அடைந்த பழைய வழி","பாரசீக வளைகுடா துறைமுகங்களும் நிலவழியும்"),
(247,"problem","Why simple bilateral exchange with Asia did not work for Europeans","Little demand for European products except gold and silver","ஆசியாவுடன் நேரடி இருதரப்பு வாணிபம் ஏன் இயங்கவில்லை","தங்கம், வெள்ளியைத் தவிர ஐரோப்பியப் பொருட்களுக்கு குறைந்த தேவை"),
(247,"medium","Commodity that served as substitute medium of exchange in Southeast Asia","Indian textiles","தென்கிழக்காசிய வாணிபத்தில் மாற்றுப் பரிமாற்ற ஊடகமாக இருந்த பொருள்","இந்திய துணிகள்"),
(247,"region","Indian textile region whose painted fabrics were highly demanded in Indonesia","Coromandel coast","இந்தோனேசியாவில் அதிக தேவை பெற்ற வர்ணப்பட்ட துணிகளின் இந்தியப் பகுதி","கொரோமண்டல் கடற்கரை"),
(248,"strategy","Reason Europeans collaborated with leading Indian merchants","They needed local merchant help to succeed","ஐரோப்பியர்கள் இந்திய வணிகர்களுடன் ஒத்துழைத்த காரணம்","வெற்றி பெற உள்ளூர் வணிகர் உதவி தேவைப்பட்டது"),
(248,"benefit","Why Indian merchants collaborated with Europeans","New business opportunities for expansion","இந்திய வணிகர்கள் ஐரோப்பியர்களுடன் ஒத்துழைத்த காரணம்","வாணிப விரிவாக்கத்திற்கான புதிய வாய்ப்புகள்"),
(248,"security","Protection supporting merchants in Surat","Mughal government","சூரத் வணிகர்களுக்கு பாதுகாப்பளித்த அரசு","முகலாய அரசு"),
(248,"enclave","Tamil colonial enclave offering merchant security under English","Chennai","ஆங்கிலேயரின் கீழ் வணிகர்களுக்கு பாதுகாப்பளித்த தமிழகக் குடியேற்றம்","சென்னை"),
(248,"enclave","French colonial enclave offering merchant security","Pondicherry","பிரெஞ்சு ஆட்சியில் வணிகர்களுக்கு பாதுகாப்பளித்த குடியேற்றம்","புதுச்சேரி"),
(248,"period","Approximate time until which Indian merchants were not disadvantaged in dealings with Europeans","About 1700","ஐரோப்பியர்களுடனான வாணிபத்தில் இந்திய வணிகர்கள் பாதிக்கப்படாத சுமார் காலம் வரை","1700 வரை"),
(248,"cause","Reason English power over Surat merchants increased","Maratha threat and Mughal inability to provide security","சூரத் வணிகர்களின் மீது ஆங்கிலேய சக்தி அதிகரித்த காரணம்","மராத்திய அச்சுறுத்தலும் முகலாய பாதுகாப்பின் பலவீனமும்"),
(248,"pressure","English pressure on Chennai merchants","Accept unviable terms to increase cloth exports","சென்னை வணிகர்கள்மீது ஆங்கிலேயர் செலுத்திய அழுத்தம்","துணி ஏற்றுமதியை உயர்த்த சாதகமற்ற நிபந்தனைகளை ஏற்கச் செய்தல்"),
(248,"short_term","Short-term effect of growing European textile demand","Benefited local economy","ஐரோப்பிய துணித் தேவையின் குறுகியகால விளைவு","உள்ளூர் பொருளாதாரத்திற்கு நன்மை"),
(248,"long_term","Long-term effect of rapidly growing European textile demand","Strained productive resources","ஐரோப்பிய துணித் தேவையின் நீண்டகால விளைவு","உற்பத்தி வளங்களுக்கு அதிக அழுத்தம்"),
(248,"burden","One extra burden on weavers in the south","Frequent famines","தென்னக நெசவாளர்களின் கூடுதல் சுமை","அடிக்கடி ஏற்பட்ட பஞ்சங்கள்"),
(248,"burden","Another extra burden on weavers","Shortage of food grains and raw materials","நெசவாளர்களின் மற்றொரு சுமை","தானிய மற்றும் மூலப்பொருள் பற்றாக்குறை"),
(248,"metamorphosis","Long-term transformation of English in India","From traders to builders of a trading empire and rulers","இந்தியாவில் ஆங்கிலேயரின் நீண்டகால மாற்றம்","வணிகர்களிலிருந்து வாணிபப் பேரரசு கட்டியவர்களாகவும் ஆட்சியாளர்களாகவும் மாறுதல்"),

# Portuguese
(248,"number","Number of men with Vasco da Gama on first voyage","170","வாஸ்கோ ட காமாவின் முதல் பயணத்தில் இருந்த ஆட்கள் எண்ணிக்கை","170"),
(248,"number","Number of vessels in Vasco da Gama's first voyage","Three","வாஸ்கோ ட காமாவின் முதல் பயணக் கப்பல்கள் எண்ணிக்கை","மூன்று"),
(248,"ruler","Ruler of Calicut who received Vasco da Gama cordially","Zamorin","வாஸ்கோ ட காமாவை அன்புடன் வரவேற்ற காலிக்கட் அரசர்","சாமூதிரி"),
(248,"date","Date Vasco da Gama began return journey from first voyage","29 August 1498","வாஸ்கோ ட காமா முதல் பயணத்திலிருந்து திரும்பிய தேதி","29 ஆகஸ்ட் 1498"),
(248,"number","Surviving men on Vasco da Gama's return journey","55","வாஸ்கோ ட காமாவின் திரும்பும் பயணத்தில் உயிர் பிழைத்தோர்","55"),
(248,"person","Portuguese commander sent with 1200 men and 13 vessels after Gama's success","Pedro Alvarez Cabral","காமாவின் வெற்றிக்குப் பின் 1200 ஆட்கள், 13 கப்பல்களுடன் அனுப்பப்பட்ட போர்த்துக்கீசியர்","பெட்ரோ ஆல்வரெஸ் கப்ரால்"),
(248,"number","Men sent under Pedro Alvarez Cabral","1200","பெட்ரோ ஆல்வரெஸ் கப்ராலுடன் அனுப்பப்பட்ட ஆட்கள் எண்ணிக்கை","1200"),
(248,"number","Vessels sent under Pedro Alvarez Cabral","13","பெட்ரோ ஆல்வரெஸ் கப்ராலுடன் அனுப்பப்பட்ட கப்பல்கள் எண்ணிக்கை","13"),
(248,"date","Date of Vasco da Gama's second visit to Calicut","29 October 1502","வாஸ்கோ ட காமா காலிக்கட்டை இரண்டாவது முறையாக சென்ற தேதி","29 அக்டோபர் 1502"),
(248,"number","Vessels in Vasco da Gama's second fleet","20","வாஸ்கோ ட காமாவின் இரண்டாவது படையில் இருந்த கப்பல்கள்","20"),
(248,"port","Port preferred by Vasco da Gama for its better harbour","Cochin","சிறந்த துறைமுகத்தால் வாஸ்கோ ட காமா விரும்பிய இடம்","கொச்சி"),
(248,"group","Trading group whose monopoly Gama sought to break","Arabs","காமா உடைக்க விரும்பிய வாணிப ஏகபோகக் குழு","அரபியர்கள்"),
(248,"rivalry","Rival rulers whose hostility Gama exploited","Cochin and Calicut","காமா பயன்படுத்திக் கொண்ட அரசர்களின் பகைமை","கொச்சி மற்றும் காலிக்கட்"),
(248,"factory","Location of Portuguese factory established by Gama","Cochin","காமா நிறுவிய போர்த்துக்கீசிய வணிக நிலையத்தின் இடம்","கொச்சி"),
(248,"prison","Location of Portuguese prison established by Gama","Kannur","காமா நிறுவிய போர்த்துக்கீசிய சிறை அமைந்த இடம்","கண்ணூர்"),
(248,"person","First Portuguese Viceroy in India","Francisco d'Almeida","இந்தியாவின் முதல் போர்த்துக்கீசிய வைஸ்ராய்","பிரான்சிஸ்கோ டி அல்மெய்டா"),
(248,"policy","Naval strategy followed by Almeida","Blue Water Policy","அல்மெய்டா பின்பற்றிய கடற்படை கொள்கை","நீலநீர் கொள்கை"),
(248,"focus","Core of Almeida's Blue Water Policy","Strengthen navy rather than add settlements","அல்மெய்டாவின் நீலநீர் கொள்கையின் மையம்","குடியேற்றங்களை விட கடற்படையை வலுப்படுத்துதல்"),
(248,"action","One major action of Almeida","Destroyed Zamorin's fleet","அல்மெய்டாவின் முக்கிய நடவடிக்கை","சாமூதிரியின் கடற்படையை அழித்தார்"),
(248,"enemy","Foreign fleet defeated by Almeida","Fleet sent by Sultan of Egypt","அல்மெய்டா தோற்கடித்த வெளிநாட்டு கடற்படை","எகிப்து சுல்தான் அனுப்பிய கடற்படை"),
(248,"ally","Indian ruler befriended by Almeida","Ruler of Cochin","அல்மெய்டா நட்பு கொண்ட இந்திய அரசர்","கொச்சி அரசர்"),
(249,"person","Successor of Almeida regarded as real founder of Portuguese empire in India","Albuquerque","இந்திய போர்த்துக்கீசியப் பேரரசின் உண்மையான நிறுவனர் எனக் கருதப்படும் அல்மெய்டாவின் வாரிசு","அல்புகர்க்"),
(249,"period","Tenure of Albuquerque","1509–1515","அல்புகர்கின் காலம்","1509–1515"),
(249,"person","Bijapur ruler defeated by Albuquerque in 1510","Yusuf Adil Khan","1510இல் அல்புகர்கால் தோற்கடிக்கப்பட்ட பிஜாப்பூர் அரசர்","யூசுப் ஆதில் கான்"),
(249,"place","Territory captured by Albuquerque in 1510","Goa","1510இல் அல்புகர்க் கைப்பற்றிய பகுதி","கோவா"),
(249,"policy","Albuquerque's settlement policy in Goa","Encouraged people of all faiths to settle","கோவாவில் அல்புகர்கின் குடியேற்றக் கொள்கை","அனைத்து மதத்தவரும் குடியேற ஊக்குவித்தார்"),
(249,"policy","Marriage policy encouraged by Albuquerque","European men marrying Indian women","அல்புகர்க் ஊக்குவித்த திருமணக் கொள்கை","ஐரோப்பிய ஆண்கள் இந்திய பெண்களை மணத்தல்"),
(249,"place","Southeast Asian trading centre conquered by Albuquerque","Malacca","அல்புகர்க் கைப்பற்றிய தென்கிழக்காசிய வாணிப மையம்","மலாக்கா"),
(249,"route","Trade route controlled through Malacca","India-China and Mecca-Cairo route","மலாக்கா வழியாக கட்டுப்படுத்தப்பட்ட வாணிபப் பாதை","இந்தியா-சீனா மற்றும் மக்கா-கெய்ரோ பாதை"),
(249,"place","Arabian port successfully taken by Albuquerque","Aden","அல்புகர்க் கைப்பற்றிய அரபுக் கடற்புறத் துறைமுகம்","ஏடன்"),
(249,"date","Year Albuquerque took control of Ormuz","1515","அல்புகர்க் ஓர்முஸை கைப்பற்றிய ஆண்டு","1515"),
(249,"practice","Indian social practice Albuquerque attempted to stop","Sati","அல்புகர்க் தடுக்க முயன்ற இந்திய சமூக நடைமுறை","சதி"),
(249,"person","Portuguese viceroy who occupied Bassein","Nino da Cunha","பசேனை கைப்பற்றிய போர்த்துக்கீசிய வைஸ்ராய்","நினோ ட குன்ஹா"),
(249,"date","Year Bassein was occupied by Da Cunha","1534","ட குன்ஹா பசேனை கைப்பற்றிய ஆண்டு","1534"),
(249,"date","Year Diu was occupied by Da Cunha","1537","ட குன்ஹா டையூவை கைப்பற்றிய ஆண்டு","1537"),
(249,"place","Port wrested from Imad-ul Mulk in 1559","Daman","1559இல் இமாத்-உல்-முல்கிடமிருந்து கைப்பற்றப்பட்ட துறைமுகம்","டாமன்"),
(249,"date","Year Daman was seized","1559","டாமன் கைப்பற்றப்பட்ட ஆண்டு","1559"),
(249,"place","Ceylon city where Portuguese fort was completed in mid-sixteenth century","Colombo","16ஆம் நூற்றாண்டின் நடுப்பகுதியில் போர்த்துக்கீசிய கோட்டை முடிக்கப்பட்ட இலங்கை நகரம்","கொழும்பு"),
(249,"person","Portuguese viceroy during whose period Akbar visited Cambay","Antonio de Noronha","அக்பர் காம்பே சென்ற கால போர்த்துக்கீசிய வைஸ்ராய்","அன்டோனியோ டி நொரோன்ஹா"),
(249,"date","Year associated with De Noronha's period and Akbar's first Portuguese contacts","1571","டி நொரோன்ஹா காலமும் அக்பர்-போர்த்துக்கீசிய முதல் தொடர்புகளும் தொடர்புடைய ஆண்டு","1571"),
(249,"person","Spanish king who defeated and annexed Portugal","Philip II","போர்த்துக்கலை தோற்கடித்து இணைத்த ஸ்பெயின் மன்னர்","இரண்டாம் பிலிப்"),
(249,"date","Year Spain annexed Portugal","1580","ஸ்பெயின் போர்த்துக்கலை இணைத்த ஆண்டு","1580"),
(249,"nation","European power that defeated Portuguese in Ceylon","Dutch","இலங்கையில் போர்த்துக்கீசியரை தோற்கடித்த ஐரோப்பிய சக்தி","டச்சுக்காரர்கள்"),
(249,"region","Overseas colony that increasingly attracted Portuguese attention after setbacks in India","Brazil","இந்தியத் தோல்விகளுக்குப் பின் போர்த்துக்கீசிய கவனம் அதிகரித்த காலனி","பிரேசில்"),

# Portuguese impact and missions
(249,"impact","First political impact of Portuguese presence","Europeans conquered and seized Indian territories","போர்த்துக்கீசியர் வருகையின் முதல் அரசியல் தாக்கம்","ஐரோப்பியர்கள் இந்திய அரசர்களிடமிருந்து நிலங்களை கைப்பற்றினர்"),
(249,"impact","Indian political condition exploited by Europeans","Division among Indian rulers","ஐரோப்பியர்கள் பயன்படுத்திய இந்திய அரசியல் நிலை","இந்திய அரசர்களின் பிளவு"),
(249,"impact","Military innovation used by Europeans","Gunpowder and superior artillery","ஐரோப்பியர்கள் பயன்படுத்திய இராணுவப் புதுமை","வெடிமருந்தும் மேம்பட்ட பீரங்கியும்"),
(249,"impact","Trade monopoly checked by Portuguese","Arab monopoly","போர்த்துக்கீசியர்கள் கட்டுப்படுத்திய வாணிப ஏகபோகம்","அரபு ஏகபோகம்"),
(249,"result","European power that ultimately benefited from safer sea routes","British","பாதுகாப்பான கடல்வழிகளால் இறுதியில் அதிகம் பயனடைந்த ஐரோப்பிய சக்தி","ஆங்கிலேயர்கள்"),
(249,"group","New racial group formed by European-Indian marriages","Eurasians","ஐரோப்பிய-இந்திய கலப்பு திருமணங்களால் உருவான புதிய இனக்குழு","யூரேசியர்கள்"),
(249,"place","Portuguese presence strongly visible in Chennai","San Thome","சென்னையில் போர்த்துக்கீசியர் இருப்பு தெளிவாகத் தெரியும் பகுதி","சாந்தோம்"),
(249,"place","Portuguese 'Black Town' in Chennai","Mylapore","சென்னையில் போர்த்துக்கீசியர்களின் 'பிளாக் டவுன்'","மயிலாப்பூர்"),
(249,"place","British-period Black Town in Chennai","George Town","ஆங்கிலேய கால 'பிளாக் டவுன்'","ஜார்ஜ் டவுன்"),
(249,"person","Jesuit missionary called father of Tamil prose in the chapter","Roberto de Nobili","தமிழ் உரைநடையின் தந்தை என பாடநூல் குறிப்பிடும் ஜெசூயிட் மறைப்பணியாளர்","ராபர்டோ டி நொபிலி"),
(249,"ability","Skill enabling Roberto de Nobili to write in Tamil and Sanskrit","Linguistic ability","ராபர்டோ டி நொபிலி தமிழிலும் சமஸ்கிருதத்திலும் எழுத உதவிய திறன்","மொழித் திறன்"),
(249,"person","Missionary called father of printing press","Henriques","அச்சகத்தின் தந்தை என அழைக்கப்படும் மறைப்பணியாளர்","ஹென்ரிக்ஸ்"),
(249,"achievement","Contribution of Henriques","Introduced printing in Tamil","ஹென்ரிக்ஸின் பங்களிப்பு","தமிழில் அச்சிடுதலை அறிமுகப்படுத்தினார்"),
(250,"region","Coast where Portuguese-Muslim clashes occurred over pearl fishing","Pearl Fishery Coast","முத்துக் குளிப்பு உரிமையைச் சுற்றி போர்த்துக்கீசிய-முஸ்லிம் மோதல்கள் நடந்த கடற்கரை","முத்துக்குளித்துறை கடற்கரை"),
(250,"period","Decade of clashes over pearl fishing rights","1530s","முத்துக் குளிப்பு உரிமை மோதல்கள் நடந்த காலம்","1530கள்"),
(250,"community","Fishing community that sought Portuguese protection","Paravas","போர்த்துக்கீசிய பாதுகாப்பை நாடிய மீனவர் சமூகத்தினர்","பரவர்கள்"),
(250,"place","Portuguese centre to which Paravas appealed","Cochin","பரவர்கள் பாதுகாப்பு கேட்ட போர்த்துக்கீசிய மையம்","கொச்சி"),
(250,"religion","Religion to which thousands of fisher people were converted","Catholic Christianity","ஆயிரக்கணக்கான மீனவர்கள் மாற்றப்பட்ட மதம்","கத்தோலிக்க கிறித்தவம்"),
(250,"person","Jesuit founder who arrived in Goa in 1542","St. Francis Xavier","1542இல் கோவா வந்த ஜெசூயிட் நிறுவனர்","புனித பிரான்சிஸ் சேவியர்"),
(250,"date","Year St. Francis Xavier arrived in Goa","1542","புனித பிரான்சிஸ் சேவியர் கோவா வந்த ஆண்டு","1542"),
(250,"place","Tamil coastal town visited by Xavier","Thoothukudi","சேவியர் சென்ற தமிழ்க் கடற்கரை நகரம்","தூத்துக்குடி"),
(250,"place","Another Tamil coastal town visited by Xavier","Punnakayal","சேவியர் சென்ற மற்றொரு தமிழ்க் கடற்கரை நகரம்","புன்னக்காயல்"),
(250,"institution","Network established by Xavier","Jesuit mission centres","சேவியர் நிறுவிய வலையமைப்பு","ஜெசூயிட் மறைப்பணி மையங்கள்"),
(250,"system","Portuguese maritime protection-pass system","Cartaz system","போர்த்துக்கீசிய கடல் பாதுகாப்புச் சீட்டு முறை","கார்டாஸ் முறை"),
(250,"meaning","Economic nature of Cartaz according to the chapter","Protection racket","பாடநூலின்படி கார்டாஸ் முறையின் பொருளாதார தன்மை","பாதுகாப்பு பெயரில் பணம் பறிக்கும் முறை"),

# Dutch
(250,"date","Year of the first Dutch expedition to Southeast Asia","1595","முதல் டச்சு தென்கிழக்காசியப் பயண ஆண்டு","1595"),
(250,"person","Trader associated with first Dutch expedition to Southeast Asia","Jan Huyghen van Linschoten","முதல் டச்சு தென்கிழக்காசியப் பயணத்துடன் தொடர்புடைய வணிகர்","யான் ஹுய்கென் வான் லின்ஸ்கோட்டன்"),
(250,"date","Year Dutch East India Company was formed","1602","டச்சு கிழக்கிந்தியக் கம்பெனி உருவான ஆண்டு","1602"),
(250,"name","Dutch name/abbreviation of the United East Indies Company","VOC","யுனைடெட் ஈஸ்ட் இண்டீஸ் கம்பெனியின் டச்சு சுருக்கப் பெயர்","VOC"),
(250,"region","Region over which the VOC established control","Spice Islands of Indonesia","VOC கட்டுப்பாடு நிலைநிறுத்திய பகுதி","இந்தோனேசிய மசாலா தீவுகள்"),
(250,"date","Year Dutch captured Malacca from Portuguese","1641","டச்சுக்காரர்கள் மலாக்காவை போர்த்துக்கீசியரிடமிருந்து கைப்பற்றிய ஆண்டு","1641"),
(250,"date","Year Dutch forced Portuguese to leave Ceylon","1658","டச்சுக்காரர்கள் போர்த்துக்கீசியரை இலங்கையிலிருந்து வெளியேற்றிய ஆண்டு","1658"),
(250,"region","Area where Dutch were highly successful","Spice Islands","டச்சுக்காரர்கள் மிகுந்த வெற்றி பெற்ற பகுதி","மசாலா தீவுகள்"),
(250,"rival","European rival that caused Dutch reverses in India","British","இந்தியாவில் டச்சு தோல்விகளுக்குக் காரணமான ஐரோப்பியப் போட்டியாளர்","ஆங்கிலேயர்கள்"),
(250,"place","Tamil port where Portuguese control was overthrown by Dutch","Pulicat","போர்த்துக்கீசிய கட்டுப்பாட்டை டச்சுக்காரர்கள் நீக்கிய தமிழ்த் துறைமுகம்","பழவேற்காடு"),
(250,"distance","Distance of Pulicat north of Chennai","60 kilometres","சென்னைக்கு வடக்கே பழவேற்காட்டின் தூரம்","60 கிலோமீட்டர்"),
(250,"fort","Dutch fort at Pulicat","Castle Geldria","பழவேற்காட்டில் டச்சு கோட்டை","காஸில் கெல்ட்ரியா"),
(250,"date","Year Dutch established control at Masulipatnam","1605","டச்சுக்காரர்கள் மசூலிப்பட்டினத்தில் கட்டுப்பாடு அமைத்த ஆண்டு","1605"),
(250,"date","Year Dutch settlement at Pulicat was established","1610","பழவேற்காட்டில் டச்சு குடியேற்றம் அமைந்த ஆண்டு","1610"),
(250,"place","One Dutch colonial possession in Tamil region","Nagapattinam","தமிழகத்தில் டச்சு காலனி உடைமைகளில் ஒன்று","நாகப்பட்டினம்"),
(250,"place","One Dutch colonial possession in Tamil region","Punnakayal","தமிழகத்தில் டச்சு காலனி உடைமைகளில் ஒன்று","புன்னக்காயல்"),
(250,"place","One Dutch colonial possession in Tamil region","Porto Novo","தமிழகத்தில் டச்சு காலனி உடைமைகளில் ஒன்று","பரங்கிப்பேட்டை"),
(250,"place","One Dutch colonial possession in Tamil region","Cuddalore","தமிழகத்தில் டச்சு காலனி உடைமைகளில் ஒன்று","கடலூர்"),
(250,"place","One Dutch colonial possession in Tamil region","Devanampatinam","தமிழகத்தில் டச்சு காலனி உடைமைகளில் ஒன்று","தேவனாம்பட்டினம்"),
(250,"event","1623 killing of British, Portuguese and Japanese servants by Dutch agents","Amboyna Massacre","1623இல் டச்சு முகவர்கள் பிரிட்டிஷ், போர்த்துக்கீசிய, ஜப்பானிய சேவகர்களைக் கொன்ற சம்பவம்","அம்போய்னா படுகொலை"),
(250,"date","Year of the Amboyna Massacre","1623","அம்போய்னா படுகொலையின் ஆண்டு","1623"),
(250,"place","Island where Amboyna Massacre occurred","Ambon Island, Indonesia","அம்போய்னா படுகொலை நடந்த இடம்","இந்தோனேசியாவின் அம்போன் தீவு"),
(250,"number","Number of servants tortured and killed in Amboyna Massacre","Twenty","அம்போய்னா படுகொலையில் கொல்லப்பட்ட சேவகர்கள் எண்ணிக்கை","இருபது"),
(251,"role","Status of Pulicat in Dutch administration","Coromandel headquarters of Dutch East India Company","டச்சு நிர்வாகத்தில் பழவேற்காட்டின் நிலை","டச்சு கிழக்கிந்தியக் கம்பெனியின் கொரோமண்டல் தலைமையகம்"),
(251,"export","Valuable commodity exported from Pulicat to western countries","Diamonds","பழவேற்காட்டிலிருந்து மேற்கத்திய நாடுகளுக்கு ஏற்றுமதி செய்யப்பட்ட பொருள்","வைரங்கள்"),
(251,"export","Spice exported from Pulicat","Nutmeg","பழவேற்காட்டிலிருந்து ஏற்றுமதி செய்யப்பட்ட மசாலா","ஜாதிக்காய்"),
(251,"export","Spice exported from Pulicat","Cloves","பழவேற்காட்டிலிருந்து ஏற்றுமதி செய்யப்பட்ட மசாலா","கிராம்பு"),
(251,"export","Spice exported from Pulicat","Mace","பழவேற்காட்டிலிருந்து ஏற்றுமதி செய்யப்பட்ட மசாலா","ஜாதிப்பத்திரி"),
(251,"factory","Military production facility set up by Dutch at Pulicat","Gunpowder factory","பழவேற்காட்டில் டச்சு அமைத்த இராணுவ உற்பத்தி நிலையம்","வெடிமருந்து ஆலை"),
(251,"trade","Exploitative trade in which Dutch were involved","Slave trade","டச்சுக்காரர்கள் ஈடுபட்ட சுரண்டல் வாணிபம்","அடிமை வாணிபம்"),
(251,"region","One source region for slaves brought to Pulicat","Bengal","பழவேற்காட்டுக்கு அடிமைகள் கொண்டு வரப்பட்ட பகுதி","வங்காளம்"),
(251,"place","One settlement from which slaves were brought to Pulicat","Tengapattinam","பழவேற்காட்டுக்கு அடிமைகள் கொண்டு வரப்பட்ட குடியேற்றம்","தேங்காப்பட்டினம்"),
(251,"place","One settlement from which slaves were brought to Pulicat","Karaikal","பழவேற்காட்டுக்கு அடிமைகள் கொண்டு வரப்பட்ட குடியேற்றம்","காரைக்கால்"),
(251,"city","Place where Dutch employed slave-catching brokers","Madras","அடிமைகளை பிடித்து அனுப்ப டச்சு தரகர்களை நியமித்த நகரம்","மதராஸ்"),
(251,"cause","Conditions that made slave trade flourish","Famines, droughts and war","அடிமை வாணிபம் பெருக காரணமான சூழல்கள்","பஞ்சம், வறட்சி மற்றும் போர்"),
(251,"person","Leiden University scholar cited on Dutch slave trade","Wil O Dijk","டச்சு அடிமை வாணிபம் குறித்த ஆய்வில் மேற்கோள் கொள்ளப்பட்ட லெய்டன் பல்கலைக்கழக ஆய்வாளர்","வில் ஓ டைக்"),
(251,"period","VOC slave passenger-list period cited","June 1621 to November 1665","மேற்கோள் கொள்ளப்பட்ட VOC அடிமைப் பயணி பட்டியல் காலம்","ஜூன் 1621 முதல் நவம்பர் 1665 வரை"),
(251,"number","Total slaves transported in cited VOC lists","26,885","மேற்கோள் கொள்ளப்பட்ட VOC பட்டியல்களில் கொண்டு செல்லப்பட்ட மொத்த அடிமைகள்","26,885"),
(251,"number","Deaths among slaves in cited VOC lists","1,379","மேற்கோள் கொள்ளப்பட்ட VOC அடிமைப் பட்டியலில் இறந்தோர் எண்ணிக்கை","1,379"),
(251,"cause","Event causing surge in Coromandel slave exports","Famine after fall of Vijayanagara","கொரோமண்டல் அடிமை ஏற்றுமதி அதிகரித்த முக்கிய காரணம்","விஜயநகர வீழ்ச்சிக்குப் பிந்தைய பஞ்சம்"),
(251,"date","Year of Bijapur invasion linked to another slave-export surge","1646","மற்றொரு அடிமை ஏற்றுமதி அதிகரிப்புடன் தொடர்புடைய பிஜாப்பூர் படையெடுப்பு ஆண்டு","1646"),
(251,"number","Approximate slaves exported in the 1646 episode","2,118","1646 சம்பவத்தில் ஏற்றுமதி செய்யப்பட்ட அடிமைகள் சுமார் எண்ணிக்கை","2,118"),
(251,"place","One coastal source of slaves in 1646","Adiramapattinam","1646இல் அடிமைகள் எடுக்கப்பட்ட கடற்கரை இடம்","அதிராம்பட்டினம்"),
(251,"place","One coastal source of slaves in 1646","Tondi","1646இல் அடிமைகள் எடுக்கப்பட்ட கடற்கரை இடம்","தொண்டி"),
(251,"place","One coastal source of slaves in 1646","Kayalpattinam","1646இல் அடிமைகள் எடுக்கப்பட்ட கடற்கரை இடம்","காயல்பட்டினம்"),

# French
(251,"date","Year of an early French attempt to establish trade link with India","1527","இந்தியாவுடன் வாணிபத் தொடர்பு ஏற்படுத்த பிரெஞ்சு மேற்கொண்ட ஆரம்ப முயற்சி ஆண்டு","1527"),
(251,"date","Year French East India Company was established","1664","பிரெஞ்சு கிழக்கிந்தியக் கம்பெனி நிறுவப்பட்ட ஆண்டு","1664"),
(251,"ruler","French king under whom the French East India Company was a royal project","Louis XIV","பிரெஞ்சு கிழக்கிந்தியக் கம்பெனி அரசுத் திட்டமாக இருந்த கால பிரெஞ்சு மன்னர்","பதினான்காம் லூயி"),
(251,"person","Finance minister instrumental in creating French East India Company","Colbert","பிரெஞ்சு கிழக்கிந்தியக் கம்பெனி அமைப்பதில் முக்கிய பங்காற்றிய நிதி அமைச்சர்","கோல்பேர்"),
(251,"character","Distinctive character of French commercial enterprise","Government initiative","பிரெஞ்சு வணிக முயற்சியின் தனித்தன்மை","அரசு முயற்சி"),
(251,"place","African island reached by French traders in 1602","Madagascar","1602இல் பிரெஞ்சு வணிகர்கள் சென்ற ஆப்பிரிக்கத் தீவு","மடகாஸ்கர்"),
(251,"date","Year French traders arrived in Madagascar","1602","பிரெஞ்சு வணிகர்கள் மடகாஸ்கர் வந்த ஆண்டு","1602"),
(251,"date","Year France largely abandoned Madagascar","1674","பிரான்ஸ் பெரும்பாலும் மடகாஸ்கரை கைவிட்ட ஆண்டு","1674"),
(251,"person","French agent who obtained Aurangzeb's firman","Berber","ஔரங்கசீப்பிடமிருந்து பர்மான் பெற்ற பிரெஞ்சு முகவர்","பெர்பர்"),
(251,"date","Date of Aurangzeb's firman to French agent","4 September 1666","பிரெஞ்சு முகவருக்கு ஔரங்கசீப் வழங்கிய பர்மானின் தேதி","4 செப்டம்பர் 1666"),
(251,"place","Location of first French factory in India","Surat","இந்தியாவின் முதல் பிரெஞ்சு வணிக நிலையம்","சூரத்"),
(251,"date","Month and year first French factory at Surat was established","December 1668","சூரத்தில் முதல் பிரெஞ்சு வணிக நிலையம் அமைந்த மாதம் மற்றும் ஆண்டு","டிசம்பர் 1668"),
(251,"place","Second French factory established soon after Surat","Masulipatnam","சூரத்திற்குப் பின் நிறுவப்பட்ட இரண்டாவது பிரெஞ்சு வணிக நிலையம்","மசூலிப்பட்டினம்"),
(251,"meaning","Meaning of factory in early European trade context","Warehouse and residence of commercial agents","ஆரம்ப ஐரோப்பிய வாணிபத்தில் factory என்பதன் பொருள்","கிடங்கும் வணிக முகவர்கள் வசிக்கும் இடமும்"),
(251,"person","French commander sent by Colbert with a fleet to India","Haye (Jacob Blanquet de la Haye)","கோல்பேர் இந்தியாவுக்கு கடற்படையுடன் அனுப்பிய பிரெஞ்சு தளபதி","ஹே (ஜேக்கப் பிளாங்கே டி லா ஹே)"),
(251,"date","Year French removed Dutch from San Thome","1672","பிரெஞ்சு சாந்தோமிலிருந்து டச்சுக்காரர்களை நீக்கிய ஆண்டு","1672"),
(251,"person","Local Bijapur governor whose support French sought","Sher Khan Lodi","பிரெஞ்சு ஆதரவு நாடிய பிஜாப்பூர் உள்ளூர் ஆளுநர்","ஷேர் கான் லோடி"),
(251,"state","State represented by Sher Khan Lodi","Bijapur","ஷேர் கான் லோடி பிரதிநிதித்துவப்படுத்திய அரசு","பிஜாப்பூர்"),
(251,"rival_state","State whose king was befriended by Dutch against the French","Golkonda","பிரெஞ்சுக்கு எதிராக டச்சுக்காரர்கள் நட்பு கொண்ட அரசு","கோல்கொண்டா"),
(251,"place","Site offered by Sher Khan Lodi to the French","Pondicherry","ஷேர் கான் லோடி பிரெஞ்சுக்காரர்களுக்கு வழங்கிய குடியேற்ற இடம்","புதுச்சேரி"),
(251,"date","Year associated with Pondicherry becoming French site","1673","புதுச்சேரி பிரெஞ்சு குடியேற்றமாகத் தொடங்கிய ஆண்டு","1673"),
(252,"person","French governor who made Pondicherry strategic centre of French settlements","Francis Martin","புதுச்சேரியை பிரெஞ்சு குடியேற்றங்களின் தந்திர மையமாக மாற்றிய ஆளுநர்","பிரான்சிஸ் மார்ட்டின்"),
(252,"place","Region where Francis Martin had spent four years before India","Madagascar","இந்தியா வருவதற்கு முன் பிரான்சிஸ் மார்ட்டின் நான்கு ஆண்டுகள் இருந்த பகுதி","மடகாஸ்கர்"),
(252,"rival","Main European rival of French over Pondicherry","Dutch","புதுச்சேரியைச் சுற்றி பிரெஞ்சுக்காரர்களின் முக்கிய ஐரோப்பிய போட்டியாளர்","டச்சுக்காரர்கள்"),
(252,"period","Period from which France and Holland were continuously at war","From 1672","பிரான்ஸ் மற்றும் ஹாலந்து தொடர்ந்து போரிட்ட தொடக்க காலம்","1672 முதல்"),
(252,"date","Year Dutch captured Pondicherry","1693","டச்சுக்காரர்கள் புதுச்சேரியை கைப்பற்றிய ஆண்டு","1693"),
(252,"duration","How long Pondicherry remained with Dutch after 1693","Six years","1693க்கு பின் புதுச்சேரி டச்சுக்காரர்களிடம் இருந்த காலம்","ஆறு ஆண்டுகள்"),
(252,"treaty","Treaty providing for restoration of Pondicherry to French","Treaty of Ryswick","புதுச்சேரியை பிரெஞ்சுக்காரர்களுக்கு மீட்க ஏற்பாடு செய்த ஒப்பந்தம்","ரிஸ்விக் ஒப்பந்தம்"),
(252,"date","Year of Treaty of Ryswick","1697","ரிஸ்விக் ஒப்பந்த ஆண்டு","1697"),
(252,"date","Year Pondicherry was actually handed back to French","1699","புதுச்சேரி நடைமுறையில் பிரெஞ்சுக்காரர்களுக்கு திருப்பிக் கொடுக்கப்பட்ட ஆண்டு","1699"),
(252,"date","Year Francis Martin died","1706","பிரான்சிஸ் மார்ட்டின் இறந்த ஆண்டு","1706"),
(252,"place","French possession secured in 1725","Mahe","1725இல் பிரெஞ்சுக்காரர்கள் பெற்ற பகுதி","மாஹே"),
(252,"date","Year French secured Mahe","1725","பிரெஞ்சுக்காரர்கள் மாஹே பெற்ற ஆண்டு","1725"),
(252,"place","French possession secured in 1739","Karaikal","1739இல் பிரெஞ்சுக்காரர்கள் பெற்ற பகுதி","காரைக்கால்"),
(252,"date","Year French secured Karaikal","1739","பிரெஞ்சுக்காரர்கள் காரைக்கால் பெற்ற ஆண்டு","1739"),
(252,"place","French Bengal settlement","Qasim Bazaar","வங்காளத்தின் பிரெஞ்சு குடியேற்றம்","காசிம் பஜார்"),
(252,"place","French Bengal settlement","Chandranagore","வங்காளத்தின் பிரெஞ்சு குடியேற்றம்","சந்திரநாகூர்"),
(252,"place","French Bengal settlement","Balasore","வங்காளத்தின் பிரெஞ்சு குடியேற்றம்","பாலசோர்"),
(252,"person","Able French governor of Pondicherry after Francis Martin","Pierre Benoit Dumas","பிரான்சிஸ் மார்ட்டினுக்குப் பின் திறமையான புதுச்சேரி ஆளுநர்","பியர் பெனுவா துமா"),

# Danes
(252,"nation","Scandinavian kingdoms politically united until 1813","Denmark and Norway","1813 வரை ஒன்றிணைந்திருந்த ஸ்காண்டினேவிய அரசுகள்","டென்மார்க் மற்றும் நார்வே"),
(252,"place","Main Danish settlement in Tamil Nadu","Tarangambadi (Tranquebar)","தமிழ்நாட்டின் முக்கிய டேனிஷ் குடியேற்றம்","தரங்கம்பாடி"),
(252,"place","Danish possession in West Bengal","Serampore","மேற்கு வங்காளத்தின் டேனிஷ் குடியேற்றம்","சேராம்பூர்"),
(252,"place","Island possession of Danes in India","Nicobar Islands","இந்தியாவில் டேனிஷ் தீவு உடைமை","நிக்கோபார் தீவுகள்"),
(252,"date","Date Christian IV chartered Danish East India Company","17 March 1616","நான்காம் கிறிஸ்டியன் டேனிஷ் கிழக்கிந்தியக் கம்பெனிக்கு சாசனம் அளித்த தேதி","17 மார்ச் 1616"),
(252,"ruler","Danish king who created Danish East India Company","Christian IV","டேனிஷ் கிழக்கிந்தியக் கம்பெனியை உருவாக்கிய மன்னர்","நான்காம் கிறிஸ்டியன்"),
(252,"person","Admiral leading first Danish expedition to Ceylon","Ove Gjedde","முதல் டேனிஷ் இலங்கைப் பயணத்தை வழிநடத்திய அட்மிரல்","ஓவே கெடே"),
(252,"date","Year of first Danish expedition to Ceylon","1618","முதல் டேனிஷ் இலங்கைப் பயண ஆண்டு","1618"),
(252,"place","Place where Portuguese sank the returning Danish main vessel","Karaikkal","திரும்பிய டேனிஷ் முக்கியக் கப்பலை போர்த்துக்கீசியர்கள் மூழ்கடித்த இடம்","காரைக்கால்"),
(252,"number","Stranded Danish sailors taken to Thanjavur ruler","Thirteen","தஞ்சாவூர் அரசரிடம் அழைத்துச் செல்லப்பட்ட சிக்கிய டேனிஷ் மாலுமிகள்","பதின்மூன்று"),
(252,"person","Danish trade director who negotiated with Thanjavur king","Robert Crappe","தஞ்சாவூர் மன்னருடன் பேச்சுவார்த்தை நடத்திய டேனிஷ் வாணிப இயக்குநர்","ராபர்ட் கிராப்பே"),
(252,"date","Date of agreement granting Tarangambadi to Danes","20 November 1620","தரங்கம்பாடி டேனிஷாருக்கு வழங்கப்பட்ட ஒப்பந்த தேதி","20 நவம்பர் 1620"),
(252,"right","Right granted to Danes at Tarangambadi","Construct a fort","தரங்கம்பாடியில் டேனிஷாருக்கு வழங்கப்பட்ட உரிமை","கோட்டை கட்டும் உரிமை"),
(252,"hazard","Natural hazard affecting Danish fort at Tarangambadi","High tidal waves","தரங்கம்பாடி டேனிஷ் கோட்டையை பாதித்த இயற்கை அபாயம்","உயர் அலைகள்"),
(252,"war","European war financially affecting the Danish company","Thirty Years War","டேனிஷ் கம்பெனியை நிதியளவில் பாதித்த ஐரோப்பியப் போர்","முப்பது ஆண்டுப் போர்"),
(252,"place","Danish factory established despite financial difficulty","Masulipatnam","நிதிச் சிரமத்திலும் டேனிஷார் நிறுவிய வணிக நிலையம்","மசூலிப்பட்டினம்"),
(252,"place","Small Danish trading post on Hooghly River","Pipli","ஹூக்ளி ஆற்றின் டேனிஷ் சிறு வணிக நிலையம்","பிப்லி"),
(252,"place","Another small Danish trading post","Balasore","மற்றொரு டேனிஷ் சிறு வணிக நிலையம்","பாலசோர்"),
(252,"date","Year Christian IV died, after which first Danish company was abolished","1648","நான்காம் கிறிஸ்டியன் இறந்த ஆண்டு; பின்னர் முதல் டேனிஷ் கம்பெனி கலைக்கப்பட்டது","1648"),
(252,"person","Danish king who abolished first Danish East India Company","Frederick","முதல் டேனிஷ் கிழக்கிந்தியக் கம்பெனியை கலைத்த மன்னர்","பிரெடெரிக்"),
(252,"date","Year second Danish East India Company was started","1696","இரண்டாம் டேனிஷ் கிழக்கிந்தியக் கம்பெனி தொடங்கிய ஆண்டு","1696"),
(252,"grant","Additional villages gifted around Tarangambadi","Three villages","தரங்கம்பாடியைச் சுற்றி டேனிஷாருக்கு வழங்கப்பட்ட கூடுதல் கிராமங்கள்","மூன்று கிராமங்கள்"),
(252,"date","Date first Protestant Danish missionaries arrived","9 June 1706","முதல் புராட்டஸ்டன்ட் டேனிஷ் மறைப்பணியாளர்கள் வந்த தேதி","9 ஜூன் 1706"),
(252,"date","Year Danes settled in Andaman and Nicobar","1755","டேனிஷார் அந்தமான் நிக்கோபாரில் குடியேறிய ஆண்டு","1755"),
(252,"date","Year Danes abandoned Andaman and Nicobar","1848","டேனிஷார் அந்தமான் நிக்கோபாரை கைவிட்ட ஆண்டு","1848"),
(252,"cause","Reason Danes abandoned Andaman and Nicobar","Malaria","டேனிஷார் அந்தமான் நிக்கோபாரை கைவிட்ட காரணம்","மலேரியா"),
(253,"person","First Lutheran missionary in India named in the chapter","Bartholomaeus Ziegenbalg","இந்தியாவின் முதல் லூத்தரன் மறைப்பணியாளராக குறிப்பிடப்பட்டவர்","பார்த்தலோமியுஸ் சீகன்பால்க்"),
(253,"person","Missionary who arrived with Ziegenbalg","Heinrich Pluetshau","சீகன்பால்குடன் வந்த மறைப்பணியாளர்","ஹெய்ன்ரிக் ப்ளூட்சாவ்"),
(253,"place","Place where Ziegenbalg and Pluetshau arrived","Tranquebar","சீகன்பால்க், ப்ளூட்சாவ் வந்த இடம்","தரங்கம்பாடி"),
(253,"date","Month and year Ziegenbalg and Pluetshau arrived","September 1706","சீகன்பால்க், ப்ளூட்சாவ் வந்த மாதம் மற்றும் ஆண்டு","செப்டம்பர் 1706"),
(253,"result","Time within which first converts were baptised","Within ten months","முதல் மதமாற்றம் செய்து ஞானஸ்நானம் அளிக்கப்பட்ட காலம்","பத்து மாதங்களுக்குள்"),
(253,"period","Period Ziegenbalg spent imprisoned","Four months in 1707–08","சீகன்பால்க் சிறையில் இருந்த காலம்","1707–08இல் நான்கு மாதங்கள்"),
(253,"institution","Society guiding Danish missionaries","Copenhagen Missionary Society","டேனிஷ் மறைப்பணியாளர்களை வழிநடத்திய அமைப்பு","கோப்பன்ஹேகன் மிஷனரி சொசைட்டி"),
(253,"technology","Institution set up by Ziegenbalg","Printing press","சீகன்பால்க் நிறுவிய தொழில்நுட்ப நிறுவனம்","அச்சகம்"),
(253,"achievement","One scholarly contribution of Ziegenbalg","Studies of Tamil language","சீகன்பால்கின் அறிவியல் பங்களிப்புகளில் ஒன்று","தமிழ்மொழி ஆய்வுகள்"),
(253,"achievement","One scholarly contribution of Ziegenbalg","Studies of Indian religion and culture","சீகன்பால்கின் அறிவியல் பங்களிப்புகளில் ஒன்று","இந்திய சமயம் மற்றும் பண்பாட்டு ஆய்வுகள்"),
(253,"date","Year Ziegenbalg's Tamil New Testament translation appeared","1715","சீகன்பால்கின் தமிழ் புதிய ஏற்பாடு மொழிபெயர்ப்பு வெளியான ஆண்டு","1715"),
(253,"significance","Status of Ziegenbalg's New Testament translation","First in any Indian language","சீகன்பால்கின் புதிய ஏற்பாடு மொழிபெயர்ப்பின் சிறப்பு","இந்திய மொழிகளில் முதலாவது"),
(253,"date","Year church building by Ziegenbalg and associates was constructed","1718","சீகன்பால்க் மற்றும் இணைவர்கள் கட்டிய தேவாலய கட்டிட ஆண்டு","1718"),
(253,"institution","Training institution established by Ziegenbalg","Seminary for local clergy","சீகன்பால்க் நிறுவிய பயிற்சி நிறுவனம்","உள்ளூர் மதகுருக்களுக்கான செமினரி"),
(253,"date","Date of Ziegenbalg's death","23 February 1719","சீகன்பால்க் இறந்த தேதி","23 பிப்ரவரி 1719"),
(253,"number","Baptized Christians left by Ziegenbalg at death","250","சீகன்பால்க் இறக்கும் போது இருந்த ஞானஸ்நானம் பெற்ற கிறித்தவர்கள்","250"),
(253,"date","Year Serampore was sold to British","1839","சேராம்பூர் ஆங்கிலேயருக்கு விற்கப்பட்ட ஆண்டு","1839"),
(253,"date","Year Tranquebar and other Danish settlements were sold to British","1845","தரங்கம்பாடி மற்றும் பிற டேனிஷ் குடியேற்றங்கள் ஆங்கிலேயருக்கு விற்கப்பட்ட ஆண்டு","1845"),

# British company and Madras/Bombay
(253,"place","London street associated with founders of English East India Company","Leadenhall Street","ஆங்கில கிழக்கிந்தியக் கம்பெனி நிறுவிய வணிகர்களுடன் தொடர்புடைய லண்டன் தெரு","லீடன்ஹால் தெரு"),
(253,"ruler","English monarch who granted royal charter to East India Company","Queen Elizabeth I","கிழக்கிந்தியக் கம்பெனிக்கு அரச சாசனம் வழங்கிய இங்கிலாந்து அரசி","முதலாம் எலிசபெத்"),
(253,"trade","Commodity trade motivating English company formation","Spice trade","ஆங்கில கம்பெனி அமைக்கத் தூண்டிய வாணிபம்","மசாலா வாணிபம்"),
(253,"number","Directors managing English East India Company","24","ஆங்கில கிழக்கிந்தியக் கம்பெனியை நிர்வகித்த இயக்குநர்கள் எண்ணிக்கை","24"),
(253,"ruler","English king who obtained Mughal permission for regular trade in 1611","James I","1611இல் முகலாயரிடமிருந்து வழக்கமான வாணிப அனுமதி பெற்ற ஆங்கில மன்னர்","முதலாம் ஜேம்ஸ்"),
(253,"person","English envoy associated with obtaining permission from Jahangir in 1611","William Hawkins","1611இல் ஜஹாங்கீரிடம் அனுமதி பெற தொடர்புடைய ஆங்கிலத் தூதர்","வில்லியம் ஹாக்கின்ஸ்"),
(253,"ruler","Mughal emperor who granted English trading permission through Hawkins","Jahangir","ஹாக்கின்ஸ் வழியாக ஆங்கில வாணிப அனுமதி வழங்கிய முகலாய பேரரசர்","ஜஹாங்கீர்"),
(253,"place","Port where English obtained trading privileges","Surat","ஆங்கிலேயர்கள் வாணிபச் சலுகைகள் பெற்ற துறைமுகம்","சூரத்"),
(253,"person","Viceroy of Gujarat who granted English trading privileges","Prince Khurram","ஆங்கிலேயருக்கு வாணிபச் சலுகைகள் வழங்கிய குஜராத் வைஸ்ராய்","இளவரசர் குர்ரம்"),
(253,"rival","European power restricting English freedom in Gujarat","Portuguese","குஜராத்தில் ஆங்கில வாணிப சுதந்திரத்தை கட்டுப்படுத்திய ஐரோப்பிய சக்தி","போர்த்துக்கீசியர்கள்"),
(253,"date","Year Madras was ceded to East India Company","1639","மதராஸ் கிழக்கிந்தியக் கம்பெனிக்கு ஒப்படைக்கப்பட்ட ஆண்டு","1639"),
(253,"ruler","Ruler who ceded Madras to East India Company","Raja of Chandragiri","மதராஸை கிழக்கிந்தியக் கம்பெனிக்கு ஒப்படைத்த அரசர்","சந்திரகிரி ராஜா"),
(253,"fort","Fortified factory built by the Company at Madras","Fort St. George","மதராஸில் கம்பெனி கட்டிய கோட்டைக் குடியிருப்பு","செயின்ட் ஜார்ஜ் கோட்டை"),
(253,"significance","Importance of Madras grant to East India Company","First recorded Company landholding in India","மதராஸ் நில அளிப்பின் கம்பெனி வரலாற்றுச் சிறப்பு","இந்தியாவில் கம்பெனியின் முதல் பதிவுசெய்யப்பட்ட நில உரிமை"),
(253,"date","Year Golkonda overran Company territories in Madras","1645","கோல்கொண்டா மதராஸ் கம்பெனி பகுதிகளை கைப்பற்றிய ஆண்டு","1645"),
(253,"date","Year Aurangzeb conquered Golkonda","1687","ஔரங்கசீப் கோல்கொண்டாவை கைப்பற்றிய ஆண்டு","1687"),
(253,"result","Effect of Mughal conquest of Golkonda on English privileges","Privileges continued","கோல்கொண்டா முகலாயரால் கைப்பற்றப்பட்ட பின் ஆங்கில சலுகைகளின் நிலை","தொடர்ந்தன"),
(253,"headquarters","Port replaced by Madras as English Coromandel headquarters","Masulipatnam","ஆங்கில கொரோமண்டல் தலைமையகமாக மதராஸ் மாற்றிய இடம்","மசூலிப்பட்டினம்"),
(253,"island","Island inherited by Charles II as dowry","Bombay","இரண்டாம் சார்லஸுக்கு வரதட்சணையாக கிடைத்த தீவு","பம்பாய்"),
(253,"date","Year Bombay was transferred to East India Company","1668","பம்பாய் கிழக்கிந்தியக் கம்பெனிக்கு மாற்றப்பட்ட ஆண்டு","1668"),
(253,"charter","Charter empowering Company to raise military forces and make war or peace","Charter of 1683","கம்பெனிக்கு படை அமைத்து போர் அல்லது சமாதானம் செய்ய உரிமை அளித்த சாசனம்","1683 சாசனம்"),
(253,"date","Year Madras first became a presidency","1652","மதராஸ் முதன்முதலில் பிரெசிடென்சியான ஆண்டு","1652"),
(253,"date","Year Madras lost presidency status","1655","மதராஸ் பிரெசிடென்சி நிலையை இழந்த ஆண்டு","1655"),
(253,"date","Year Madras was re-elevated to presidency status","1684","மதராஸ் மீண்டும் பிரெசிடென்சியான ஆண்டு","1684"),
(253,"date","Year Madras obtained municipal government with a Mayor","1688","மதராஸ் மேயர் கொண்ட நகராட்சி நிர்வாகம் பெற்ற ஆண்டு","1688"),
(253,"date","Year Company obtained three more villages around Madras","1693","மதராஸைச் சுற்றி கம்பெனி மேலும் மூன்று கிராமங்கள் பெற்ற ஆண்டு","1693"),
(253,"date","Year five additional villages were granted around Madras","1702","மதராஸைச் சுற்றி மேலும் ஐந்து கிராமங்கள் வழங்கப்பட்ட ஆண்டு","1702"),

# Bengal
(255,"person","Mughal prince who first gave Company trading privileges in Bengal","Shah Shuja","வங்காளத்தில் கம்பெனிக்கு ஆரம்ப வாணிபச் சலுகைகள் வழங்கிய முகலாய இளவரசர்","ஷா ஷுஜா"),
(255,"relation","Shah Shuja's relationship to Shah Jahan","Second son","ஷா ஷுஜாவுக்கும் ஷாஜகானுக்கும் உள்ள உறவு","இரண்டாவது மகன்"),
(255,"office","Shah Shuja's position in Bengal","Governor of Bengal","வங்காளத்தில் ஷா ஷுஜாவின் பதவி","வங்காள ஆளுநர்"),
(255,"date","Year British trading rights in Bengal were finally obtained","1680","வங்காளத்தில் ஆங்கில வாணிப உரிமைகள் கிடைத்த ஆண்டு","1680"),
(255,"cause","Immediate problem leading Company to war in Bengal","Local officials interfered with English trading rights","வங்காளத்தில் கம்பெனி போர் அறிவிக்க வழிவகுத்த உடனடி பிரச்சினை","உள்ளூர் அதிகாரிகள் ஆங்கில வாணிப உரிமைகளில் தலையிட்டனர்"),
(255,"date","Year peace was restored and Sutanuti settlement established","1690","அமைதி மீண்டு சுதானுடி குடியேற்றம் அமைந்த ஆண்டு","1690"),
(255,"place","First English settlement in Bengal that became future Calcutta","Sutanuti","பின்னர் கல்கத்தாவான முதல் ஆங்கில வங்காள குடியேற்றம்","சுதானுடி"),
(255,"date","Year English factory at Bengal settlement was fortified","1696","வங்காள ஆங்கில வணிக நிலையம் கோட்டைப்படுத்தப்பட்ட ஆண்டு","1696"),
(255,"date","Year Company obtained zamindari rights over three Bengal villages","1698","மூன்று வங்காள கிராமங்களின் ஜமீந்தாரி உரிமையை கம்பெனி பெற்ற ஆண்டு","1698"),
(255,"village","One village in the Calcutta zamindari grant","Sutanuti","கல்கத்தா ஜமீந்தாரி அளிப்பில் உள்ள ஒரு கிராமம்","சுதானுடி"),
(255,"village","One village in the Calcutta zamindari grant","Kalikata","கல்கத்தா ஜமீந்தாரி அளிப்பில் உள்ள ஒரு கிராமம்","காலிகட்டா"),
(255,"village","One village in the Calcutta zamindari grant","Gobindpur","கல்கத்தா ஜமீந்தாரி அளிப்பில் உள்ள ஒரு கிராமம்","கோவிந்த்பூர்"),
(255,"payment","Annual payment for zamindari rights over three villages","1200 rupees","மூன்று கிராம ஜமீந்தாரி உரிமைக்கான ஆண்டு கட்டணம்","1200 ரூபாய்"),
(255,"fort","Name of fortified English factory in Bengal","Fort William","வங்காளத்தில் கோட்டைப்படுத்தப்பட்ட ஆங்கில வணிக நிலையத்தின் பெயர்","வில்லியம் கோட்டை"),
(255,"date","Year Fort William became presidency headquarters","1770","வில்லியம் கோட்டை பிரெசிடென்சி தலைமையகமான ஆண்டு","1770"),
(255,"mission","English mission sent by William III in 1698","Norris Mission","1698இல் மூன்றாம் வில்லியம் அனுப்பிய ஆங்கிலத் தூதுக்குழு","நோரிஸ் மிஷன்"),
(255,"person","Envoy leading Norris Mission","Sir William Norris","நோரிஸ் மிஷனை வழிநடத்திய தூதர்","சர் வில்லியம் நோரிஸ்"),
(255,"ruler","Mughal emperor met by Norris","Aurangzeb","நோரிஸ் சந்தித்த முகலாய பேரரசர்","ஔரங்கசீப்"),
(255,"goal","Aim of Norris Mission","Full English jurisdiction over English settlements","நோரிஸ் மிஷனின் நோக்கம்","ஆங்கில குடியேற்றங்களில் முழு ஆங்கில அதிகாரம்"),
(255,"period","Years of Surman mission obtaining firmans","1714–1717","சுர்மன் மிஷன் பர்மான்கள் பெற்ற காலம்","1714–1717"),
(255,"person","Envoy under whose mission trading firmans were obtained from Farrukhsiyar","Surman","பரூக்‌சியாரிடமிருந்து வாணிப பர்மான்கள் பெற்ற மிஷன் தலைவர்","சுர்மன்"),
(255,"ruler","Mughal emperor who granted firmans to Surman mission","Farrukhsiyar","சுர்மன் மிஷனுக்கு பர்மான்கள் வழங்கிய முகலாய பேரரசர்","பரூக்‌சியார்"),
(255,"region","One region whose local ruler received Farrukhsiyar's firman","Gujarat","பரூக்‌சியாரின் பர்மான் அனுப்பப்பட்ட பகுதி","குஜராத்"),
(255,"region","One region whose local ruler received Farrukhsiyar's firman","Hyderabad","பரூக்‌சியாரின் பர்மான் அனுப்பப்பட்ட பகுதி","ஹைதராபாத்"),
(255,"region","One region whose local ruler received Farrukhsiyar's firman","Bengal","பரூக்‌சியாரின் பர்மான் அனுப்பப்பட்ட பகுதி","வங்காளம்"),

# Carnatic Wars basics
(255,"number","Number of Carnatic Wars fought between British and French","Three","ஆங்கிலேயர் மற்றும் பிரெஞ்சுக்காரர்கள் நடத்திய கர்நாடகப் போர்கள் எண்ணிக்கை","மூன்று"),
(255,"period","Overall period of Carnatic Wars","1746–1763","கர்நாடகப் போர்களின் மொத்த காலம்","1746–1763"),
(255,"region","Location of Carnatic between Eastern Ghats and Coromandel Coast","South India","கிழக்கு தொடர்ச்சி மலை மற்றும் கொரோமண்டல் கடற்கரை இடையிலான கர்நாடகப் பகுதி","தென்னிந்தியா"),
(255,"state","Present-day state included in Carnatic region","Tamil Nadu","கர்நாடகப் பகுதியில் அடங்கும் இன்றைய மாநிலம்","தமிழ்நாடு"),
(255,"state","Present-day region included in Carnatic","Eastern Karnataka","கர்நாடகப் பகுதியில் அடங்கும் இன்றைய பகுதி","கிழக்கு கர்நாடகம்"),
(255,"state","Present-day region included in Carnatic","North-eastern Kerala","கர்நாடகப் பகுதியில் அடங்கும் இன்றைய பகுதி","வடகிழக்கு கேரளா"),
(255,"state","Present-day region included in Carnatic","Southern Andhra Pradesh","கர்நாடகப் பகுதியில் அடங்கும் இன்றைய பகுதி","தென் ஆந்திரப் பிரதேசம்"),

# First Carnatic War
(255,"period","First Carnatic War","1746–1748","முதல் கர்நாடகப் போர்","1746–1748"),
(255,"war","European war whose repercussions contributed to First Carnatic War","Austrian War of Succession","முதல் கர்நாடகப் போருக்குக் காரணமான ஐரோப்பியப் போர்","ஆஸ்திரிய வாரிசுரிமைப் போர்"),
(255,"ruler","Austrian ruler whose death triggered succession conflict","Charles VI","ஆஸ்திரிய வாரிசுரிமைச் சிக்கலைத் தூண்டிய மன்னர்","ஆறாம் சார்லஸ்"),
(255,"date","Year Charles VI died","1740","ஆறாம் சார்லஸ் இறந்த ஆண்டு","1740"),
(255,"person","Daughter who succeeded Charles VI","Maria Theresa","ஆறாம் சார்லஸுக்கு பின் வந்த மகள்","மரியா தெரசா"),
(255,"nation","European power that did not support Maria Theresa's succession","France","மரியா தெரசாவின் வாரிசுரிமையை ஆதரிக்காத ஐரோப்பிய சக்தி","பிரான்ஸ்"),
(255,"person","Prussian ruler who invaded and annexed Silesia","Frederick II","சிலீசியாவை ஆக்கிரமித்து இணைத்த ப்ரஷ்யா மன்னர்","இரண்டாம் பிரடெரிக்"),
(255,"alternate_name","Popular title of Frederick II","Frederick the Great","இரண்டாம் பிரடெரிக்கின் பிரபலப் பெயர்","பிரடெரிக் தி கிரேட்"),
(255,"province","Austrian province annexed by Frederick II","Silesia","இரண்டாம் பிரடெரிக் கைப்பற்றிய ஆஸ்திரிய மாகாணம்","சிலீசியா"),
(255,"person","Governor of Pondicherry who appealed for neutrality at outbreak of war","Dupleix","போர் தொடங்கியபோது நடுநிலையை கேட்ட புதுச்சேரி ஆளுநர்","டுப்ளெக்ஸ்"),
(255,"person","Governor of Madras addressed by Dupleix","Morse","டுப்ளெக்ஸ் நடுநிலையை கேட்ட மதராஸ் ஆளுநர்","மோர்ஸ்"),
(255,"person","British commodore whose squadron captured French vessels","Commodore Barnett","பிரெஞ்சு கப்பல்களை கைப்பற்றிய பிரிட்டிஷ் கடற்படைத் தலைவர்","கமொடோர் பார்னெட்"),
(255,"person","Nawab of Carnatic asked by Dupleix to help avoid war","Anwar-ud-din","போர் தவிர்க்க டுப்ளெக்ஸ் உதவி கேட்ட கர்நாடக நவாப்","அன்வர்-உத்-தீன்"),
(255,"person","French Governor of Isle of France contacted by Dupleix","La Bourdonnais","டுப்ளெக்ஸ் தொடர்பு கொண்ட Isle of France பிரெஞ்சு ஆளுநர்","லா போர்டோனே"),
(255,"number","French warships brought by La Bourdonnais","Eight","லா போர்டோனே கொண்டு வந்த பிரெஞ்சு போர்க்கப்பல்கள்","எட்டு"),
(255,"person","English squadron commander who faced La Bourdonnais","Peyton","லா போர்டோனேவை எதிர்கொண்ட ஆங்கில கடற்படைத் தலைவர்","பெய்டன்"),
(255,"number","English ships under Peyton","Four","பெய்டனின் கீழ் இருந்த ஆங்கிலக் கப்பல்கள்","நான்கு"),
(255,"date","Date of naval battle between Peyton and French squadron","6 July 1746","பெய்டன் மற்றும் பிரெஞ்சு படையணி போரின் தேதி","6 ஜூலை 1746"),
(255,"place","Place to which Peyton retreated","Hoogly, Calcutta","பெய்டன் பின்வாங்கிய இடம்","ஹூக்ளி, கல்கத்தா"),
(255,"date","Date French captured Madras","15 September 1746","பிரெஞ்சு மதராஸை கைப்பற்றிய தேதி","15 செப்டம்பர் 1746"),
(255,"person","Madras Governor asked to surrender to French","Morse","பிரெஞ்சுக்காரர்களிடம் சரணடைய கேட்ட மதராஸ் ஆளுநர்","மோர்ஸ்"),
(255,"date","Date English were forced to part with Madras","21 September 1746","மதராஸ் ஆங்கிலேயரிடமிருந்து பிரெஞ்சுக்காரர்களுக்கு சென்ற தேதி","21 செப்டம்பர் 1746"),
(256,"number","Force sent by Nawab of Carnatic to claim Madras","10,000 men","மதராஸைப் பெற கர்நாடக நவாப் அனுப்பிய படை","10,000 பேர்"),
(256,"person","Son of Nawab commanding force against French","Mahfuz Khan","பிரெஞ்சுக்காரர்களுக்கு எதிரான நவாப் படையை வழிநடத்திய மகன்","மஹ்ஃபூஸ் கான்"),
(256,"battle","Battle in which French defeated Nawab's forces near Adyar","Battle of San Thome and Adyar","அடையாறு அருகே பிரெஞ்சு நவாப் படையை தோற்கடித்த போர்","சாந்தோம் மற்றும் அடையாறு போர்"),
(256,"river","River crossed by French in battle against Mahfuz Khan","Adyar","மஹ்ஃபூஸ் கானுக்கு எதிரான போரில் பிரெஞ்சு கடந்து சென்ற ஆறு","அடையாறு"),
(256,"fort","British possession targeted by Dupleix after Madras","Fort St. David","மதராஸ் பின் டுப்ளெக்ஸ் குறிவைத்த ஆங்கிலக் கோட்டை","செயின்ட் டேவிட் கோட்டை"),
(256,"place","Location of Fort St. David","Cuddalore","செயின்ட் டேவிட் கோட்டை அமைந்த இடம்","கடலூர்"),
(256,"gift","Value of gifts offered by French to Nawab to withdraw aid to British","Rs. 40,000","ஆங்கிலேயருக்கு உதவி நிறுத்த நவாபுக்கு பிரெஞ்சு வழங்கிய பரிசுத் தொகை","ரூ. 40,000"),
(256,"person","British Rear-Admiral whose attempts to take Pondicherry failed","Boscowen","புதுச்சேரியை கைப்பற்ற முயன்று தோல்வியடைந்த பிரிட்டிஷ் ரியர்-அட்மிரல்","பாஸ்கோவன்"),
(256,"treaty","Treaty ending hostilities of First Carnatic War in India","Treaty of Aix-la-Chapelle","முதல் கர்நாடகப் போரின் இந்தியத் தகராறை முடித்த ஒப்பந்தம்","ஐக்ஸ்-லா-ஷபெல் ஒப்பந்தம்"),
(256,"date","Year Treaty of Aix-la-Chapelle was signed","1748","ஐக்ஸ்-லா-ஷபெல் ஒப்பந்த ஆண்டு","1748"),
(256,"exchange","Territory returned by French to British under Aix-la-Chapelle","Madras","ஐக்ஸ்-லா-ஷபெல் ஒப்பந்தத்தில் பிரெஞ்சு ஆங்கிலேயருக்கு திருப்பிய பகுதி","மதராஸ்"),
(256,"exchange","North American possession exchanged for Madras","Louisburg","மதராஸுக்குப் பதிலாக பிரான்சுக்கு கிடைத்த வட அமெரிக்க பகுதி","லூயிஸ்பர்க்"),

# Second Carnatic War
(256,"period","Second Carnatic War","1749–1754","இரண்டாம் கர்நாடகப் போர்","1749–1754"),
(256,"strategy","Dupleix's policy in second war","Intervene in succession disputes of Hyderabad and Arcot","இரண்டாம் போரில் டுப்ளெக்ஸின் கொள்கை","ஹைதராபாத் மற்றும் ஆர்க்காடு வாரிசுரிமை சச்சரவுகளில் தலையீடு"),
(256,"person","French-backed claimant to Hyderabad","Muzaffar Jung","பிரெஞ்சு ஆதரித்த ஹைதராபாத் வாரிசு","முஸஃபர் ஜங்"),
(256,"relation","Muzaffar Jung's relationship to Asaf Jah","Grandson","முஸஃபர் ஜங்குக்கும் ஆசப் ஜாவுக்கும் உள்ள உறவு","பேரன்"),
(256,"date","Year Asaf Jah died","1748","ஆசப் ஜா இறந்த ஆண்டு","1748"),
(256,"person","French-backed claimant to Carnatic","Chanda Sahib","பிரெஞ்சு ஆதரித்த கர்நாடக நவாப் உரிமைக்கோரியவர்","சந்தா சாஹிப்"),
(256,"alliance","Triple alliance in Second Carnatic War","French, Nizam claimant and Nawab claimant","இரண்டாம் கர்நாடகப் போரின் முக்கூட்டணி","பிரெஞ்சு, நிஜாம் உரிமைக்கோரியவர், நவாப் உரிமைக்கோரியவர்"),
(256,"fort","Only major British possession after loss of Madras","Fort St. David","மதராஸை இழந்த பின் ஆங்கிலேயரிடம் இருந்த முக்கியக் கோட்டை","செயின்ட் டேவிட் கோட்டை"),
(256,"person","English-backed claimant to Hyderabad","Nasir Jung","ஆங்கிலேயர் ஆதரித்த ஹைதராபாத் உரிமைக்கோரியவர்","நாசிர் ஜங்"),
(256,"person","English-backed Carnatic claimant after Anwar-ud-din's death","Muhammad Ali","அன்வர்-உத்-தீன் இறந்த பின் ஆங்கிலேயர் ஆதரித்த கர்நாடக உரிமைக்கோரியவர்","முகமது அலி"),
(256,"battle","Battle in which Anwar-ud-din was killed","Battle of Ambur","அன்வர்-உத்-தீன் கொல்லப்பட்ட போர்","ஆம்பூர் போர்"),
(256,"date","Year of Battle of Ambur","1749","ஆம்பூர் போரின் ஆண்டு","1749"),
(256,"result","Result for Chanda Sahib after Battle of Ambur","Entered Arcot as Nawab","ஆம்பூர் போருக்குப் பின் சந்தா சாஹிபின் நிலை","ஆர்க்காடு நவாபாக நுழைந்தார்"),
(256,"person","Son of Anwar-ud-din who escaped to Tiruchirappalli","Muhammad Ali","அன்வர்-உத்-தீனின் மகனாக திருச்சிராப்பள்ளிக்கு தப்பியவர்","முகமது அலி"),
(256,"person","Tamil merchant whose diary is a major source for Dupleix's period","Anandarangam Pillai","டுப்ளெக்ஸ் காலத்திற்கு முக்கிய ஆதாரமான தமிழ் வணிகர்","ஆனந்தரங்கம் பிள்ளை"),
(256,"period","Life span of Anandarangam Pillai","1709–1761","ஆனந்தரங்கம் பிள்ளையின் வாழ்நாள்","1709–1761"),
(256,"person","Father of Anandarangam Pillai","Tiruvengadam Pillai","ஆனந்தரங்கம் பிள்ளையின் தந்தை","திருவேங்கடம் பிள்ளை"),
(256,"office","Position given to Anandarangam by Dupleix in 1746","Chief Dubhashi and Chief Commercial Agent","1746இல் டுப்ளெக்ஸ் ஆனந்தரங்கத்துக்கு வழங்கிய பதவி","தலைமை துபாஷி மற்றும் தலைமை வணிக முகவர்"),
(256,"meaning","Meaning of Dubhashi","One who knows two languages","துபாஷி என்ற சொல்லின் பொருள்","இரு மொழிகளை அறிந்தவர்"),
(256,"period","Period covered by Anandarangam's Tamil diary","1736–1760","ஆனந்தரங்கத்தின் தமிழ் நாட்குறிப்பு உள்ளடக்கிய காலம்","1736–1760"),
(257,"date","Month and year Muzaffar Jung was made Nizam","December 1750","முஸஃபர் ஜங் நிஜாமான மாதம் மற்றும் ஆண்டு","டிசம்பர் 1750"),
(257,"person","French general sent by Dupleix to protect Muzaffar Jung","Bussy","முஸஃபர் ஜங்கை பாதுகாக்க டுப்ளெக்ஸ் அனுப்பிய பிரெஞ்சு தளபதி","புஸ்சி"),
(257,"person","Brother of Nasir Jung placed on Hyderabad throne by Bussy","Salabat Jung","புஸ்சி ஹைதராபாத் அரியணையில் அமர்த்திய நாசிர் ஜங்கின் சகோதரர்","சலாபத் ஜங்"),
(257,"place","City Chanda Sahib aimed to capture with French and Nizam help","Tiruchirappalli","பிரெஞ்சு, நிஜாம் உதவியுடன் சந்தா சாஹிப் கைப்பற்ற முயன்ற நகரம்","திருச்சிராப்பள்ளி"),
(257,"person","English officer whose Arcot strategy changed course of Second Carnatic War","Robert Clive","இரண்டாம் கர்நாடகப் போரின் போக்கை மாற்றிய ஆர்க்காடு திட்டத்தை முன்வைத்த ஆங்கில அதிகாரி","ராபர்ட் கிளைவ்"),
(257,"number","Frenchmen in Chanda Sahib's forces near Tiruchirappalli","900","திருச்சிராப்பள்ளி அருகே சந்தா சாஹிபின் படையில் இருந்த பிரெஞ்சுக்காரர்கள்","900"),
(257,"number","Soldiers of Muhammad Ali mentioned before Clive's Arcot move","5000","கிளைவின் ஆர்க்காடு நடவடிக்கைக்கு முன் முகமது அலியிடம் இருந்த வீரர்கள்","5000"),
(257,"number","Englishmen helping Muhammad Ali","Not more than 600","முகமது அலிக்கு உதவிய ஆங்கிலேயர் எண்ணிக்கை","600க்கு மேல் இல்லை"),
(257,"date","Date Clive left Fort St. David for Arcot","26 August 1752","கிளைவ் செயின்ட் டேவிட் கோட்டையிலிருந்து ஆர்க்காட்டிற்கு புறப்பட்ட தேதி","26 ஆகஸ்ட் 1752"),
(257,"number","English soldiers with Clive on Arcot expedition","200","கிளைவுடன் ஆர்க்காடு படையெடுப்பில் இருந்த ஆங்கில வீரர்கள்","200"),
(257,"number","Indian soldiers with Clive on Arcot expedition","300","கிளைவுடன் ஆர்க்காடு படையெடுப்பில் இருந்த இந்திய வீரர்கள்","300"),
(257,"ally","Regional ruler supporting Muhammad Ali","Raja of Mysore","முகமது அலியை ஆதரித்த பிராந்திய அரசர்","மைசூர் ராஜா"),
(257,"ally","Another ruler supporting Muhammad Ali","Ruler of Thanjavur","முகமது அலியை ஆதரித்த மற்றொரு அரசர்","தஞ்சாவூர் அரசர்"),
(257,"person","Son of Chanda Sahib sent to recover Arcot","Raja Sahib","ஆர்க்காட்டை மீட்க அனுப்பப்பட்ட சந்தா சாஹிபின் மகன்","ராஜா சாஹிப்"),
(257,"number","Force sent under Raja Sahib","3000","ராஜா சாஹிபின் கீழ் அனுப்பப்பட்ட படை எண்ணிக்கை","3000"),
(257,"date","Date Clive seized Arcot","31 August 1752","கிளைவ் ஆர்க்காட்டை கைப்பற்றிய தேதி","31 ஆகஸ்ட் 1752"),
(257,"duration","Length of siege Clive withstood at Arcot","53 days","கிளைவ் ஆர்க்காட்டில் தாங்கிய முற்றுகைக் காலம்","53 நாட்கள்"),
(257,"battle","Battle where English and Murari Rao faced French and Nawab forces","Battle of Arni","ஆங்கிலேயர் மற்றும் முராரி ராவ் பிரெஞ்சு-நவாப் படைகளை எதிர்கொண்ட போர்","ஆரணி போர்"),
(257,"person","Maratha ruler allied with English at Arni","Murari Rao","ஆரணி போரில் ஆங்கிலேயருடன் இருந்த மராத்திய தலைவர்","முராரி ராவ்"),
(257,"battle","Another battle mentioned in which Chanda Sahib's side was defeated","Kaveripakkam","சந்தா சாஹிப் தரப்பு தோற்கடிக்கப்பட்ட மற்றொரு போர்","காவேரிப்பாக்கம்"),
(257,"result","Fate of Chanda Sahib","Captured and executed","சந்தா சாஹிபின் இறுதி நிலை","பிடிக்கப்பட்டு மரணதண்டனை"),
(257,"result","Political result in Carnatic after Chanda Sahib's fall","Muhammad Ali became undisputed ruler","சந்தா சாஹிப் வீழ்ச்சிக்குப் பின் கர்நாடக அரசியல் விளைவு","முகமது அலி மறுக்க முடியாத ஆட்சியாளரானார்"),
(257,"action","French government's response to Dupleix's Indian policy","Recalled Dupleix","டுப்ளெக்ஸின் இந்தியக் கொள்கைக்கு பிரெஞ்சு அரசின் பதில்","டுப்ளெக்ஸை திரும்ப அழைத்தது"),
(257,"treaty","Treaty signed with English after Dupleix's recall","Treaty of Pondicherry","டுப்ளெக்ஸ் திரும்ப அழைக்கப்பட்ட பின் ஆங்கிலேயருடன் கையெழுத்தான ஒப்பந்தம்","புதுச்சேரி ஒப்பந்தம்"),
(257,"date","Year Treaty of Pondicherry was signed","1755","புதுச்சேரி ஒப்பந்த ஆண்டு","1755"),
(257,"principle","Main political clause of Treaty of Pondicherry","No interference in quarrels of Indian princes","புதுச்சேரி ஒப்பந்தத்தின் முக்கிய அரசியல் விதி","இந்திய இளவரசர் சச்சரவுகளில் தலையிடாமை"),

# Robert Clive box
(257,"date","Date of Robert Clive's birth","29 September 1725","ராபர்ட் கிளைவ் பிறந்த தேதி","29 செப்டம்பர் 1725"),
(257,"job","First East India Company position secured for Clive by his father","Writer","கிளைவின் தந்தை கிழக்கிந்தியக் கம்பெனியில் பெற்றுத் தந்த முதல் பதவி","ரைட்டர்"),
(257,"place","Indian city to which Clive was first sent","Madras","கிளைவ் முதலில் அனுப்பப்பட்ட இந்திய நகரம்","மதராஸ்"),
(257,"office","Fort of which Clive later became governor","Fort St. David","கிளைவ் பின்னர் ஆளுநரான கோட்டை","செயின்ட் டேவிட் கோட்டை"),
(257,"battle","Bengal battle won by Clive that launched British imperial rise","Battle of Plassey","கிளைவ் வென்ற வங்காளப் போர்; ஆங்கில பேரரசு எழுச்சியுடன் தொடர்புடையது","பிளாசி போர்"),
(257,"date","Year Clive secured Diwani rights","1765","கிளைவ் திவானி உரிமைகளைப் பெற்ற ஆண்டு","1765"),
(257,"wealth","Approximate personal fortune Clive took home","234,000 pounds","கிளைவ் எடுத்துச் சென்ற சுமார் தனிப்பட்ட செல்வம்","234,000 பவுண்டுகள்"),
(257,"income","Annual rental income from Clive's Bengal jagir","27,000 pounds","கிளைவின் வங்காள ஜாகீரிலிருந்து ஆண்டு வருமானம்","27,000 பவுண்டுகள்"),
(257,"inquiry","Political scrutiny Clive faced in England","Parliamentary inquiry over corruption allegations","இங்கிலாந்தில் கிளைவ் எதிர்கொண்ட அரசியல் விசாரணை","ஊழல் குற்றச்சாட்டுகள் தொடர்பான பாராளுமன்ற விசாரணை"),
(257,"fate","Fate of Robert Clive after exoneration","Committed suicide","விசாரணையில் விடுவிக்கப்பட்ட பின் ராபர்ட் கிளைவின் முடிவு","தற்கொலை செய்தார்"),

# Third Carnatic War and Bengal
(257,"period","Third Carnatic War","1756–1763","மூன்றாம் கர்நாடகப் போர்","1756–1763"),
(257,"war","Global conflict echoed in Third Carnatic War","Seven Years War","மூன்றாம் கர்நாடகப் போரில் பிரதிபலித்த உலகப் போர்","ஏழாண்டுப் போர்"),
(257,"period","Seven Years War","1756–1763","ஏழாண்டுப் போரின் காலம்","1756–1763"),
(257,"date","Year Seven Years War broke out in Europe","1756","ஐரோப்பாவில் ஏழாண்டுப் போர் தொடங்கிய ஆண்டு","1756"),
(257,"rivals","Main European rivals in Seven Years War in this chapter","Britain and France","இந்த அத்தியாயத்தில் ஏழாண்டுப் போரின் முக்கிய ஐரோப்பிய எதிரிகள்","பிரிட்டன் மற்றும் பிரான்ஸ்"),
(257,"region","One world region where Seven Years War was fought","North America","ஏழாண்டுப் போர் நடந்த உலகப் பகுதிகளில் ஒன்று","வட அமெரிக்கா"),
(257,"region","Another world region where Seven Years War was fought","West Africa","ஏழாண்டுப் போர் நடந்த மற்றொரு உலகப் பகுதி","மேற்கு ஆப்பிரிக்கா"),
(258,"battle","Bengal battle of 1757 changing British position","Battle of Plassey","1757இல் ஆங்கிலேயரின் நிலையை மாற்றிய வங்காளப் போர்","பிளாசி போர்"),
(258,"abuse","Trade privilege abused by East India Company in Bengal","Dastaks","வங்காளத்தில் கிழக்கிந்தியக் கம்பெனி தவறாகப் பயன்படுத்திய வாணிபச் சலுகை","தஸ்தக்குகள்"),
(258,"issue","Tax-related abuse by the Company","Not paying taxes to Nawab of Bengal","கம்பெனியின் வரி தொடர்பான தவறான நடைமுறை","வங்காள நவாபுக்கு வரி செலுத்தாமை"),
(258,"issue","Other Company abuse in Bengal","Involvement in internal trade","வங்காளத்தில் கம்பெனியின் மற்றொரு தவறான நடைமுறை","உள்நாட்டு வாணிபத்தில் தலையீடு"),
(258,"person","Nawab of Bengal at Plassey","Siraj-ud-daula","பிளாசி போரின் போது வங்காள நவாப்","சிராஜ்-உத்-தௌலா"),
(258,"fort","British fort captured by Siraj-ud-daula before Plassey","Fort William","பிளாசிக்கு முன் சிராஜ்-உத்-தௌலா கைப்பற்றிய ஆங்கிலக் கோட்டை","வில்லியம் கோட்டை"),
(258,"person","Company commander sent from Fort St. George against Siraj","Robert Clive","சிராஜுக்கு எதிராக செயின்ட் ஜார்ஜ் கோட்டையிலிருந்து அனுப்பப்பட்ட கம்பெனி தளபதி","ராபர்ட் கிளைவ்"),
(258,"person","Naval commander sent with Clive","Watson","கிளைவுடன் அனுப்பப்பட்ட கடற்படைத் தளபதி","வாட்சன்"),
(258,"incident","Contested British account of prisoners dying in Calcutta confinement","Black Hole Tragedy of Calcutta","கல்கத்தா சிறைச்சம்பவம் குறித்த சர்ச்சைக்குரிய பிரிட்டிஷ் கதை","கல்கத்தா கருந்துளைச் சம்பவம்"),
(258,"number","Number of European prisoners alleged to be confined in Black Hole story","146","கருந்துளை கதையில் அடைக்கப்பட்டதாகக் கூறப்பட்ட ஐரோப்பிய கைதிகள்","146"),
(258,"dimension","Room dimensions alleged in Black Hole story","18 by 15 feet","கருந்துளை கதையில் கூறப்பட்ட அறை அளவு","18 × 15 அடி"),
(258,"number","Alleged survivors of Black Hole story","23","கருந்துளை கதையில் உயிர் பிழைத்ததாகக் கூறப்பட்டோர்","23"),
(258,"assessment","Historical status of Black Hole story in chapter","Its veracity has been debated","பாடநூலில் கருந்துளைச் சம்பவத்தின் வரலாற்று நிலை","உண்மைத் தன்மை வரலாற்றாசிரியர்களால் விவாதிக்கப்பட்டது"),
(258,"result","Major consequence of Plassey for British","Changed from commercial to territorial power","பிளாசி போரின் ஆங்கிலேயருக்கான முக்கிய விளைவு","வணிக சக்தியிலிருந்து நில ஆட்சிச் சக்தியாக மாறினர்"),
(258,"person","Nawab installed in Bengal after Siraj-ud-daula","Mir Jaffar","சிராஜ்-உத்-தௌலாவுக்குப் பின் வங்காள நவாபாக நிறுவப்பட்டவர்","மீர் ஜாஃபர்"),
(258,"result","Status of Company sovereignty after Plassey","Sovereignty over Calcutta recognised","பிளாசிக்கு பின் கம்பெனியின் இறையாண்மை நிலை","கல்கத்தா மீது இறையாண்மை அங்கீகரிக்கப்பட்டது"),
(258,"result","Military territorial concession after Plassey","Land to maintain a military force","பிளாசிக்கு பின் கம்பெனிக்கு கிடைத்த இராணுவ நிலச் சலுகை","படை பராமரிக்க நிலம்"),
(258,"office","Political representative accepted at Nawab's court after Plassey","Company Resident","பிளாசிக்கு பின் நவாப் அரசவையில் ஏற்றுக்கொள்ளப்பட்ட கம்பெனி அதிகாரி","கம்பெனி ரெசிடெண்ட்"),
(258,"person","Nawab who replaced Mir Jaffar","Mir Qasim","மீர் ஜாஃபருக்கு பதிலாக வந்த நவாப்","மீர் காசிம்"),
(258,"issue","Reason Mir Qasim clashed with Company","Tried to assert independence","மீர் காசிம் கம்பெனியுடன் மோதிய காரணம்","சுதந்திரத்தை நிலைநிறுத்த முயன்றார்"),
(258,"battle","Battle fought in 1764 against Mir Qasim's alliance","Battle of Buxar","மீர் காசிமின் கூட்டணிக்கு எதிராக 1764இல் நடந்த போர்","பக்சார் போர்"),
(258,"date","Year of Battle of Buxar","1764","பக்சார் போரின் ஆண்டு","1764"),
(258,"ally","Mughal emperor allied with Mir Qasim at Buxar","Shah Alam II","பக்சார் போரில் மீர் காசிமுடன் கூட்டணியிட்ட முகலாய பேரரசர்","இரண்டாம் ஷா ஆலம்"),
(258,"ally","Nawab of Oudh allied with Mir Qasim at Buxar","Shuja-ud-daulah","பக்சார் போரில் மீர் காசிமுடன் கூட்டணியிட்ட அவத் நவாப்","ஷுஜா-உத்-தௌலா"),
(258,"result","Military reason cited for Company victory at Buxar","Superior arms","பக்சாரில் கம்பெனி வெற்றிக்குக் கூறப்பட்ட இராணுவ காரணம்","மேம்பட்ட ஆயுதங்கள்"),
(258,"treaty","Treaty following Battle of Buxar","Treaty of Allahabad","பக்சார் போருக்குப் பின் கையெழுத்தான ஒப்பந்தம்","அலகாபாத் ஒப்பந்தம்"),
(258,"date","Year Treaty of Allahabad was signed","1765","அலகாபாத் ஒப்பந்த ஆண்டு","1765"),
(258,"person","Company leader who signed Treaty of Allahabad with Shah Alam II","Robert Clive","இரண்டாம் ஷா ஆலமுடன் அலகாபாத் ஒப்பந்தத்தில் கையெழுத்திட்ட கம்பெனி தலைவர்","ராபர்ட் கிளைவ்"),
(258,"right","Major fiscal right obtained under Treaty of Allahabad","Diwani right to collect land revenue","அலகாபாத் ஒப்பந்தத்தில் கம்பெனி பெற்ற முக்கிய நிதி உரிமை","நிலவருவாய் வசூலிக்கும் திவானி உரிமை"),
(258,"region","One territory covered by Company Diwani rights","Bengal","கம்பெனி திவானி உரிமை பெற்ற பகுதி","வங்காளம்"),
(258,"region","One territory covered by Company Diwani rights","Bihar","கம்பெனி திவானி உரிமை பெற்ற பகுதி","பீகார்"),
(258,"region","One territory covered by Company Diwani rights","Orissa","கம்பெனி திவானி உரிமை பெற்ற பகுதி","ஒரிசா"),
(258,"district","One Bengal district obtained by Company","Burdwan","கம்பெனி பெற்ற வங்காள மாவட்டம்","பர்த்வான்"),
(258,"district","One Bengal district obtained by Company","Chittagong","கம்பெனி பெற்ற வங்காள மாவட்டம்","சிட்டகாங்"),
(258,"district","One Bengal district obtained by Company","Midnapur","கம்பெனி பெற்ற வங்காள மாவட்டம்","மித்னாபூர்"),
(258,"result","Political outcome after Allahabad Treaty","British virtually became rulers of Bengal","அலகாபாத் ஒப்பந்தத்திற்குப் பின் அரசியல் விளைவு","ஆங்கிலேயர் நடைமுறையில் வங்காள ஆட்சியாளர்களானார்கள்"),

# Third Carnatic War operations
(258,"place","French Bengal settlement captured by Clive after Seven Years War began","Chandranagore","ஏழாண்டுப் போர் தொடங்கிய பின் கிளைவ் கைப்பற்றிய பிரெஞ்சு வங்காள குடியேற்றம்","சந்திரநாகூர்"),
(258,"result","Effect of Chandranagore capture","French influence ended in Bengal","சந்திரநாகூர் கைப்பற்றலின் விளைவு","வங்காளத்தில் பிரெஞ்சு செல்வாக்கு முடிந்தது"),
(258,"person","French commander sent to India during Third Carnatic War","Count de Lally","மூன்றாம் கர்நாடகப் போரில் இந்தியாவுக்கு அனுப்பப்பட்ட பிரெஞ்சு தளபதி","கௌண்ட் டி லாலி"),
(258,"title","Lally's position in India","Supreme Commander of French forces","இந்தியாவில் லாலியின் பதவி","பிரெஞ்சு படைகளின் உச்ச தளபதி"),
(258,"fort","British fort captured by Lally","Fort St. David","லாலி கைப்பற்றிய ஆங்கிலக் கோட்டை","செயின்ட் டேவிட் கோட்டை"),
(258,"place","Kingdom besieged by Lally for money but siege abandoned","Thanjavur","பணம் பெற லாலி முற்றுகையிட்டு பின்னர் கைவிட்ட அரசு","தஞ்சாவூர்"),
(258,"reason","Reason Lally lifted siege of Thanjavur","Threat of British attack on Pondicherry","தஞ்சாவூர் முற்றுகையை லாலி கைவிட்ட காரணம்","புதுச்சேரி மீது ஆங்கிலத் தாக்குதல் அச்சுறுத்தல்"),
(259,"person","French general recalled from Hyderabad by Lally","Bussy","ஹைதராபாதிலிருந்து லாலி அழைத்த பிரெஞ்சு தளபதி","புஸ்சி"),
(259,"date","Year French lost Rajahmundry","1758","பிரெஞ்சுக்காரர்கள் ராஜமுந்திரியை இழந்த ஆண்டு","1758"),
(259,"date","Year French lost Masulipatam","1759","பிரெஞ்சுக்காரர்கள் மசூலிப்பட்டினத்தை இழந்த ஆண்டு","1759"),
(259,"person","Nizam who transferred Masulipatam and Northern Circars to British","Salabat Jung","மசூலிப்பட்டினம் மற்றும் வடக்கு சர்க்கார்களை ஆங்கிலேயருக்கு வழங்கிய நிஜாம்","சலாபத் ஜங்"),
(259,"territory","Territory transferred by Nizam from French to English","Northern Circars","நிஜாம் பிரெஞ்சுக்காரர்களிடமிருந்து ஆங்கிலேயருக்கு மாற்றிய பகுதி","வடக்கு சர்க்கார்கள்"),
(259,"place","Town captured by combined Bussy-Lally forces before Madras","Kanchipuram","மதராஸ் முன் புஸ்சி-லாலி படைகள் கைப்பற்றிய நகரம்","காஞ்சிபுரம்"),
(259,"number","Englishmen in Madras during French siege","About 800","பிரெஞ்சு முற்றுகையின் போது மதராஸில் இருந்த ஆங்கிலேயர்கள்","சுமார் 800"),
(259,"number","Indian soldiers in Madras during French siege","2500","பிரெஞ்சு முற்றுகையின் போது மதராஸில் இருந்த இந்திய வீரர்கள்","2500"),
(259,"date","Date Siege of Madras began","12 December 1758","மதராஸ் முற்றுகை தொடங்கிய தேதி","12 டிசம்பர் 1758"),
(259,"period","Month until which French siege of Madras continued","February 1759","மதராஸ் முற்றுகை நீண்ட மாதம்","பிப்ரவரி 1759 வரை"),
(259,"cause","Reason French abandoned Siege of Madras","Supplies were dwindling","மதராஸ் முற்றுகையை பிரெஞ்சு கைவிட்ட முக்கிய காரணம்","வழங்கல் குறைந்து கொண்டிருந்தது"),
(259,"person","British naval commander who brought relief fleet to Madras","General Pocock","மதராஸுக்கு நிவாரணக் கடற்படை கொண்டு வந்த ஆங்கிலத் தளபதி","ஜெனரல் பொக்காக்"),
(259,"battle","Decisive battle between Eyre Coote and Lally","Battle of Wandiwash","ஐர் கூட் மற்றும் லாலி இடையிலான தீர்மானப் போர்","வந்தவாசி போர்"),
(259,"date","Month and year of Battle of Wandiwash","January 1760","வந்தவாசி போரின் மாதம் மற்றும் ஆண்டு","ஜனவரி 1760"),
(259,"person","British commander at Wandiwash","Sir Eyre Coote","வந்தவாசி போரின் ஆங்கிலத் தளபதி","சர் ஐர் கூட்"),
(259,"person","French commander at Wandiwash","Lally","வந்தவாசி போரின் பிரெஞ்சு தளபதி","லாலி"),
(259,"person","French general defeated and captured at Wandiwash","Bussy","வந்தவாசியில் தோற்கடிக்கப்பட்டு பிடிக்கப்பட்ட பிரெஞ்சு தளபதி","புஸ்சி"),
(259,"place","Fort captured by British before final Pondicherry siege","Senji","இறுதி புதுச்சேரி முற்றுகைக்கு முன் ஆங்கிலேயர் கைப்பற்றிய கோட்டை","செஞ்சி"),
(259,"date","Date Pondicherry finally fell to British","4 February 1761","புதுச்சேரி ஆங்கிலேயரிடம் இறுதியாக வீழ்ந்த தேதி","4 பிப்ரவரி 1761"),
(259,"place","French west-coast possession captured by British in 1761","Mahe","1761இல் ஆங்கிலேயர் கைப்பற்றிய பிரெஞ்சு மேற்குக் கடற்கரை பகுதி","மாஹே"),
(259,"treaty","Treaty ending Seven Years War and Third Carnatic War","Treaty of Paris","ஏழாண்டுப் போரும் மூன்றாம் கர்நாடகப் போரும் முடித்த ஒப்பந்தம்","பாரிஸ் ஒப்பந்தம்"),
(259,"date","Year Treaty of Paris was signed","1763","பாரிஸ் ஒப்பந்த ஆண்டு","1763"),
(259,"restoration","French settlement restored under Treaty of Paris","Pondicherry","பாரிஸ் ஒப்பந்தத்தின்படி பிரெஞ்சுக்காரர்களுக்கு திருப்பிய குடியேற்றம்","புதுச்சேரி"),
(259,"restoration","French settlement restored under Treaty of Paris","Chandranagore","பாரிஸ் ஒப்பந்தத்தின்படி பிரெஞ்சுக்காரர்களுக்கு திருப்பிய குடியேற்றம்","சந்திரநாகூர்"),
(259,"possession","French possession retained after 1763","Pondicherry","1763க்குப் பின் பிரெஞ்சுக்காரர்கள் வைத்திருந்த பகுதி","புதுச்சேரி"),
(259,"possession","French possession retained after 1763","Karaikal","1763க்குப் பின் பிரெஞ்சுக்காரர்கள் வைத்திருந்த பகுதி","காரைக்கால்"),
(259,"possession","French possession retained after 1763","Yanam","1763க்குப் பின் பிரெஞ்சுக்காரர்கள் வைத்திருந்த பகுதி","யானம்"),
(259,"possession","French possession retained after 1763","Mahe","1763க்குப் பின் பிரெஞ்சுக்காரர்கள் வைத்திருந்த பகுதி","மாஹே"),
(259,"possession","French possession retained after 1763","Chandranagore","1763க்குப் பின் பிரெஞ்சுக்காரர்கள் வைத்திருந்த பகுதி","சந்திரநாகூர்"),
(259,"result","Final outcome of Carnatic Wars","English emerged as undisputed colonial power in India","கர்நாடகப் போர்களின் இறுதி விளைவு","ஆங்கிலேயர் இந்தியாவில் சவாலற்ற காலனித்துவ சக்தியாக உயர்ந்தனர்"),
(259,"transformation","Institutional transformation of English after Carnatic Wars","From trading company to territorial power","கர்நாடகப் போர்களுக்குப் பின் ஆங்கிலேய கம்பெனியின் மாற்றம்","வணிகக் கம்பெனியிலிருந்து நில ஆட்சிச் சக்தியாக மாறியது"),

# Glossary
(263,"term","Meaning of revamped in the glossary","Changed something again","கலைச்சொல் பகுதியில் revamped என்பதன் பொருள்","திருத்தியமைக்கப்பட்டது"),
(263,"term","Meaning of devastated in the glossary","Destroyed","கலைச்சொல் பகுதியில் devastated என்பதன் பொருள்","அழிந்தது"),
(263,"term","Meaning of political turmoil in the glossary","A state of confusion","கலைச்சொல் பகுதியில் political turmoil என்பதன் பொருள்","அரசியல் குழப்பநிலை"),
(263,"term","Meaning of incursion in the glossary","A sudden attack","கலைச்சொல் பகுதியில் incursion என்பதன் பொருள்","திடீர் தாக்குதல்"),
(263,"term","Meaning of metamorphosis in the glossary","A complete change","கலைச்சொல் பகுதியில் metamorphosis என்பதன் பொருள்","முழுமையான உருமாற்றம்"),
(263,"term","Meaning of stranded in the glossary","Struck by a difficult situation","கலைச்சொல் பகுதியில் stranded என்பதன் பொருள்","கைவிடப்பட்ட அல்லது சிக்கிய நிலை"),
(263,"term","Meaning of invincibility in the glossary","Impossible to defeat","கலைச்சொல் பகுதியில் invincibility என்பதன் பொருள்","வெல்ல முடியாத தன்மை"),
]

def norm(s): return " ".join(str(s).split()).strip()

facts=[]; seen=set()
for row in F:
    p,k,de,ae,dt,at=row
    key=(norm(de).lower(),norm(ae).lower())
    if key in seen: continue
    seen.add(key)
    facts.append({"page_en":p,"kind":k,"desc_en":norm(de),"ans_en":norm(ae),"desc_ta":norm(dt),"ans_ta":norm(at)})

pools=defaultdict(list)
for f in facts: pools[f["kind"]].append(f)

def distractors(f,n=3):
    cand=[x for x in pools[f["kind"]] if x["ans_en"].lower()!=f["ans_en"].lower()]
    cand.sort(key=lambda x:(abs(x["page_en"]-f["page_en"]),x["ans_en"]))
    out=[]; used=set()
    for x in cand:
        a=x["ans_en"].lower()
        if a not in used:
            out.append(x); used.add(a)
        if len(out)==n: break
    if len(out)<n:
        for x in facts:
            a=x["ans_en"].lower()
            if a!=f["ans_en"].lower() and a not in used:
                out.append(x); used.add(a)
            if len(out)==n: break
    return out

def make_opts(f,seed):
    arr=[f]+distractors(f,3)
    random.Random(seed).shuffle(arr)
    return [x["ans_en"] for x in arr],[x["ans_ta"] for x in arr],arr.index(f)

questions=[]; qid=1
def add(page,qen,qta,oe,ot,c,een,eta,typ):
    global qid
    questions.append({
      "id":f"C11H16-Q{qid:04d}",
      "quiz":(qid-1)//20+1,
      "page_en":page,
      "q_en":qen,"q_ta":qta,
      "opts_en":oe,"opts_ta":ot,
      "correct":c,"exp_en":een,"exp_ta":eta,"type":typ
    })
    qid+=1

for i,f in enumerate(facts):
    een=f'{f["desc_en"]}: {f["ans_en"]}.'
    eta=f'{f["desc_ta"]}: {f["ans_ta"]}.'
    templates=[
      ("direct","What is the correct textbook answer for: ","இதற்கான சரியான பாடநூல் விடை எது: "),
      ("association","Which option is correctly associated with the following description: ","பின்வரும் விளக்கத்துடன் சரியாகப் பொருந்தும் விடை எது: "),
      ("recognition","Identify the term/person/place that the textbook links with this fact: ","இந்த பாடநூல் உண்மையுடன் தொடர்புடைய பெயர்/சொல்/இடத்தைத் தேர்ந்தெடுக்கவும்: ")
    ]
    for j,(typ,pfx_en,pfx_ta) in enumerate(templates):
        oe,ot,c=make_opts(f,16000+i*37+j*100003)
        add(f["page_en"],pfx_en+f["desc_en"]+"?",pfx_ta+f["desc_ta"]+"?",oe,ot,c,een,eta,typ)

comb_en=["Both I and II are correct","I is correct; II is incorrect","I is incorrect; II is correct","Both I and II are incorrect"]
comb_ta=["I மற்றும் II இரண்டும் சரி","I சரி; II தவறு","I தவறு; II சரி","I மற்றும் II இரண்டும் தவறு"]
for i,f in enumerate(facts):
    g=facts[(i+1)%len(facts)]
    mode=i%4
    iok=mode in (0,1); iiok=mode in (0,2)
    wf=distractors(f,1)[0]; wg=distractors(g,1)[0]
    a1=f["ans_en"] if iok else wf["ans_en"]; t1=f["ans_ta"] if iok else wf["ans_ta"]
    a2=g["ans_en"] if iiok else wg["ans_en"]; t2=g["ans_ta"] if iiok else wg["ans_ta"]
    qen=f'Consider the following statements:\nI. {f["desc_en"]} — {a1}.\nII. {g["desc_en"]} — {a2}.\nWhich option is correct?'
    qta=f'பின்வரும் கூற்றுகளைக் கவனிக்கவும்:\nI. {f["desc_ta"]} — {t1}.\nII. {g["desc_ta"]} — {t2}.\nசரியான விடை எது?'
    exen=["Both Statement I and Statement II are correct.","Statement I is correct and Statement II is incorrect.","Statement I is incorrect and Statement II is correct.","Both Statement I and Statement II are incorrect."][mode]
    exta=["கூற்று I மற்றும் II இரண்டும் சரி.","கூற்று I சரி; கூற்று II தவறு.","கூற்று I தவறு; கூற்று II சரி.","கூற்று I மற்றும் II இரண்டும் தவறு."][mode]
    add(max(f["page_en"],g["page_en"]),qen,qta,comb_en,comb_ta,mode,exen,exta,"statement-analysis")

# exact de-duplication and renumbering
unique=[]; sigs=set()
for q in questions:
    s=(q["q_en"],tuple(q["opts_en"]))
    if s in sigs: continue
    sigs.add(s); unique.append(q)
questions=unique
for i,q in enumerate(questions,1):
    q["id"]=f"C11H16-Q{i:04d}"
    q["quiz"]=(i-1)//20+1

quiz_count=(len(questions)+19)//20
sets=[{"id":i,"title_en":f"Quiz {i} · Competitive Review","title_ta":f"வினாடி வினா {i} · போட்டித் தேர்வு மீள்பார்வை"} for i in range(1,quiz_count+1)]
counts=Counter("ABCD"[q["correct"]] for q in questions)
dups=len(questions)-len({(q["q_en"],tuple(q["opts_en"])) for q in questions})

out={"meta":{
  "board":"Tamil Nadu State Board","class":11,"subject":"History","edition":2025,"unit":16,
  "unit_en":"The Coming of the Europeans","unit_ta":"ஐரோப்பியர்களின் வருகை",
  "source":"Government of Tamil Nadu Higher Secondary First Year History, Revised Edition 2025, English and Tamil editions supplied by the user",
  "total_questions":len(questions),"base_facts":len(facts),"quiz_sets":sets,
  "question_style":"Maximum useful source-grounded bilingual competitive-exam coverage from Unit 16: Mughal and south Indian political conditions, Indian agriculture/manufacturing/merchant networks and Indian Ocean trade; Portuguese, Dutch, French, Danish and English settlements; missionary and printing activity; slave trade; East India Company bases in Madras, Bombay and Bengal; the three Carnatic Wars; Plassey, Buxar and the shift from commercial to territorial power.",
  "quality_policy":"Four-option bilingual MCQs grounded in the supplied 2025 textbook. Activities, assignments and low-value procedural material are excluded. Distinct textbook facts are reinforced through direct recall, association, recognition and statement-analysis formats. The chapter's own framing is preserved.",
  "page_reference_note":"page_en refers to the printed English textbook page.",
  "qa_all_four_options":all(len(q["opts_en"])==4 and len(q["opts_ta"])==4 for q in questions),
  "qa_valid_correct_indexes":all(0<=q["correct"]<4 for q in questions),
  "qa_duplicate_ids":len(questions)-len({q["id"] for q in questions}),
  "qa_exact_duplicate_question_options":dups,
  "qa_answer_position_counts":dict(counts)
},"questions":questions}

os.makedirs(os.path.dirname(OUT),exist_ok=True)
with open(OUT,"w",encoding="utf-8") as fp:
    json.dump(out,fp,ensure_ascii=False,indent=2)
print(f"Wrote {OUT}: {len(facts)} facts, {len(questions)} questions, {quiz_count} quizzes")
